### ISSUE TITLE
Wii U Pro Controller doesn't pair

### ISSUE THREAD

**Issue by Raddock** [OpenEmu/OpenEmu#1039]
When I go to the input menu and select "Add a Wiimote", then press the pairing button on the back of my controller, then "Start Scanning" the pairing window disappears as soon as I select Start Scanning, and the controller doesn't pair.

Am I supposed to see any kind of confirmation window saying it's paired?  My controller doesn't show up as being paired.

I'm using a Mac Pro Early 2008, 3Ghz 8 core, 8GB RAM.  On Mavericks 10.9.1

**Comment by MasterOs** [comment]
Sorry to tag onto this a year after it was posted (and closed), but I was having the same issue with no solutions.  I serendipitously stumbled upon a fix though.  I had meticulously followed the instructions in the OpenEmu help guide, but to no avail.  My issue was exactly the way Raddock described:  attempted to pair the Wii U Pro controller in OpenEmu, but after clicking the red sync button on the controller and then the "start scanning" button in OE, the pairing window closed and nothing happened.  My controller wasn't listed in the input dropdown window.  When I went through the steps to pair directly to my Mac via the bluetooth dropdown in the menu bar, it would recognize the controller and attempt to pair, but I would get the message that the pairing failed.  I tried clicking the red sync button again before, during, and after pairing, but nothing worked.  I also clicked on the option button in the bluetooth menu next to the controller, but it asked me for a pin (I tried guessing several easy combinations, but none worked).  I also read on another thread elsewhere that it helps if you pair your Wii U Pro to a Wii U first, so I did that but the outcome was the same.  I also deleted all paired Wiimotes from the Bluetooth menu and tried everything again but it didn't make a difference.

Eventually, what worked was:  I grabbed a Wii motion plus Wiimote that I had successfully paired in the past.  I started the pairing process on the Wii U Pro controller.  When OE didn't recognize the controller after clicking on "start scanning", I pushed the red sync button on the back of the Wii Motion Plus Wiimote to see if that one would pair.  Suddenly, they both paired and my Wii U Pro magically appeared in the input dropdown menu in OE.  

Sorry about the long, outdated post, but I just thought it might help someone else, since I was so frustrated after trying everything I had read online with no success.
