### ISSUE TITLE
Support for DropBox or other cloud storage and better support for NAS storage

### ISSUE THREAD

**Issue by beeksiwaais** [OpenEmu/OpenEmu#1109]
It should be a good idea, no ?

**Comment by ddbehsnilian** [comment]
I have managed to get this to work even if it is unsupported at the moment. Now let me clarify that I am I no way affiliated with the OpenEmu team, I’m just a thankful dude tryinng to give back a little. Having said that, I am trying this at my own risk and if anyone tries to do the same I will not be responsible for any consequences. This should only be attempted by people who know what they are doing. Even so I would advice to have a recent backup before embarking on this adventure.

Alright, now to the fun part.

I have found that it is possible to sync the entire OpenEmu Library, including all the stuff from ~/Library/Application Support/OpenEmu over Dropbox. I find this useful since I have a Mac Mini at home and a MacBook Pro for the road.

First of all I made sure to have the exact same version of the Experimental release of OpenEmu on both computers. Also important, whenever I update one I immediately update the other to the same version, before I even open the app. This is to avoid any problems that may stem from version differences.

If you already have your OpenEmu Library folder on Dropbox then skip this, otherwise create a new library inside Dropbox, close OpenEmu, overwrite the new empty library with the one with all your data. Relaunch OpenEmu.

Now for the OpenEmu folder inside ~/Application Support we’ll do the old symlink “switcheroo" trick.

	1. Copy the OpenEmu folder from ~/Application Support to somewhere on your Dropbox

		If you want things nice and tidy you can do as I did and create a Emulation folder on your Dropbox containing your game library folder and your application support/openemu folder

	2. Delete the OpenEmu folder form ~/Application Support and create a symlink to the folder’s new location inside Dropbox. This will “fool” OpenEmu into thinking all the support files are where they are supposed to be when they are in fact in your Dropbox. If you need to freshen up your symlink creating skills you might want to give Path Finder a try. It really does give Finder a run for it’s money. Otherwise you can use this command in the Terminal ln -s /path/to/original /path/to/symlink replacing the values as needed.

Anyway, whis is what you should end up with:

![7fcecc08-3da9-11e5-9f98-4d044063624f](https://cloud.githubusercontent.com/assets/13107306/9152162/f67dda48-3df3-11e5-8a46-e1e436b14282.png)

![914278b8-3da9-11e5-84fa-9a07f011a51b](https://cloud.githubusercontent.com/assets/13107306/9152167/08e6a840-3df4-11e5-9b7f-115dd10696e9.png)

**Comment by clobber** [comment]
@ddbehsnilian Thanks but please stop blasting every issue related to this.

**Comment by ddbehsnilian** [comment]
I apologize if I caused any inconvenience, my intention was to help out everyone in the same situation because I saw people being redirected to other posts with no answer. This makes finding an answer much more difficult than it should be. I respect the fact that you choose not to support Dropbox for now, but I don't see the harm in helping everyone with the same problem when I have found a good solution. Until your team offers a better, more polished solution (like merging the application support folder into the library, making it a bundle and officialy supporting Dropbox) I think my suggestion will help out a bunch of people. This is 2015, cloud sync is nothing too complex anymore, I'm sure your team has solved much more difficult challenges. I only hope they have the time to work on it.

Honestly, out of curiosity, what harm did I cause by "blasting" this information on the posts that people were being sent to (with no solution by the way)? If I did, I apologize again.

**Comment by clobber** [comment]
@ddbehsnilian The answer is that dropbox or other syncing services are and always will be unsupported, so let's not push it.  The duplicate issues link back to the originals in which you already posted your work around, so you do not need to repost it in each one. It's redundant and I don't want meta conversions about the same subject in multiple places. Good example being a time could come when your suggested work around no longer works, or perhaps it simply is not a good work around, and now it's in 9 locations instead of just one. Furthermore, this sort of thing is really best left to the subreddit since the issue pages are for bug reporting.

Thanks, hope you understand.

**Comment by ddbehsnilian** [comment]
I do understand, and I honestly asked out of curiosity since I'm a total noob when it comes to GitHub. Thank you for taking the time to explain that, it makes total sense. I will use the subreddit in the future for things like this. If you don't mind my suggestion, maybe you can include a link to it in the openemu site, since it links to the GitHub but not the subrreddit. I only posted here because it was linked in the openemu official site.

Also, pardon me for "pushing it" but I really wish you would be more open to the possibility of supporting sync services. I understand they are not supported now, but to say they will "always be unsupported" seems a bit closed minded to me, specially coming from a software with the word "open" in it's name. Also, not that there has to be one, but I haven't seen an explanation on why sync services won't be supported in the future. I imagine lots of people would benefit from cloud sync functionality.

In any case, I appreciate the work you are doing, and all the moving parts involved.
