### ISSUE TITLE
Support Game Controller framework

### ISSUE THREAD

**Issue by peterb12** [OpenEmu/OpenEmu#1113]
A lot of the game controller support in emulators like this is typically done through one-off drivers (e.g. the Tattiebogle.net drivers for the wired xbox controller).  That stuff is great when it works, but seems to be a moving target and tends to break with OS releases.

I'd like to propose that OpenEmu support the Game Controller framework:

https://developer.apple.com/library/mac/documentation/ServicesDiscovery/Conceptual/GameControllerPG/Introduction/Introduction.html

... as the solution most likely to support the widest array of Mac-compatible controllers, and being the least likely to break over time.

Thanks for your consideration.

**Comment by IngwiePhoenix** [comment]
I know this issue is closed and all, but I wanted to ask back on the current status of this. MFi gamepads seem to be growing in popularity and i see people buying them as well. Since iOS and OS X both support the same gadgets in this regard, it would be nice to know if this will be integrated.

... because otherwise, I gotta go and find my old USB gamepad. x)

Kind regards, Ingwie.
