### ISSUE TITLE
Send keystroke to OpenEmu with applescript

### ISSUE THREAD

**Issue by Beatgodes** [OpenEmu/OpenEmu#1169]
I'm trying to control OpenEmu programmatically by sending keystrokes to it using another application.

Using 

```
osascript -e 'tell application "System Events" to keystroke "[somekey]" '
```

works fine for any other application. However, with OpenEmu, it does not (assuming ofc OpenEmu is the active window).

**Comment by bradorego** [comment]
Not to necro a post from 2014, but a) the Lua scripting branch hasn't been updated since 2012. I don't know how much core has changed, but I doubt it's even still functional at this point, and b) is there any documentation on how to use Osculator to send keystrokes? Because being an OSX app that doesn't support AppleScript (which everyone knows and is widely supported), and then pointing to some obscure 3rd party software (which nobody knows) seems like a really poor solution.
