### ISSUE TITLE
Fullscreen - Set Aspect Ratio / Non-Linear Stretch

### ISSUE THREAD

**Issue by ditrist** [OpenEmu/OpenEmu#1280]
Request for such a feature is a must for users of non 4/3 Screens, which makes up just about everyone. Any other emulator has this function, to deny others of the feature because one personally dislikes it is just being ignorant. not having this feature makes this emulator useless. No offense, i think the software is great. but why would I use it, if it can't do what others can.

**Comment by KimCheeWarrior** [comment]
let me try a different approach since the current one doesnt seem to be working. ive been using emulators on Mac OS since Mac OS 7 and as far back as I can remember there has almost always been an option to stretch the image to fill the screen regardless of what size screen you might be using. even early versions of snes9x for mac os impressively made this feature available even on mac os's well before "x" came along. throughout the years ive seen many emulators for mac come and go, mr bannister has had a hand in developing either in conjunction or nearly single handedly produced a huge portion of my most beloved emulators for mac os for years. ive even paid for his emulator enhancer add-on which adds many so called "unpopular" and "ugly" video modes that are and always have been under heavy demand. i can understand the frustration of people demanding things without asking when you spend much time on developing software without making a dime. for emulators that ask for a donation or even shareware emulators, i try to pay as much as i can afford because i know they get nothing in return. look at what im saying as more like a suggestion to improve your emulator so people will look at it in higher regard than they already do. its quite remarkable how many systems this emulator supports as well as the options that are available consistently regardless of what system youre playing, very impressive. i know youve tried very hard to create the ultimate retro gaming software and you are much appreciated for blessing us with such a troublefree and easy to use emulator. i dare say this gives mess a run for its money. i can respect that you might want to keep the experience wholesome and as close to the originals as much as possible but please dont automatically assume that everyone thinks its ugly or everyone might think that its utterly ridiculous for many users of your emulator to want a feature like that. not everyone feels like posting like this on blog or forums, etc. because im guessing theyre like me and they just dont wanna deal with the internet's finest (sarcasm duely noted).

**Comment by KimCheeWarrior** [comment]
oh and a direct reply to capeman a bit further up, yes, i very much would like to play stretchy super mario bros right along with stretchy mega man, stretchy streets of rage, stretchy sonic the hedgehog and even stretchy phantasy star. believe it or not some of us actually find the entire screen being filled up as being more immersive. although many of us have actually played most of these games on their respective consoles during their prime, when playing them again some of us wouldnt mind a new way of playing them, hence the visual effects and smoothing effects provided with many emulators nowadays. no disrespect intended and i know some of your comments were directed towards posters who didnt use the right words to ask for a new feature, but just because someone really wants a feature and one of you might think its ridiculous, dont try to make a fool out of them out of them like many of the comments ive read here from so called professionals. its uncalled for. that being said, im still much obliged to all the hard work put into this emulator and wish the best of luck to you on your future projects.

**Comment by clobber** [comment]
Not happening.
