### ISSUE TITLE
Wii U Pro Controller mapping issues

### ISSUE THREAD

**Issue by superweeninja** [OpenEmu/OpenEmu#1442]
Wii U Pro Controller will pair successfully. Left and right analog sticks will occasionally map, but usually there is no response with any buttons. OpenEmu automatically maps controls for systems like SNES and GBA, but still won't allow changes to systems like N64 and Playstation. I'm running the most recent update of OpenEmu, but I'm using Experimental to play N64 games (the main reason I wanted the Pro Controller was to use it for N64 and Playstation). Would the Experimental version be why the controls won't map?

**Comment by luserppc** [comment]
I have the same issue, and only verysofttoiletpaper's advice worked.  Generally, hitting the right analog trigger will register, then you can map other buttons.  Verysofttoiletpaper's  advice allowed me to set my Home button to Quick Load.
Glitch occurred in OSX 10.10.2, OE Ver 1.0.4 663-g0130d6b-Release

**Comment by diotro** [comment]
I too had difficulty with using my **Wii U Pro Controller** and prior to the fix, every regular end-user method I performed was nil. I was going to give up hope at one point; and chalk it up to the fact that fixing it has something to do with some directory buried, manually edited, .plist conflict... and then it dawned on me. 

After reading the guide from stem to stern once more, I embarrassingly admit that I had overlooked the importance of following EXACT instructions. For anyone who hasn't read the section I'm referring to, [here is a direct link.](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing) After reading it word for word, (unfortunately due to my ADHD, I HAVE to read this way sometimes.) I realized that even though I recently uninstalled USB Overdrive and at one time in the past had tried WJoy, there are lingering remnants within the filesystem. So in an act of desperation, here is what I did.

* I first removed any paired devices using the Bluetooth PreferencePane.
* Since some of them stubbornly would not dissapear after I clicked the X next to the device name, I figured that I'd have to do it by editing the .plist
* I opened the .plist within my home folder's Library and it was lacking everything except MAC addresses. After that didn't work, I saved the .plist to my desktop and removed it from the Preferences directory. 
* Then instead of attempting to edit the main OS X Library folder's Preference .plist, I just moved it to the desktop as a backup, and left the Preferences folder without the file entirely. Obviously this was done so I could allow Mac OS X to recreate a fresh new one,  *at least that's what I was hoping it would do.*
* I used an application called "CleanMyMac 3" to remove any remaining files that had something to do with USB Overdrive and WJoy.
* Also referring back to the OpenEmu User Guide, I ran the command in Terminal to remove any leftover kext files. ``` sudo kextunload -b com.alxn1.driver.wjoy ```
* Note: I made sure Bluetooth was enabled the entire time I performed this procedure. This is because I wanted it to be ready to go after executing the following last steps.
* I shutdown my Macbook Pro and performed an [SMC reset](https://support.apple.com/en-us/HT201295), making sure that nothing was plugged into the I/O ports, excluding the MagSafe 2 power adapter plug.
* Finally, just to be extra diligent I executed a [reset of the NVRAM/PRAM](https://support.apple.com/en-us/HT204063) and waited for it to startup, making sure I heard that **second** chime before the  logo appears.
* Once I was at the desktop and all of my menubar applications sorted out, I immediately opened OpenEmu, rather than going straight to the Bluetooth prefs. 
* After opening the OpenEmu preferences and going to the controller settings, I attempted to add the Wii U Pro Controller as normal, making sure my Wii U wasn't on of course, and leaving all other peripherals unplugged. 

**Success!**

I concluded that it was a combination of all of things I've previously mentioned. Sometimes being a power user can make the simplest of bugs, hairy as ever! We tend to overlook the big picture, and focus primarily on only one of the causes of a large issue; at least in my case. Or worse, reinstall the entire OS in a blanket of ignorance and/or lack of patience. 

Hopefully this method will be of some use for users who are/were in a similar situation.

**Comment by aheckmann** [comment]
In my case, I was able (after restarting / unpairing many many times) to get the classic control to map. However, when I play a game (SuperNES, NES, N64), no buttons work.

**Comment by clobber** [comment]
The official Nintendo Wii U Pro Controller is well-supported as of OpenEmu 2.2.
