### ISSUE TITLE
Experiencing some serious lag (external display through HDMI)

### ISSUE THREAD

**Issue by edgonzalez32** [OpenEmu/OpenEmu#1519]
Late 2013 Retina MacBook Pro
2.3 i7 Quad Core
16 GB of ram
Nvidia GeForce GT 750M w/ 2 GB of ram

I've tried switching every filter and I still have the same experience, no matter what core I'm using, which are these:
- SNES9x
- GenesisPlus
- Gambatte

If you need more info from me let me know!

**Comment by F4LL3N** [comment]
I just wanted to add that I am having the same issue. I have a 2010 Mac Mini running HDMI into a Panasonic Viera TV. My Mac is running Yosemite and I have what seems to be sound lag (but possibly overall game lag) with any core and any game that I try to use. Running OpenEmu on my 2014 Macbook Air with no external display (Mavericks) gives me no issues.

I have tried every filter on the Mac Mini with no luck - all give me the same lag issue. It might be useful to know however, that if I access my Mac Mini through VNC the lag greatly improves and is pretty much back to normal - and this is when still viewing through the external display. It is a very odd thing.

**Comment by F4LL3N** [comment]
Hi I just wanted to add that I have solved the problem. My TV is set to PAL 50Hz (as I am in the UK). I changed it to NTSC - 60Hz and it has solved the problem! Is it possible to add a PAL setting (filter?) of some description in OpenEmu?

**Comment by stillmoms** [comment]
I’m experiencing notably worse performance emulating SNES games on El Capitan with any display that’s not the “primary” display. I’m running it on a Mac Pro with two displays (using the new Yosemite-and-later multi-monitor Mission Control behavior), and if I run it on the primary display it runs perfectly using Higan (Snes9X still exhibits stuttering audio, suggesting it’s not running at 60fps, which is odd considering I was using Snes9x 10 years ago to play SNES games at full speed with no issues) no matter what filter I turn on. If I drag it to the secondary display it lags to all hell. To be fair, I’m running NVIDIA’s web drivers because this machine has a GeForce GTX 960 in it, so I’m not sure you have the ability to test such a config, but I figured I’d report it anyway. The lag is MUCH worse on a secondary display, but it seems like performance has dropped off a cliff for me with OpenEmu 2.0.1 vs. 1.0.5.

**Comment by CSindony** [comment]
I'm having a lot of lagging/slow mo issues with N64 games on 2.0.1 that I didn't have before with the OpenEmu 1.0.5 on Lion. I have a MacBook Pro 15" Late 2011, 2.4 GHz Intel Core i7, 4GB RAM, Intel HD Graphics 3000 384 MB. I'd like to mention that I didn't have any issue with this setup when I had 1.0.5. Things that happen when I play N64 games: Very bad/ laggy sound, slow/laggy video and gameplay. I've tried with the "Nearest Neighbor" filter and some others, still no change. I'll list the games that I've been having trouble with:

Ocarina of Time, Donkey Kong 64, Mario Tennis, Mario Golf, Banjo-Tooie, Banjo-Kazooie (In this case, I have a strange 2x speed issue, like the game is always on fast forward), Conker's Bad Fur Day, Diddy Kong Racing (specially sound issues), etc.

I assume that I'm not the only one having this type of issues on 2.0.1 with the N64 games.
