### ISSUE TITLE
Translations guide

### ISSUE THREAD

**Issue by clobber** [OpenEmu/OpenEmu#1685]
With 1.0.4 we introduced initial support for translations. We should write a guide in the wiki for help with using @cyco's OELocalizer tool (https://github.com/cyco/OELocalizer) to assist others that would like to localize.

**Comment by cyco** [comment]
Turns out it wasn't the best idea to use a custom app for translations. Especially keeping track of changes turned out to be difficult.

Instead we're just going to edit .strings directly. Guide and contributor list here https://github.com/OpenEmu/OpenEmu/wiki/Developers:-Translation-Guide-(First-Draft)
