### ISSUE TITLE
N64 Analog Sensitivity Controls

### ISSUE THREAD

**Issue by Navitas56** [OpenEmu/OpenEmu#1709]
Some games are very specific about the amount of pressure that you use.
An example would be tip-toeing in Banjo-Tooie.

Without being able to control the sensitivity I cannot complete some areas as the character walks too fast.

Please implement a method to modify sensitivity.

**Comment by nilberts** [comment]
Hey clobber, any updates on the fix for issue #1303? I'd love to know if that is being worked on or if a fixed is planned soon. The current sensitivity setting makes shooting arrows in Zelda pretty difficult. I think it would be fine if instead of implementing a way to change this manually, you could just hard code a calibration that is a little more accurate to typical N64 gameplay. I mean, when you are playing a real N64 you don't need to calibrate deadzones and stuff like that, it just has one default setting that works for every game. This could be easier to do than adding an entire calibration module to the interface.

**Comment by DavidTortolo** [comment]
I have the same issue with the latest release, I believe this PR doesn't solve the issue. It would be nice to have a slider to set the sensitivity, or a value field to enter floats.
