### ISSUE TITLE
Pokemon white 2 problem

### ISSUE THREAD

**Issue by randomyuan** [OpenEmu/OpenEmu#1761]
So I been playing Pokemon white 2 for a while and Openemu worked fine, but now I can't continue the game, because it crashes when I go inside Drayden's house. (I need to enter to continue the game)

**Comment by berrypunny** [comment]
Hello, I know I am responding rather late, but if you wish to continue to play your White 2 ROM, what I found that worked for me was to stop using the OpenEmu emulator, and download the 9.11 DesMume and migrate your battery save there. The current version of OpenEmu only has 9.10 or something like that and I believe the 9.11 fixed this bug.

**Comment by clobber** [comment]
>The current version of OpenEmu only has 9.10 or something like that and I believe the 9.11 fixed this bug.

No, we ship with 0.9.11. The bug is partly with the Dynamic Recompiler, which we have enabled by default for performance reasons. Desmume standalone does not have it enabled. However, this is not the only problem with Pokemon games and Desmume. The AP measures built in to these games are sensitive to timings on real hardware. Desmume does not emulated accurate timings and you will still run into problems. This is why Desmume states in their FAQ that these games are unsupported.
