### ISSUE TITLE
Nintendo DS-Pokemon Black Freeze when going to dreamyard (Please Fix!)

### ISSUE THREAD

**Issue by ultim8trix** [OpenEmu/OpenEmu#1778]
I was playing Pokemon Black using Openemu. And then i was asked to go to the dreamyard.
When i go to the dreamyard, openemu freezes then crashed. If that happens i can never finish the game. Please fix it!

**Comment by joshvickerson** [comment]
I think it's more of an issue with the DeSmuME core. There's a sticky on their <a href="http://forums.desmume.org/viewtopic.php?id=4124">support forum</a> that says the Pokemon games aren't supported.

That said, I'm not sure how active the support forums are any more, nor does it seem the DeSmuME project has had much development recently. Maybe someone else knows more.

**Comment by clobber** [comment]
Yeah there are several tickets all related to this so please search next time. Desmume issue.

**Comment by dbheudfbhdsbfjhshfb** [comment]
argghh i hate fennel i want to move on!!! and the dowload site said pokemon games were working and supported. dont ask me which on i have forggoten

**Comment by ifonefox** [comment]
dbheudfbhdsbfjhshfb: 
1. You don't need to comment on every issue about your problems with DeSmuME
2. The latest DeSmuME download is [here](http://downloads.sourceforge.net/project/desmume/desmume/0.9.10/desmume-0.9.10-mac.dmg?r=&ts=1421169124&use_mirror=iweb) (if that link doesn't work, try [here](http://sourceforge.net/projects/desmume/files/desmume/0.9.10/desmume-0.9.10-mac.dmg/download))
3. If it doesn't run in DeSmuME, it won't run in OpenEmu, because OpenEmu uses DeSmuME to run DS games.

**Comment by alanah2005** [comment]
How do I download pokemon black on nds4ios with out coolrom?

**Comment by cyco** [comment]
Not really the place for nds4ios, colors or any other part of that question.
