### ISSUE TITLE
Genesis inaccurate colors

### ISSUE THREAD

**Issue by LordHDL** [OpenEmu/OpenEmu#1785]
Use Digital Color Meter to compare native color values.  OpenEmu's version of Genesis Plus has brighter colors.

![kega 1](https://cloud.githubusercontent.com/assets/5182602/5789166/b560556a-9e2d-11e4-9848-fe277f94ab52.png)
![openemu 1](https://cloud.githubusercontent.com/assets/5182602/5789167/b56b0b2c-9e2d-11e4-99bf-eb091b866947.png)
![kega 2](https://cloud.githubusercontent.com/assets/5182602/5789168/b571e172-9e2d-11e4-9ef8-34369992cb74.png)
![openemu 2](https://cloud.githubusercontent.com/assets/5182602/5789169/b5790d9e-9e2d-11e4-8f8c-9a11fcdb2ec7.png)
![genesis plus](https://cloud.githubusercontent.com/assets/5182602/5789165/b54e325e-9e2d-11e4-81a0-214de1296cb0.png)

**Comment by clobber** [comment]
OpenEmu doesn't use Genesis Plus. We use GenesisPlus-GX (https://code.google.com/p/genplus-gx/) which is a lot different from a stone age Bannister port. Not the same.

**Comment by LordHDL** [comment]
You misunderstand.  The old Bannister port has correct colors.  The last image is just to show as such.

OpenEmu's implementation (I know it's GX) is inaccurate, as would be apparent if you tried the color meter.

**Comment by clobber** [comment]
Slight difference in color values between two different emulators and you know an old Bannister port has 'correct' colors because how?

**Comment by LordHDL** [comment]
3 different emulators, just didn't bother lengthening the post.

In any case my approach with Digital Color Meter is probably off considering the nature of emulation, so I decided to ask someone who is extremely intimate with the Genesis hardware and this is what he told me:

"This one is a contentious issue
There is a thread on SpritesMinds that has voltage measurements of the output signals of the VDP for R, G, B, and some newer emulators are basing the color information on that
(based on the assumption that the white color specified on the palette (0xEEE) is white on RGB as well (0xFFFFFF))
Some emulators base the colors on other things
For example, they just take the Genesis internal color (say, 0xEEE) and either stuff it with zeroes (to form 0xE0E0E0) or repeat the nibbles (to form 0xEEEEEE)
But there are other ethods used as well
All told, the one most likely to be correct is the one based on voltage measurements
In this case, Gens/GS would be the one with the most accurate colors"

Here's are screen shots of Gens/GS:

![gens gs 1](https://cloud.githubusercontent.com/assets/5182602/5792775/82762dee-9ef7-11e4-9bdc-64592600fbce.png)
![gens gs 2](https://cloud.githubusercontent.com/assets/5182602/5792776/82854e78-9ef7-11e4-8b8f-bf6da35a7835.png)

And I can't tell if you missed it or not, but you can compare color values with Digital Color Meter, which is a default app in the Utilities folder.

**Comment by astrange** [comment]
If there's an issue with the bitmap coming out of the emulator OpenEmu isn't responsible for it. (like that would be)

However if we're right and the original emulator is wrong, obviously they'd be different. That could happen if we're color-correcting the original sRGB image to your display profile. I feel sure the original emulator does not do that, but can't remember if OE ever implemented that.

**Comment by astrange** [comment]
If there's a screenshot key in the original, try comparing that with OE's screenshots.

**Comment by LordHDL** [comment]
How would I get an OS X build of the original GX to compare?  All I can find are guides for building Wii/GC binaries.

**Comment by ekeeke** [comment]
Don't bother. You are comparing screenshots from emulators and arbitrarely stating one is less accurate than another just because RGB values are not exactly the same, which does not make much sense.

There are differences because they use different methods to map the original 3-bit digital color channel value to PC digital 8-bit value but none of them are 100% accurate anyway. There is no hardware-perfect pixel color value and it makes no sense looking for one because original hardware video out goes through DAC, various analog steps, different video encoders, etc, which are impossible to perfectly emulate because it's ... well, analog, not digital.

Now, for the record:
- original Genesis Plus would simply put zeroes in the low bits so white would be 224,224,224
- Genesis Plus GX treats 3-bit value as 4-bit (with lsb set to zero except in shadow/higlight mode) and duplicates this 4-bit value to get 8-bit value so white is 238,238,238 

The second method indeed results in slightly brighter colors but the difference is barely visible on your screenshots. And it is actually more "accurate" to the voltage measures I made in the topic you linked so saying old bannister's port is more accurate is kinda wrong on that regard. 

About using the exact measured values and convert them to 8-bit values, there is actually no guarantee that this method is more "accurate", just that it tries to emulate an imperfect DAC by making unverified assumptions about voltage reference. What really matters is how the output colors compare to the original screen colors, not voltages or arbitrary pixel value references from other emulators, and honestly I can tell you it does not make enough (if any) visible differences to be worth the shot. You will probaly only see the differences when using an image analysing tool like you did or, as a lot of people obsessed with "perfection", once you know tiny differences exist because some software told you.
