### ISSUE TITLE
I can not run neogeo games

### ISSUE THREAD

**Issue by mauricioargj** [OpenEmu/OpenEmu#1792]
Hello. I compiled the source, put the neogeo.zip in the Arcade of the library, but I still can not run any neogeo game. Can anyone help me?

Thank U

**Comment by clobber** [comment]
Please run a search first before opening an issue like this since it has been covered before.

For our MAME core you need roms (zips) from a **MAME 0.149 romset**. Sometimes the games require additional system or bios zips (parent roms) so check console.app for output and it will usually specify names of zips that are also required.
