### ISSUE TITLE
TG16 Resolution/Aspect Ratio Issues

### ISSUE THREAD

**Issue by Emuthusiast** [OpenEmu/OpenEmu#1797]
First of all, this issue is not present in mednafen version 0.9.34, I went and downloaded the old version just in case you guys just needed to update the core.

For some reason, a bunch of TG16/PCE games aspect ratios are all screwey, and in games where there's any kind of resolution switching stuff just falls off the edge of the screen. I've uploaded an example. I don't know what the cause of this is but I hope someone smarter than me can figure it out :-D Thanks a ton for creating an awesome multisystem frontend, and I hope in a small way this helps it be more awesome.

EDIT: Yeah I know the screenshot says "Ration," stupid autocorrect....

![screen shot 2015-01-27 at 5 28 06 pm](https://cloud.githubusercontent.com/assets/10732381/5928615/8acf1b5e-a64a-11e4-93a7-485130729c54.png)

**Comment by clobber** [comment]
> a bunch of TG16/PCE games aspect ratios are all screwey

Got an example and which version of our OE Mednafen core port?

> Your screenshot, Order of the Griffon mid-scanline resolution change.

Known issue. I have a patch for this that i'll probably include in our next release we push out for the Mednafen core.

**Comment by Emuthusiast** [comment]
The OE Mednafen core port is 0.9.34.1. I'll post several more examples later(don't have time now) if you think it would help, but even above the midscanline resolution change you'll notice the aspect is correct in mednafen and off in OE(you can see the little two-headed arrow I put to show the discrepancy between widths). It seems to be a PAR issue of some kind, something to do with scaling? I've put together a very quick OotG comparison again, and like I said I'd be happy to offer more if this isn't helpful. Thanks for your time!

![ermahgerdmerdnerfern](https://cloud.githubusercontent.com/assets/10732381/5930093/ea8dc5e6-a658-11e4-8ba6-29ab502f8cd8.png)

**Comment by clobber** [comment]
Well first of all we already know this game, Order of the Griffon, is a problem.

You need to be playing games using the 'popout gameplay window' (see OpenEmu > library prefs) and then you can get proper integral 1x, 2x, 3x, etc scaling. Playing games in the main window does not preserve aspect ratio because the view conforms to the stretching and scaling of that window.

Also, using the "Pixellate" shader (our default) will help keep pixels uniform. Closing this issue since these are likely the cases, but feel free to reply.

**Comment by Emuthusiast** [comment]
Hi! Sorry to continue to be a bother, but after using the Pixellate shader, "Always use popout gameplay window," and trying a couple other games the overall "squat" feeling still pervades TG16 titles in OE. I've included a non-OotG example, here: 
![bonksquashed](https://cloud.githubusercontent.com/assets/10732381/6035827/d94f4786-ac08-11e4-8718-3a25bfa528a3.png)

Like most folks that use emulators, this is a nostalgia thing for me— it just "feels" off. I totally understand if that's not something you folks would have as a priority. But the short version is, every game I open that I owned as a kid feels squished/squat/stretched— Order of the Griffon, Cadash, the Bonks, Air Zonk, Keith Courage, so on. Anyway, if it's an easy fix rad, if not ignore me. Thanks again for your time and for an awesome emulator.

**Comment by clobber** [comment]
Comparing this stuff isn't really apples to apples, because even Mednafen has its own various scaling options and it looks like you have the Pixellate shader active in OE. But, what you're seeing with OpenEmu is an 8:7 image (PCE/TG16 internal aspect ratio) corrected to fit 4:3 aspect ratio which is what we do for all console systems and also what you would have seen on your real television - minus the scanlines, phosphors and other NTSC artifacts. We believe this to be the correct behavior since even Nintendo does this for its virtual console games originally designed with 4:3 in mind. Perhaps it "feels" off to you since you've played your majority of these games on emulators only outputting square pixels.

Semi-related article on fitting aspect ratios and resolutions: http://blog.hardcoregaming101.net/2012/03/explaining-resolution-intro-of.html

**Comment by Emuthusiast** [comment]
Thank you again for continuing to reply. I have an actual TG16, which I got for Christmas when I was 8, and that's how I've played and remember these games. In fact the lack of real turbo function is something I sorely miss(and remember fondly, the clicking of those little switches, without which the bonk games are basically unplayable) but I'm happy to let this go. There are so many variables here - the TV I grew up with, the scaling on my HDTV(what I've used most recently to play the actual TG16 and found much more confusing than OE) and the Wii VC releases you mentioned, which I also played on the HDTV but with component cables etc. this is probably just rose tinted glasses talking, especially since the CRT filter feels closest to my memory and it lacks the artifacts you mentioned. I'll stop bugging you guys now.

That said thank you for the link and your continued efforts to assist and educate.

**Comment by clobber** [comment]
@Emuthusiast you were right about something looking wrong with Bonk. The pixel aspect ratio (PAR) was not being corrected properly.

On a 4:3 CRT TV, the majority of these older systems (NES, SNES, TG16, SMS, GEN) all have a PAR of 8:7 (~1.14) which has to do with the pixel rate of their video signal generator chips and scanline length. So, to make these games appear how they would on TV, one cannot simply stretch the screen (display aspect ratio) to 4:3 but instead must adjust the outputted width times the PAR:

E.g. 256px width x 240px height game: `256 * (8/7) = 292 x 240`

More details if you are interested:
* https://pineight.com/mw/index.php?title=Dot_clock_rates
* http://wiki.nesdev.com/w/index.php/Overscan

Fixed in https://github.com/OpenEmu/Mednafen-Core/commit/6475277d7c3ac41d05c796c8ccf408fe20b62504

**Comment by Emuthusiast** [comment]
Wow! Thank you, that's very validating. Like I said, almost none of my TG16
games looked quite right, but it was a gut feeling more than anything else.
I'm familiar with PAR/overscan issues related to freelance video production
in the pre-HD era, so this is extra cool to hear about. Thank you for your
time and your attention to detail.

Now if only we had emulation for the Turbo Buttons above buttons I & II I
could abandon any other TG16 emulators!

On Sun, Jul 19, 2015 at 8:01 PM, clobber <notifications@github.com> wrote:

> @Emuthusiast <https://github.com/Emuthusiast> you were right about
> something looking wrong with Bonk. The pixel aspect ratio (PAR) was not
> being corrected properly.
>
> On a 4:3 CRT TV, the majority of these older systems (NES, SNES, TG16,
> SMS, GEN) all have a PAR of 8:7 (~1.14) which has to do with the pixel rate
> of their video signal generator chips and scanline length. So, to make
> these games appear how they would on TV, one cannot simply stretch the
> screen (display aspect ratio) to 4:3 but instead must adjust the outputted
> width times the PAR:
>
> E.g. 256px width x 240px height game: 256 * (8/7) = 292 x 240
>
> More details if you are interested:
>
>    - https://pineight.com/mw/index.php?title=Dot_clock_rates
>    - http://wiki.nesdev.com/w/index.php/Overscan
>
> Fixed in OpenEmu/Mednafen-Core@6475277
> <https://github.com/OpenEmu/Mednafen-Core/commit/6475277d7c3ac41d05c796c8ccf408fe20b62504>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenEmu/OpenEmu/issues/1797#issuecomment-122719728>.
>



-- 
*Colin W. Felt*
Lover, Liar and Wordsmith

**Comment by clobber** [comment]
Order of the Griffon issue fixed in https://github.com/OpenEmu/Mednafen-Core/commit/18a33dc8abe05ab697ab5ff2e1a366c9da00e9fd, available in the Mednafen 0.9.46 core plugin.
