### ISSUE TITLE
4DO Super Wing Commander no controls

### ISSUE THREAD

**Issue by darklord42** [OpenEmu/OpenEmu#1800]
I did a bit of digging to figure out why the controls wasn't working with this game.  According to this, if all 6 controllers are being emulated the controls won't work.  And binding controls for 6 controllers will cause it to not work again.

http://wiki.fourdo.com/index.php?title=Compatibility_List#Super_Wing_Commander

Is there any reason this fix could have been reverted when the emulator was made a plug-in for OpenEmu?

Aside from that, I have no ideas

**Comment by clobber** [comment]
They have a frontend or perhaps implementation hack to work around it but nothing was ever patched to the emulator core (FreeDO/libfreedo) itself, so no fix could have ever been brought along in our port or reverted. We don't have a way to report from our frontend to the core as to how many virtual players actually have active bindings.

What you can do is change the size of this array here to 1 or 2 and that will fix it, after recompiling https://github.com/OpenEmu/4DO-Core/blob/master/FreeDOGameCore.mm#L59

Since the 3DO could daisy-chain up to 8 controllers, we should actually learn how many games even support that many players or what is the max # of multiple players of a 3DO game, then adjust that input array accordingly - I bet there aren't any that even support 6. I noticed right now we only have 1 virtual controller exposed via the frontend anyway.

If you have any idea about the max players, let me know. Closing this for now but feel free to comment.

**Comment by darklord42** [comment]
Well max players for SWC is just 1 player.  I'll give the array thing a try.

**Comment by clobber** [comment]
Yeah I know that its 1 max for this game. I'd like to know if there are any 3DO games that support 4 or 5 or 6 or more players. My guess is there aren't any supporting 6 but I don't know for sure.

**Comment by darklord42** [comment]
I suppose you can make a 5 max and see if anyone ever complains :) If possible I think a better solution would be just to make some exception for SWC.  I think it's the only one mentioned on that site that has this issue.  Aren't such exceptions fixes made specifically for other games?

**Comment by darklord42** [comment]
Dang, I tried changing 4DO/FreeDOGameCore.mm line #59
inputState internal_input_state[6];
to 
inputState internal_input_state[2];
But no luck. Still no response of controls.  Is there something else that needs to be changed? Or is this whole assumption wrong?

**Comment by clobber** [comment]
@darklord42 It works. Change the value to 1 (or anything below 6), recompile the core and make sure it ends up in your Cores folder. That's it.

**Comment by darklord42** [comment]
Thanks for testing it out.  Strange, I believe you, and am very glad that the solution is possible.  I did it again thinking that maybe I should have cleaned everything out and make sure the slate is clean. But still no luck.

**Comment by darklord42** [comment]
Might I request that this remain open?  Although we know the cause and can be fixed, It hasn't actually been implemented in the software yet, and I imagine probably will take a little bit before anyone actually gets around to it.
