### ISSUE TITLE
MAME and NEOGEO issues

### ISSUE THREAD

**Issue by johnnyblair** [OpenEmu/OpenEmu#1807]
Can someone please help me out and tell me whats wrong?  I have OpenEmu 1.0.4 installed and for the life of me cannot get a single MAME rom or Neo Geo rom working.  All of my MAME rooms have come from Mame 0.149 and not a single one will launch and no cover art is being found either.  I also have taken the neogeo.zip bios file and dragged it into OpenEmu which I think is the correct way but still cannot figure out why I keep getting this error.  All of the other systems NEW, Sega, etc work just fine.
![error2](https://cloud.githubusercontent.com/assets/8002204/6043042/90953e70-ac57-11e4-8073-13cd431aa415.jpg)

**Comment by AnalogSurfer** [comment]
See https://github.com/OpenEmu/OpenEmu/issues/930 for possible reasons you're experiencing the error and how to check the Console. MAME is very pissy and particular about naming and each game needs to be in .zip format. Probably should be looking in the Console on your computer if you want to know what is causing the errors for sure though.

For Neo Geo: right-click in OpenEmu and delete whatever neogeo.zip you have installed and trash the file when prompted. Then perform a search for "NeoGeo Bios [Full] [30-04-13]" and download - drag/install that .zip file to OpenEmu as it's the most complete one I know of (making sure it's not renamed to neogeo (2).zip or whatever if you have one in the download folder already). 

I use MAME 0.155 ROMs for Arcade/Neo Geo games and they run perfectly. Most of the Neo Geo ROMS I play on my Windows machine with Nebula don't work with OpenEmu/MAME setup. This is because there are multiple ways that Neo Geo ROMs are packaged for different emulators and many of them lack one or more necessary files or contain files in the wrong format for using with MAME. In other words, my complete collection of Neo Geo ROMs is somewhat worthless with OpenEmu and if you're having the same issue then find MAME ROM alternatives. Cover art can be manually added later if you really want it, but really it's just icing on the cake.

**Comment by darklord42** [comment]
The trick with mame is to go to Applications/Utilities/Console.app and then try to launch your game.  You will get an error explaining which files you need to get it running.  Most Mame sites I run across are not complete in their files for individual games.  You get a lot of update packages which don't include files for the base game.  It takes a lot of work with the google toolbar. but it's worth it.

**Comment by digamejh** [comment]
In my experiences, secondary files necessary for certain MAME games to run (like qsound.zip or atarisys1.zip) are ok simply being in the same folder as the game ROM (zip file) itself.  If you set OpenEmu to copy games into its own directory upon import, then do so, otherwise they're ok just being in the same folder on your hard drive.
BUT... NeoGeo games are the exception, and are apparently not supported yet no matter what I try.

**Comment by clobber** [comment]
For our MAME core you need roms (zips) from a MAME 0.149 romset. This includes neogeo.zip as well. If the games don't run with both the game and neogeo.zip, then you don't actually have the correct files from a 0.149 set. Delete the ones you have, find the correct ones and reimport them.

This is all the help we can offer right now until we've made some changes to how MAME outputs errors to the frontend.

This issue has also been discussed several times so please search the issues next time for help.

**Comment by pawelkrupinski** [comment]
On Mac, start OpenEmu, go to "Arcade" section right-click on any rom there, click "Show in Finder". Copy qsound.zip to the same location.
