### ISSUE TITLE
Genesis scale off integer (popout)

### ISSUE THREAD

**Issue by LordHDL** [OpenEmu/OpenEmu#1832]
This happens at any window size.  Here is the window scale when loading a Genesis game:

![sonic 3 knuckles 2015-02-18 11 49 56](https://cloud.githubusercontent.com/assets/5182602/6251933/cb6bca4c-b764-11e4-84c6-42dc88624397.png)

Here is the corrected scale if you manually select the current scale setting after loading:
![sonic 3 knuckles 2015-02-18 11 50 31](https://cloud.githubusercontent.com/assets/5182602/6251952/e0e01950-b764-11e4-9e5f-5bae9784bd4d.png)

This doesn't happen for the other cores I've tried (7).

**Comment by clobber** [comment]
The resolution is changing during boot up. We get the the resolution from screenRect and make our changes to the popout window probably from the first frame or so. We can't really add a delay to read more frames because then that will delay the window and when video will appear. Closing for now at least.

**Comment by astrange** [comment]
Maybe it could freely resize the window in the first few seconds? Or the core could lie about the initial screen size.
