### ISSUE TITLE
Arcade game cover art

### ISSUE THREAD

**Issue by johnnyblair** [OpenEmu/OpenEmu#1834]
I just want to know if arcade games pull cover art like the cartridge systems do.  I have tried many ROM files from the MAME .149 set as well as other arcade ROMS but none pull any cover art.  Is this a limitation?

I have hundreds and would have to have to do this manually. 

Thanks

**Comment by clobber** [comment]
Currently unsupported for arcade.

**Comment by jduraes** [comment]
Still unsupported 3 years later?

**Comment by clobber** [comment]
There is a referenced issue from 6 months ago. Also,

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](http://choccyhobnob.com/articles/demystifying-mame-roms/)."
