### ISSUE TITLE
Wii U Pro Controller and Remotes Not Appearing When Trying To Sync Or Even When Synced  

### ISSUE THREAD

**Issue by beviordo** [OpenEmu/OpenEmu#1837]
Was working perfectly fine before but now i can't even sync the controllers. Only keyboard appears on controller configure Screen even after the controller vibrates to say that open emu has picked it up nothing appears on  configure screen

**Comment by beviordo** [comment]
tried previous versions of open emu appears to be a issue with the experimental versions as it finds and displays the wii u pro controller on the non experimental version

experimental finds the wii u pro controller but does not display or show it on the input screen so i can't select it

could someone address this problem as the experimental version is better with more emulators

**Comment by clobber** [comment]
Wii U Pro seems to work for everybody else. There is no different between the standard build and 'experimental' build of OpenEmu; exactly the same code. 'Experimental' just has additional system and core plugins available. I suggest completely removing your control device in Bluetooth Preferences on OSX and start over using this guide to pair: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing

Closing because this is an issue on your end.
