### ISSUE TITLE
Glow in filters

### ISSUE THREAD

**Issue by superrune** [OpenEmu/OpenEmu#1871]
Hi,

Excuse me if I'm posting this the wrong place, I'm new to GitHub and these forums.

I have been playing around with OpenEmu the past days, trying to find a video filter that makes my games look nice. Although they all look pretty nice, I think a couple of things are missing before they're ideal. Are the filters delivered as part og MAME and the other emulators, or do you have control of that code yourself?

Do the filters do filtering with the correct gamma applied internally? I see a couple of them make the game very dark, which could be a gamma issue: http://www.4p8.com/eric.brasseur/gamma.html

Also, the filters that are closest in my eyes (beam4, CRT and the NTSC filters) are all missing glow. CRT screens have a visible glow effect that softened (and brightened) the image. I would love to see that simulated too!

Great work on the application, I love how easy it is to use! Cheers!

**Comment by mrvacbob** [comment]
The filters are written in the Cg language, so you could edit them yourself as long as they're not in bytecode. In the future, we'll switch back to GLSL since Nvidia no longer supports Cg.

Unfortunately they are not properly color corrected; I tried using proper sRGB textures a while ago but couldn't get it to work for some reason. Although this is wrong, AFAIK the errors should be more visible downscaling than upscaling, so it's not too bad.

They might have left out glowing since it'd be another few rendering passes? (basically you add the gaussian-blurred image to itself)

**Comment by superrune** [comment]
Thanks for the quick answer! Glowing would do a lot to create that beautiful retro look. I only do very very basic scripting, but I will look at the Cg source some day I feel brave enough :)

This emulator does some pretty comprehensive (too much imho) screen simulation, and bloom/glow is one of the features it has: http://micro64.de

**Comment by clobber** [comment]
Search this repo for glow or bloom; plenty there https://github.com/libretro/common-shaders

Closing ticket cause general question. Feel free to reply though.

**Comment by superrune** [comment]
The CRT Royale shader inside the commons-shaders repo looks really amazing. Would love to see that in openEmu - if possible of course!

**Comment by mrvacbob** [comment]
If it's a .cgp file, I think you can drop it into Application Support/OpenEmu/ somewhere and it'll get picked up.
