### ISSUE TITLE
Fast Forward Button

### ISSUE THREAD

**Issue by ArmyBox1** [OpenEmu/OpenEmu#1874]
I am having a lot of problems with the speed button. When I press the key, the game with surge in and out of FF/Turbo mode. It makes it mush harder to play, especially when I need to fast forward through things.

**Comment by clobber** [comment]
@ArmyBox1 First of all, it's unnecessary to post in closed/resolved issues since you've opened your own. Also expecting people to personally email you with help is unreasonable; that's what discussion in these issues are for.

Anyway if I understand correctly, you need to press *and* hold the button you've set for "fast forward" in order for it to fast forward.

**Comment by ArmyBox1** [comment]
I do hold it. It keeps surging. And i'm sorry about the whole posting thing. I didn't think it'd actually be an issue, but sometimes it takes weeks for people to see posts on other forums.

**Comment by kylewlacy** [comment]
What systems and cores have you tested fast forwarding with? I think the issue *might* be that your hardware is too slow to constantly run a particular emulator core at 5x speed. Could you test fast forwarding with a NES game, and compare it to fast forwarding with an N64 game?

If possible, could you also provide a screen recording of the issue? If you open QuickTime, you can make a screen recording by going to "File > New Screen Recording", clicking the record button, and dragging a square over the OpenEmu window. This would make it much easier to figure out the issue.

**Comment by ArmyBox1** [comment]
I have been trying to work on GBA. As for the core, it's Visual Boy Advanced. I've switched through all of the filters and back to Nearest Neighbor (the original) I bet it's just my computer. Meh, I'll be back home where I have a much better computer to work with in a few days. Thanks for the help anyway.

**Comment by ArmyBox1** [comment]
Is there any way to change the FF speed, like maybe from 5x to 4x/3x. My computer might handle that better.

**Comment by clobber** [comment]
Sorry, no. Not likely to add an option for that either. But we shouldn't assume that is the issue since there could be something else going on - possibly video. I can tell you fast forwarding for VBA on an old Core2Duo CPU uses 90%-to-high-90's and is not 'surging'. You should post your machine specs including your GPU.

**Comment by ArmyBox1** [comment]
Processor  1.7 GHz Intel Core i5
Memory  4 GB 1333 MHz DDR3
Graphics  Intel HD Graphics 3000 384 MB
It's just a stock Mid 2013 Macbook Air

**Comment by clobber** [comment]
Your CPU is fast enough and your GPU shouldn't be having any issues with GL or most filters/shaders. Try just using Pixellate or Nearest Neighbor as your filter. Others with these same machine specs aren't having this issue.

**Comment by ArmyBox1** [comment]
I'm Using Nearest Neighbor, but should I restart the system when I switch to Pixellate?

**Comment by ArmyBox1** [comment]
I switched to Pixellate (without restarting, if it matters) and the problem didn't change at all.

**Comment by clobber** [comment]
Did you compile OpenEmu on your own or download it from a different website besides openemu.org? Can you also verify you are in fact running GBA games with VisualBoyAdvance and not Higan (check in the cog menu on the HUD bar, "Select Core")? What is the version of VisualBoyAdvance in OpenEmu > Preferences > Cores ?

**Comment by ArmyBox1** [comment]
I know for absolutely sure that I am using Visual Boy Advanced and not Higan. I was going to switch to see if it changed, but I was too lazy (vacation, dude). As for where I got it, I got it from coolrom.com. If I need to redownload it, then will my quick saves stop? Because I had a huge problem with that.

**Comment by ArmyBox1** [comment]
I went ahead and redownloaded the app from the openemu site, but nothing changed. Probably because I kept the Application Support folder from fear of losing my files.

**Comment by ron-wolf** [comment]
You can move them to the Trash without fear of losing them. If you need to you can always open the Trash, right-click on the files you need, and select “Put Back”. Alternatively, you can rename them something slightly different—for example, by adding a tilde~ at the beginning—and then undo the name change later on. (This is especially useful because you can keep both the old version and the new version in the same folder without OS X complaining about them having the same name.)

**Comment by clobber** [comment]
The original problem seems to be an issue on your machine for whatever reason.
