### ISSUE TITLE
Fire Emblem 6: Sword of Seals - Chapter 11 Error

### ISSUE THREAD

**Issue by npd200** [OpenEmu/OpenEmu#1890]
I completed chapter 11 in FE6 and as I capture the boss castle with Roy, the game freezes. I have restarted OpenEmu several times and tried different save points. Help!

**Comment by clobber** [comment]
Probably a regression or bug in the fork of VBA that is currently available over the downloader.

If you upload your save file to somewhere such as transfer.sh and tell me exactly how to reproduce the freeze, I can take a look if its still happening in an updated-but-not-yet-released version of our VBA core port.

**Comment by npd200** [comment]
how exactly do i upload the file?

**Comment by npd200** [comment]
Here's the URL.

https://transfer.sh/jsaiL/save-game-4-2015-04-06-210316-0000.oesavestate.zip

**Comment by npd200** [comment]
All you have to do is take the main character in the top right corner, move him onto the "gate" tile right in front of him, and select "Conquer."

**Comment by clobber** [comment]
You should have told me you were using a translation patched version of the game since there very well could be a bug from that patch. Anyway, I tracked down that patched version and tested it with recent VBA. The game no longer crashes but it appears to cause another problem where controls no longer respond. This is either a bug with the translation patch or with VBA itself. I suggest first testing with the unpatched version of the game at the same point and see if the problem persists and also determine if a newer patch is available. 

Anyway, here is an updated version of the VBA core port you can use that won't crash at least:

https://transfer.sh/gYGoF/visualboyadvance-1.8.0.1231.zip

Download, unzip and place the .oecoreplugin file in ~/Library/Application Support/OpenEmu/Cores (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)

**Comment by npd200** [comment]
I replaced the core, but I don't know how to transfer the savestate to the
original Japanese rom. The rom I'm using is pre-patched, but I also
downloaded the original rom. How do I transfer the file, if it's even
possible?

On Tue, Apr 7, 2015 at 12:24 AM, clobber <notifications@github.com> wrote:

> You should have told me you were using a translation patched version of
> the game since there very well could be a bug from that patch. Anyway, I
> tracked down that patched version and tested it with recent VBA. The game
> no longer crashes but it appears to cause another problem where controls no
> longer respond. This is either a bug with the translation patch or with VBA
> itself. I suggest first testing with the unpatched version of the game at
> the same point and see if the problem persists and also determine if a
> newer patch is available.
>
> Anyway, here is an updated version of the VBA core port you can use that
> won't crash at least:
>
> https://transfer.sh/gYGoF/visualboyadvance-1.8.0.1231.zip
>
> Download, unzip and place the .oecoreplugin file in ~/Library/Application
> Support/OpenEmu/Cores (~ meaning your Home folder where ~ is your username.
> Guide here if you don't know this:
> http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenEmu/OpenEmu/issues/1890#issuecomment-90354417>.
>



-- 
- Nick Davini

**Comment by clobber** [comment]
@npd200 No need to open another ticket. This isn't a priority issue or even a problem with OpenEmu, but a problem with your ROM hack. You should first see if there is an updated version by the author who created it. They may have a forum somewhere.

**Comment by kylewlacy** [comment]
In some cases, it kind of is possible to transfer saves (by opening the `.oesavestate` bundle and moving the `State` file), but in many cases, emulators check to see that a state file matches the loaded ROM, by using a checksum. VisualBoyAdvanced does this, so there really isn't any way to move a save state from one ROM to another. Most other emulators do this as well, so it isn't really practical for OpenEmu to handle transferring saves.
