### ISSUE TITLE
Sounds Cracks and Pops

### ISSUE THREAD

**Issue by inhalexhale** [OpenEmu/OpenEmu#1891]
I'm experiencing cracks and pops in the audio, when playing SNES games. Specifically Chrono Trigger and Mario RPG. CT seems to have the issue much more. I tried different ROMs, from different sources, but the issue persists. What could be the problem? The cracks/pops aren't extremely loud, but noticeable.

**Comment by clobber** [comment]
Need to know:
* Which version of OSX?
* Which Mac are you using and what is your display? Are you using an external display? (third party monitor or TV? or are you using the built-in display of a macbook or imac?)
* What is your GPU? Listed under "Graphics" in Apple menu -> About This Mac -> More Info -> Overview
* What version of OpenEmu do you have?
* Which SNES core are you using (SNES9x or Higan) and which versions are listed in OpenEmu -> Preferences -> Cores (and were there updates available in that menu?)

**Comment by inhalexhale** [comment]
- 10.10.2
- 2012 iMac
- GTX 680mx
- OpenEmu 1.0.4 (Using experimental at the moment, but this issue also occurred under the standard version)
- SNES9x; 1.53.3 (switching to Higan, which I tried, freezes the emulator)

I don't see anything to update in the Cores screen.

**Comment by clobber** [comment]
I forgot to also ask you which filter you are using and to try with both Nearest Neighbor and Pixellate.

The core switching freeze has been fixed in source; for now you can work around the problem by simply pausing emulation first (the pause button on the HUD bar) and then switch to Higan to see if that changes anything. Your save file from SNES9x is not shared with Higan so you can either copy that over in app support or start new.

Also try with this version of OpenEmu to see if it makes a difference:

https://transfer.sh/fLiFc/openemu-1.0.4-experimental-no-clientstorage.zip

Btw - both the standard build and 'experimental' are exactly the same code. Experimental only includes additional 'experimental' system plugins which gives you access to the 'experimental' cores.

**Comment by clobber** [comment]
Didn't hear back from you but I fixed what appeared to be another problem. For now use Higan for SNES or wait until next OpenEmu release.

https://github.com/OpenEmu/SNES9x-Core/commit/fc9b31c9a9b9c07abb4336ddc0ad64c2d2a453ce

**Comment by inhalexhale** [comment]
Hey,

I didn’t have time to retest. New baby and finals at school. No time for old school gaming! I’ll check out Higan and report back. Thanks.
