### ISSUE TITLE
suitable core

### ISSUE THREAD

**Issue by grande123** [OpenEmu/OpenEmu#1905]
I get an error message when trying to play games. 
The operation couldn’t be completed. OpenEmu could not find a Core to launch the game.
Make sure your internet connection is active and download a suitable core.

I am trying to play a game on sony playstation.
I have internet connection and there is a sony playstation tab.
Please help!

**Comment by clobber** [comment]
Sounds like you have a weird broken setup, maybe because you installed OE in a non standard way or got it from anywhere besides our website?

* Delete the "Cores" and "Systems" folder (if it exists) in ~/Library/Application Support/OpenEmu (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
* Run the following command in Terminal.app: `defaults delete org.openemu.OpenEmu`
* Download OpenEmu 1.0.4 experimental cores build from https://github.com/OpenEmu/OpenEmu/releases/download/v1.0.4/OpenEmu_1.0.4-experimental.zip
* Run the app and let all the cores download through setup assistant.

Assuming you have all the correct BIOS files required (https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files), it should now work.

**Comment by clobber** [comment]
Oh, and if they won't download during setup then you will need to follow these guides:

http://superuser.com/questions/605900/why-wont-os-x-trust-githubs-ssl-certificate
https://blog.digicert.com/expired-intermediate-certificate/

**Comment by grande123** [comment]
I don't know how to run the command in the terminal.app. can you run me through that?

**Comment by grande123** [comment]
also, how do i download the correct BIOS files?

**Comment by clobber** [comment]
@grande123 - few things:

* You don't need to open up a new ticket.
* Follow my actual directions :)
* Here's a guide for Terminal http://mac.appstorm.net/how-to/utilities-how-to/how-to-use-terminal-the-basics/
* I cannot help you download these files, sorry.

If none of this works, then there is nothing we can do for you. You're on your own and this might be too difficult for you.

**Comment by pacav69** [comment]
the https://blog.digicert.com/expired-intermediate-certificate/ solved my problem by removing the expired certificate i was able to download the core files.
