### ISSUE TITLE
yosemite 10.10, experimental 1.04, playstation not playing

### ISSUE THREAD

**Issue by ngude** [OpenEmu/OpenEmu#1952]
i dragged and dropped scph5500,01,02.bin into open emu and watched as they went to the correct BIOS folder, but attempting to launch any psx games results in nothing. no black screen, just nothing.

any ideas? even though the bios files were taken via drag+drop without error by openemu, i doublechecked their md5 and everything matches up.

this behavior is consistent no matter what playstation games i try to open

**Comment by clobber** [comment]
Nothing launching means it cannot load the game, so you have a bad cue+bin set up. Check what was imported for your game and make sure it is correct. See here: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cue-sheets-%E2%80%94%C2%A0loading-CD-based-games

This is all the help we can offer until the guide is rewritten for next version to handle more CD-importing issues.

**Comment by ngude** [comment]
both bin and cue were imported. cue file points to the correct bin file. this happens with 3 images so far. any other ideas?

btw, i used all your very helpful guides to set up the cue files as well.

**Comment by ngude** [comment]
all other consoles work great for me. appreciate your hard work! looking forward to the next version :)

**Comment by clobber** [comment]
Okay, run find -s ~/Library/Application\ Support/OpenEmu/BIOS -type f -exec md5 '{}' \; in Terminal and paste the results back here.

I also need to know which game you're trying to load and what the cuesheet and files look like. So in "~/Library/Application Support/OpenEmu/Game Library/roms/Sony PlayStation" copy and paste the names of all the files for the game (.bin, .cue, anything else) and also open up the .cue file in TextEdit for the game in question and paste its contents back here.

Finally, open up Console.app and look for the output or crash logs that should be there for "OpenEmu" and "OpenEmuHelperApp" and open that up and paste its contents in gist.github.com and link that back here too.

**Comment by ngude** [comment]
you're not going to believe this. 

total noob move on my part. i had file extensions hidden and was attempting to rename an IMG as BIN. 

works now as all the files have correct extensions!

i am however still getting that 'nvidia 320m' problem where audio/gameplay briefly stutters every few seconds. happens on most games that use predominantly 2d graphics. currently tested on mother 3 (gba --both cores), paper mario, castlevania X (psx), any snes games (both cores)

filter: nearest neighbor or linear or pixellate

seems this may have been related to the 'slow client storage'. you had a test build up 'openemu-1.0.4-no-clientstorage.zip'

did this have any effect?

**Comment by clobber** [comment]
> total noob move on my part. i had file extensions hidden and was attempting to rename an IMG as BIN. 

Yep, I've made a note to update the guide with regard to renaming files (and supported file types) so others won't make that same mistake, but usually there should not be a reason to rename files. If your cuesheet already points to a .IMG and your included binary is .IMG, it will import and load just fine. Currently, the guide makes it seem like only a .BIN can be imported, but that is not the case. Hence the need to rewrite the guide for next release.

> i am however still getting that 'nvidia 320m' problem where audio/gameplay briefly stutters every few seconds.

Yeah, this has been fixed and will be included in our next release. It affects other GPU's besides the 320M, but if you do have that GPU then the problem is fixed. I've uploaded a build with the patch applied here: https://transfer.sh/EFaH2/openemu-1.0.4-experimental-no-clientstorage.zip

As an aside, I don't understand why that person with the video didn't simply open up a ticket instead of posting a youtube video; it's not like we go searching youtube for these things. Doesn't make a lot of sense, anyway...

**Comment by Truesyndo** [comment]
Hey wasup Clobber, why did you close the other thread after i asked if you could reupload the no clientstorage file? Ive been using openemu for awhile now and I love the program but I cant enjoy the games at all, Id really like to keep using this program but the lag is a big problem and im not the only one having it.

**Comment by ronnyhartenstein** [comment]
I found the correct bins (MD5 check), but currently it won't import on drop on the mediathek. But I created ~/Library/Application\ Support/OpenEmu/BIOS and put it there manually and it worked! (green marks in Settings -> BIOS).
