### ISSUE TITLE
Missing OEPrefControlsController.xib on pt and es locale

### ISSUE THREAD

**Issue by mathmarques** [OpenEmu/OpenEmu#1963]
After compile the experimental build, I notice that Controller Preferences was crashing OpenEmu. 

I found (with @torque help) whats was generating the crash was the missing of OEPrefControlsController.xib pt.lproj

**Comment by clobber** [comment]
Thanks for reporting. It looks like the ES translation is also missing it. We can just add these files in since barely anything in that xib needs to be localized. Temp workaround is to add that file to your project or change your machine's locale to english.

Note to us devs: we need to check all translations for any other missing files
![screen shot 2015-07-02 at 3 34 43 pm](https://cloud.githubusercontent.com/assets/1303132/8492027/74c6f59a-2109-11e5-914d-ca12e055143c.png)

**Comment by mathmarques** [comment]
np.
I just copy the xib from EN and worked just fine.
