### ISSUE TITLE
007 Multiplayer not running smoothly -N64

### ISSUE THREAD

**Issue by drduker** [OpenEmu/OpenEmu#1970]
I believe it is related to the fact that the plugin currently is mupen64.  However, if I run the game with mupen64plus-core(open source) it runs smoothly on Mac OS X, it just has large deficiency - no controller configuration possible.  Please implement a new video plugins or add additional video options for N64 so that 007 will work nicely.  Glide64mk2 is the video mode that I have had success with to make sure all 4 screens are not laggy or experience flickering.  Thanks!

**Comment by clobber** [comment]
![screen shot 2015-07-05 at 5 34 54 pm](https://cloud.githubusercontent.com/assets/1303132/8513731/31fcae50-233c-11e5-92a3-1528e4d32ce3.png)

As the dialog suggests, we'd really prefer to not receive bug reports on N64, especially because there is nothing we can do about it.

The Glide64mk2 plugin does not work with our implementation.
