### ISSUE TITLE
Openemu Crashing 

### ISSUE THREAD

**Issue by SEGADREAM** [OpenEmu/OpenEmu#2021]
Whenever I open openemu, this happens [tell me if screen shot doesn't work]
![screen shot 2015-08-17 at 8 50 56 pm](https://cloud.githubusercontent.com/assets/13797302/9303493/b0d945b0-4521-11e5-8d1d-cf575d905ba4.png)

**Comment by loicloic** [comment]
Click that report button then copy and paste the crashlog on https://gist.github.com for example and link it here.

**Comment by clobber** [comment]
@SEGADREAM It's obviously from your screenshot and prior posts that you are screwing around with your OpenEmu install. Since it is no one's responsibility to fix what you break, here is the only advice you are going to get:

1) Delete your OpenEmu install, this includes the application and everything in app support.
2) Download an official build of OpenEmu from our website: http://openemu.org
3) Do not ever open the App Support folder again. Do not add any files to OpenEmu's folder again. Stay out of there.

**Comment by SEGADREAM** [comment]
Thanks! By the way, Is multi-disk in the current version?

**Comment by SEGADREAM** [comment]
Thanks!
