### ISSUE TITLE
scph5502 deletes upon clicking a PS1 game

### ISSUE THREAD

**Issue by RainingJellyfish** [OpenEmu/OpenEmu#2068]
Certain BIOS files get deleted when I start up a PS1 game, including 5502 which is necessary. Even renaming another BIOS file (One that stayed) to 5502 caused that one to be deleted too.

**Comment by clobber** [comment]
That's on purpose. You are importing files incorrectly by forcing them into the BIOS folder instead of importing them from the UI which determines if you have the right BIOS files or not. You have the wrong files so they are being deleted.

Follow the guide that is both in the UI and in the wiki, they are there for a reason.

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files
