### ISSUE TITLE
Freezes on Yosemite

### ISSUE THREAD

**Issue by andy551** [OpenEmu/OpenEmu#2069]
After playing 4-5 NES times the screen goes black and pressing the stop button has no effect. I need to force-quit the app and then start it again in order to be able to play again 4-5 times & so on...
This seems to happen with any core.

**Comment by pipwerks** [comment]
I have had to force quit several times in Yosemite as well. It appears to happen randomly, but always after OpenEmu has been running for a while. I was only using the MAME/Arcade core.

**Comment by clobber** [comment]
Our last release is nearing a year old and when I was still running 10.10 I couldn't replicate any issues like this with the latest source, so it's probably something we fixed a long time ago. Going to close and assume fixed.

P.S. be sure to update to 10.11

**Comment by pipwerks** [comment]
Updating to the latest OS (especially when it is so new) is not always an option. For example, I have some software and drivers that are currently not compatible with El Capitan. Of course, this is not your problem, but I just wanted to share that "upgrade the OS" is not always an available solution. Thanks again for all the work on this, it is not unappreciated.

**Comment by andy551** [comment]
Totally agree, and I doubt that more than 5% of all Mac users have upgraded to El Capitan. A huge chunk is still on Mavericks, and that's probably this bug wasn't brought up before

**Comment by clobber** [comment]
@andy51 lol, conjecture. If [Yosemite is any indicator](http://www.imore.com/os-x-yosemite-sees-fastest-adoption-rate-ever-55-after-8-months), over 50% of users will be on El Capitan within its first 8 months of release.

>and that's probably this bug wasn't brought up before

So we already know the basis of your argument is bunk: the majority of Mac users were running 10.10 at one point which means that your "bug" wasn't reported because others have not experienced it before. 
This "bug" was not investigated here because your report was vague and its not something I (or others) experienced while running 10.10. Could even be unrelated to the app. Both of the comments here could even be unrelated issues!

Your opinion on which OSX we should support is irrelevant though.
