### ISSUE TITLE
Switch higan core to compatibility profile

### ISSUE THREAD

**Issue by thefiddler** [OpenEmu/OpenEmu#2071]
The performance profile of higan is not maintained, and is 2x slower and more buggy than the snes9x core. 

It would make sense to use the compatibility profile of higan instead. Almost any modern system can run this and it is significantly more compatible than the performance profile. Older systems can always rely on the snes9x core instead.

**Comment by PGGB** [comment]
I think I remember byuu mentioning this, but now I can't find it anymore. If you can link me to a post or something I'll switch it over.

**Comment by thefiddler** [comment]
This is the latest discussion on the topic: http://board.byuu.org/phpbb3/viewtopic.php?f=4&t=730

> I'd love to drop the performance profile now, but I'm a bit worried that'll be the new justification for why people won't upgrade from v073->v09x if I do.

> Maybe we can spin off the performance profile's cores to be included with the bsnes-only UI, and move tomoko/len to only having the accuracy+balanced profiles going forward. (meaning the cores would be missing from the higan_v09x.tar.xz source bundles as well.)

**Comment by clobber** [comment]
Okay, so none of what you said has actually happened. Glad we got that cleared up.

Keep in mind that switching profiles breaks save state compatibility, but perhaps that doesn't matter because save state compat breaks between releases anyway!

**Comment by PGGB** [comment]
Yeah I think it's fine to keep the performance profile for now. The only argument I see right now is that since there is no more OSX build of Higan, OpenEmu is the only (?) way to play the more accurate profiles on OSX without going back to a previous version.

I'll probably set up the other profiles as different targets so folks at least have the option to go in and compile an accuracy/balanced build if they want to. We can switch the default when the performance profile disappears from the source.

**Comment by thefiddler** [comment]
@clobber The performance profile *is* buggy, unmaintained, and going away. Byuu has been signalling this for at least 2 years now.

In any case, I would argue that adding, or outright switching to, the balanced profile is desirable regardless of the status performance profile. Balanced can run pretty much every SNES game correctly, with just a handful of exceptions. Performance is nowhere near that level of compatibility.

**Comment by clobber** [comment]
Important to note that the performance profile has mostly minor issues with the following games:
* A.S.P. Air Strike Patrol
* Funaki Masakatsu Hybrid Wrestler – Tougi Denshou
* Mecarobot Golf
* Mega Man X2
* Mega Man X3
* Mortal Kombat II
* NHL ’94
* Super Pinball - Behind the Mask
* Tetris Attack

"Balanced" profile has issue with A.S.P. Air Strike Patrol, obviously.

Back to your original argument, the Higan performance profile is better than Snes9x no contest. As @PGGB said, we can look at switching over to balanced when performance is finally dropped from source. We don't take save state breakage lightly because OpenEmu is designed to be pick-up-where-you-left-off by default and people aren't too happy to learn their states are worthless.

Closing this ticket since we will keep in mind switching profiles in future releases.

**Comment by PGGB** [comment]
https://github.com/OpenEmu/Higan-Core/commit/af277c0a1ad079ed20cd0421a9ceb3bb597b8cb5 has targets for compiling the core in both balanced and accuracy profile.
