### ISSUE TITLE
Importing saves into .m3u?

### ISSUE THREAD

**Issue by RainingJellyfish** [OpenEmu/OpenEmu#2073]
Is there a way to import Metal Gear Solid Disc 1 saves into the m3u containing disc 1 and 2? I played through Disc 1 and made the m3u afterward so I could get to disc2. When I start up the .m3u, the save files aren't there (and yes, I made sure the .cue files names matched). Is there a way to import the save states or battery saves so I could continue where I left off? Thanks.

**Comment by clobber** [comment]
Look m8, you're asking for help on 'experimental' stuff (because you couldn't wait until next release when this stuff is fully supported) and this isn't really the place for this.

To answer your question, you would probably have to rename your mem card save file for the game but I don't know what. No guarantee that would work.

**Comment by joaovitor2112** [comment]
Hi, it looks like i didnt understood something right, the 1.0.4 release already support the .m3u?? Im on 1.0.4 and cant seem to import the .m3u

**Comment by clobber** [comment]
@joaovitor2112 Sorry about that. It will be available in our next release (coming soon).
