### ISSUE TITLE
DeSmuME save-state loading error

### ISSUE THREAD

**Issue by C34H32N4O4Fe** [OpenEmu/OpenEmu#2103]
Hi.

I'm playing Pokemon Black, which has a known glitch in OpenEmu but not in DeSmuME. Because of this, I play it on DeSmuME most of the time. However, in order to enter an Action Replay cheat, I need to use OpenEmu (I can't fiure out how to do this, if it's even possible, in DeSmuME). However, when I transferred my DeSmuME save file to the folder where OpenEmu keeps its save files, OpenEmu was only able to see my old save file (even though I had deleted it from my computer and replaced it with the DeSmuME one). I deleted the "Quick Save" and "Auto Save" save-state files and tried again, and this time OpenEmy did see the mew save file, although a popup appeared as soon as I launched the rom (it said "The operation could not be completed." and "No other information is available about the problem."). I ignored the popup and was able to play. If I then save the game, the save file is fine and can be read by both OpenEmu and DeSmuME. However, if I save the state (by pressing command+S) and then try to load it, I get the same popup and the game freezes (I can unfreeze it by resetting the emulation or by closing and reopening OpenEmu). What's up with this?

Thanks in advance.

**Comment by clobber** [comment]
You kind of screwed up your internal data store by forcefully deleting those save state files. I don't really have a fix for you that wouldn't involve way more time than I am willing to spend, but in our next release (coming soon) we have a proper save state manager that may help.

Next time you want to stop auto saves from being automatically restored, you need to go into OpenEmu's Preferences > Library and click "Reset warnings" because the emulator won't see changes to an imported battery save file if you have reloaded a state (it has the old one in-state memory). That's just the way it works.

**Comment by C34H32N4O4Fe** [comment]
OK, thanks, I'll do that next time. Would reinstalling OpenEmu and the rom in question remove the issue?

**Comment by clobber** [comment]
You could just delete your Game Library folder, being sure to first back up all your games, and then reimport them all. Note: you will also lose all your save states doing this.
