### ISSUE TITLE
Beta Builds

### ISSUE THREAD

**Issue by vinkla** [OpenEmu/OpenEmu#2122]
What about creating beta builds of OpenEmu? Maybe a version that could run side-by-side with the stable release? We could call it `OpenEmu Beta.app`. I know this would be appreciated by early adopters and would make it easier for you to find bugs early on. What do you think?

**Comment by clobber** [comment]
No, because then we would have broken and work-in-progress builds spread around when we don't want that. We typically break things in source and prefer to be able to do that without needing to think about how the changes we make also affect bleeding edge/beta users. We also don't add enough features to need beta test cycles. So-called "early adopters" can continue to live dangerously by compiling from source.
