### ISSUE TITLE
Xcode build: success but OpenEmu.app doesn't get created

### ISSUE THREAD

**Issue by rvb3n** [OpenEmu/OpenEmu#2123]
Hi, I'm trying to build the latest version of OpenEmu but after the compiling process I can't find OpenEmu.app anywhere.

I already had success with past version but it seems that with the latest one Xcode doesn't generate the app.

To find I usually search for openemu.app in the finder but now it doesn't find anything.

I'm I the only one to have this problem?

Note: I've already tried to reinstall Xcode, delete the cache and delete and download again Openemu from github..

Thanks if you can help me!

**Comment by clobber** [comment]
You uhh, "reinstalled" Xcode and deleted everything related because you couldn't find the binary you compiled with it?

The default location for build products is `~/Library/Developer/Xcode/DerivedData`, it says so right in our [compiling guide](https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide).

If you didn't find your compiled binary via spotlight search, it hadn't been indexed yet.
