### ISSUE TITLE
OGG support for Genesis Plus GX

### ISSUE THREAD

**Issue by romulof** [OpenEmu/OpenEmu#2146]
In your documentation says:

> Mega CD/Sega CD (using Genesis Plus GX)
> CUE + BIN/IMG/ISO + CDDA tracks with WAV/OGG. MP3 is NOT supported.

I've made an image in CUE+ISO+CDDA that plays nice with tracks in WAV format, but compressing them with OGG made the music stop playing.

Here is how the CUE file looks like:
```
FILE "Sonic CD.iso" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
FILE "Sonic CD-02.ogg" WAVE
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
...
```

**Comment by clobber** [comment]
>FILE "Sonic CD-02.ogg" WAVE

Uh nope, replace WAVE with OGG

**Comment by romulof** [comment]
I replaced ...
```...
FILE "Sonic CD #02.ogg" OGG
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
...```

... and it didn't worked. Music is not playing.

And, by the way, OGG support for PSX works the way I posted before.

**Comment by digamejh** [comment]
I am having the same problem.

OGG appears not to be working for Sega CD games, even though it does for PS1 and Saturn (in the experimental release).

**Comment by Retropotenza** [comment]
I'm seeing this issue as well, in v2.0.8.

OGG works fine in PSX, Saturn and TG-CD, but not in Sega CD. I split a bin in wav, and it worked well. The same converted in OGG not (and I double checked the .cue, is correct as the others that I did for other consoles).

**Comment by romulof** [comment]
v2.1.1 still doesn't work

**Comment by Retropotenza** [comment]
I look deeper here, and proposed a fix in https://github.com/OpenEmu/GenesisPlus-Core/pull/3.

The issue was that the Ogg Vorbis Tremor library was present in the codebase, but not added neither in the GenesisPlus Xcode project, nor in the build settings for the target plugin.

My proposed fix:
* Add a class for Tremor in the project.
* Add -DUSE_LIBTREMOR flag and $(SRCROOT)/genplusgx_source include path in the build settings.

I take a look also in other cores that use the Tremor library:
* Picodrive allows to use it as well, but it looks not included in the original project (and there is a open bug to track this, see https://github.com/notaz/picodrive/issues/11, this may prevent ogg forest support for the few 32x titles on CD, six of them according to https://en.wikipedia.org/wiki/List_of_32X_games).
* In Mednafen the Tremor library is present already as a class, and used by default (without adding a specific flag, since there is a default fallback to it if HAVE_EXTERNAL_TREMOR is not defined).
