### ISSUE TITLE
OpenEmu 1.0.4 Experimental crash

### ISSUE THREAD

**Issue by kwemi** [OpenEmu/OpenEmu#2148]
Lately OpenEmu 1.0.4 Experimental crash constantly while I am trying to launch a game or try to access to the controller preferences.
The issue seem to come from the controller settings.

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: OEPSXRightAnalogDown)'
terminating with uncaught exception of type NSException
abort() called

Here is the full crash report
https://gist.github.com/kwemi/3514974a6ee8909871b2

**Comment by clobber** [comment]
I think this might actually be related to a custom font issue that we patched here already, https://github.com/OpenEmu/OpenEmu/pull/1894

Or you can try the following:

1) Navigate to the folder `~/Library/Application Support/OpenEmu` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)

2) Delete the "Systems" folder (if it exists)

3) Delete Default.oebindings in the "Bindings Configurations" folder.

Reopen app.

Otherwise, you need to wait until next release where this is already fixed.

**Comment by kwemi** [comment]
Ok there where no "Systems" folder but deleting Default.oebindings in the "Bindings Configurations" folder fixed my problem.
Thanks.
