### ISSUE TITLE
Gameboy emulator not working

### ISSUE THREAD

**Issue by MDJCM** [OpenEmu/OpenEmu#2179]
Tried Kirby and Tetris, both hang on a light blue / white square screen. Fail to load in the same way, then crash the OpenEmu app, and requires force quit.

**Comment by clobber** [comment]
Doesn't sound right to me, and you haven't provided any details. Which version of OpenEmu and OSX. How about a crash log?

**Comment by MDJCM** [comment]
I’ll take a video of it in action tomorrow and how do I provide a crash log? I have to force quit it to get out of the full screen mode with the blank screen.


Marcos

**Comment by clobber** [comment]
Video won't be helpful but maybe you are using the Higan core for Game Boy emulation instead of Gambatte. Logs are located in ~/Library/Logs/DiagnosticReports/ or easily accessible with Console.app

Anyway, troubleshooting this is rather pointless, as whatever was going on is already fixed for our next release (coming soon). The last release is over a year old now and a lot has changed.

I'll close but feel free to reply.

**Comment by MDJCM** [comment]
Hi, roughly when is the update coming out? In the next month?


Marcos
