### ISSUE TITLE
Steam Controller Support?

### ISSUE THREAD

**Issue by The-Pezman** [OpenEmu/OpenEmu#2209]
I've been looking into the Steam Controller, and while it seems that OSX drivers are not fully developed yet, they are definitely forthcoming. The steam controller would be an excellent option for certain console games (e.g. Mario Paint), so I'm just curious to know whether it's something to look forward to.

**Comment by clobber** [comment]
Probably not something we would add natively, but if someone creates a driver then maybe we could automap controls for it.

**Comment by qwoodmansee** [comment]
Clobber, I thought I would mention that I am very interested in this feature/support as well. Just showing that there is interest :)

**Comment by clobber** [comment]
Interest in what? We won't be writing any driver for the Steam controller. That is up to someone else to write a general purpose driver so it can be used with other applications.

**Comment by ascrane** [comment]
Curious if there are any plans to fix this. It seems that some OpenEmu component is preventing the standard HID functions of the controller from being recognized. The device acts as a standard keyboard/mouse and optionally joystick components, and doesn't require any special support in that regard. It seems as though there is some kind of partial support that is redirecting the controller's input into the void instead of treating it as a standard keyboard/mouse.
