### ISSUE TITLE
Higher Intelligence Cover art and Naming algorithm - Feature Request

### ISSUE THREAD

**Issue by panzander** [OpenEmu/OpenEmu#2221]
As it goes I've been collecting roms for almost a decade, and I have a massive library. When I pulled them into openemu a majority of them weren't recognized and thus excluded from the cover art download. With iTunes there are tons of third part apps that can scan just a little of song and compare it to a data base. This allows it to find the proper name and album artwork making for an amazing library experience(there are also programs that do this for movies and tv shows) A built in feature that scans games, names them, and downloads proper art work would create unparalleled beauty in user's libraries.

**Comment by clobber** [comment]
It doesn't really get more intelligent than a database of checksums for lookup which we currently do.

It's important to note we only identify retail releases and "good" dump of the games. No hacks, betas, overdumps, homebrew, translations, etc. This isn't going to change.

If the issue is with SNES games, they need to be "good" dumps, not containing the useless 512-byte SMC copier header. These usually come as .SFC files.
