### ISSUE TITLE
Save states won't save if you checked the "Don't ask me again" box

### ISSUE THREAD

**Issue by Passeparla** [OpenEmu/OpenEmu#2224]
In the new OpenEmu (2.0) on Macos X 10.11.2 save a game is impossible. We can click, but the game is not saved.

**Comment by clobber** [comment]
Can you describe this better, with exact steps to replicate the problem?

**Comment by acataldo** [comment]
Can absolutely confirm that I am having the same problem.  When you try to save ANY save state (making sure that the system is set to NOT ask for a file name at each save) the game will continue without saving.  The only time ALL emulators will save a game is if you have the system set to name the save each time.  Otherwise, you are unable to save a game, attempting to do so leaves no save file in the program nor in the application support/save state folder.  Also OpenEmu 2.0 MacOS X 10.11.2.  Additionally, this was not an issue in the experimental pack I had downloaded a few days ago.  Hope this gets resolved soon!

**Comment by clobber** [comment]
@acataldo Thanks for describing, we'll patch this soon.

For now, the quick workaround is to go to Preferences > Library > click 'Reset Warnings' and don't check the "don't ask me again box" when you are saving state.

**Comment by acataldo** [comment]
Yep, absolutely works.  Thanks for all your work on this project, you've done an unbelievably amazing job (is there a place to donate?)

**Comment by clobber** [comment]
Resolved in https://github.com/OpenEmu/OpenEmu/commit/4ba8b8a8c4dde3f4ca32c595732be20e913693bc

We'll push out an updated release when we can.

**Comment by clobber** [comment]
Fixed for 2.0.1, out now.
