### ISSUE TITLE
OpenEmu 2.0 Crashes Upon Loading ANY Game for ANY System

### ISSUE THREAD

**Issue by CadmiumRED** [OpenEmu/OpenEmu#2226]
I just downloaded the newest 2.0 version from in-app in the Experimental Pack Version 1.0.4 of OpenEmu on my Macbook Pro with OSX 10.11.2 El Capitan, and now the software crashes upon loading any game for any system.  I've tried deleting the binding file in the Bindings folder and deleted all cores and reinstalled a few to see if those could be what's at fault.  Sadly, every game I double-click on instantly crashes the software and yields a report.  Is there something I'm doing wrong or is it due to the software itself?

https://gist.github.com/CadmiumRED/d5513f6a172f0adab5d8

**Comment by clobber** [comment]
We resolved this through funky measures (creating a new OpenEmu folder in app support and letting setup assistant run), but will keep open a while to investigate.

**Comment by alexcuemagOE** [comment]
<img width="460" alt="captura de pantalla 2015-12-25 a las 4 08 45 pm" src="https://cloud.githubusercontent.com/assets/16439642/12004500/8943530c-ab23-11e5-91e8-c30e9f7bbc30.png"> Everytime I tried to load my save data in OpemEmu this appear, and only in the game I have a lot of saves data. I don't know if it's the games or the software itself

**Comment by capeman29** [comment]
I am experiencing the exact same issue. Start a rom and instant crash followed by the exact same report that CadmiumRed posted above. Are there any other folders with settings to try deleting other than the OpenEmu folder in the application support? I tried backing up and nuking that folder completely, but even after that still getting the crash.

Macbook pro (high end version with discreet graphics card) 2015 model.
Error code reads as follows:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull systemBindingsDidSetEvent:forBinding:playerNumber:]: unrecognized selector sent to instance 0x7fff763c8780'
terminating with uncaught exception of type NSException
abort() called

**Comment by clobber** [comment]
Hrm yeah, sorry about the trouble. Haven't tracked this down yet, but I believe CadmiumRED resolved this by:

* Running `defaults delete org.openemu.OpenEmu` in Terminal to reset prefs.
* Renaming the OpenEmu folder in Application Support.
* Relaunching the application (standard build) so the folders are recreated and the Cores redownload.
* Imported a single game just to make sure everything is now working correct.

Later they copied their old Game Library, Save States, BIOS and individual core support folders (Mednafen, Nestopia, etc) into their new OpenEmu folder. Don't copy any of the rest or other files.

**Comment by capeman29** [comment]
Brilliant! Running fine now. 

Might be because i upgraded from a source build (from around August) instead of the official binary from the website. Probably made the prefs file act funny. If cadmium was using a source build also, it might not even be an issue that most users of the official 1.x binary would experience. Just a thought, but I'm no coder, haha.

Let me know if i can help out any further, i think i still have the crashlogs saved if they can be of any use.

**Comment by azileyalt** [comment]
clobber, how do I do the first 2 steps that CadmiumRED did? I am probably less techy than everyone else in here, so specific instructions are appreciated- I'm on a new MacBook if that makes any difference in procedure.

**Comment by clobber** [comment]
@azileyalt I updated the guide above with another step to explain that.

**Comment by azileyalt** [comment]
Thank you. Still not working. Will there be another update soon to fix this? OR, even better? Can I undo the last update and use the second-latest version of OpenEmu? I miss my game :/

**Comment by thedeeper87** [comment]
64 games are unplayable, video/music is very choppy with the new El Capitan update 10.11.3

**Comment by SirVer** [comment]
I figured out that deleting my `Bindings` folder is enough to get OpenEMU going again. I am using a iBuffalo SNES like gamepad for playing. Maybe that helps tracking this down.

**Comment by woodar13** [comment]
I did the steps above and now when OpenEmu opens its just a clear window. I also tried the transparency thing listed in #2375 but that didn't fix it

**Comment by SirVer** [comment]
@clobber The steps from 26 Dec 2015 did not fix it for me. OpenEMU still crashes when launching any game until I delete the `Bindings` folder. Then, a game launches once successfully. I configure my controller (a 2 axis iBuffalo Classic USB Gamepad, looks like a SNES controller) and can play, but once I exit the game and try to start any other (I test with SNES and GBA roms), OpenEMU crashes.

Full [Apple Crash Report details are here](https://gist.github.com/SirVer/132cf43d4f16fcb229f2f9e7907a249e).
