### ISSUE TITLE
After core updates error message

### ISSUE THREAD

**Issue by cwscws** [OpenEmu/OpenEmu#2238]
I updated all cores but suddenly only get an error message that the plugin can not be loaded. Maybe it's related to my version number 1.0.4 of OpenEmu. But I can not update the emu itself as I'm using MacOS 10.9.5 and I won't update to the latest OS.

Please let us use OpenEmu 2.0 or at least 1.0.4 with the lastest plugins with MacOS 10.9.

**Comment by clobber** [comment]
Yes, you need to upgrade to 2.0 or redownload the older cores. The newer are not compatible and there was no way to do version checks at the time.

**Comment by cwscws** [comment]
But 2.0 is not compatible with MacOS 10.9. Any chance of making it compatible?

**Comment by robotoad** [comment]
@cwscws 

I'm afraid there's zero chance because the application relies on newer APIs. This decision was made taking into consideration the fact that OS X updates are free and that system requirements haven't increased in several releases. It's strongly recommended that you upgrade, if possible, not just for OpenEmu but for security and feature updates in the operating system.

**Comment by cwscws** [comment]
Sorry to hear that. I really hoped that at least the plugins would be updated to the latest revisions.
