### ISSUE TITLE
Latest version for those not running OS X El Capitan?

### ISSUE THREAD

**Issue by asoksevil** [OpenEmu/OpenEmu#2241]
I understand OpenEmu 2.0 requires 10.11 but there are still ton of people using Yosemite, Mavericks and below. Which is the latest release supported by them that include several fixes? (You could previously compile it directly from Github, but I am not sure if you are able to do it now)

Thanks!

**Comment by clobber** [comment]
Unsupported, but 1.0.4 and you would need to manually download the cores.

Why not just upgrade?

**Comment by xythobuz** [comment]
I'm still depending on drivers that don't reliably work on El Capitan yet, so I can't upgrade.

I'm curious, what has changed in OpenEmu that it can no longer run in Yosemite?

**Comment by clobber** [comment]
The application relies on newer APIs not present in older versions of OS X.

**Comment by robotoad** [comment]
@xythobuz Speaking for the component I'm most familiar with (the UI), development and testing has taken place with the assumption of 10.11 for a while now, so there are 10.11 dependencies scattered throughout--mostly in Foundation usage, and there are likely other El Capitan-specific behaviors that the application now implicitly depends on.

As for why this is the case: since backwards compatibility was already breaking, it was decided to start fresh on El Capitan, since it's generally considered a "better Yosemite." I can't speak on future backwards compatibility, but note that first-class API availability checking in Swift makes it much easier (of course, this requires converting to Swift in the first place). The main point here is that 2.0 represents a path of modernization for the project, and step one was requiring a contemporary OS X release.

**Comment by xythobuz** [comment]
Alright, thank you for the explanation.

Just to make my opinion known: I think that's not a good decision and I can unfortunately no longer use OpenEmu for the foreseeable future.

Thanks for the great work in this open source project to you all, anyway :smiley:

**Comment by asoksevil** [comment]
@clobber I would like to update but I cannot at this moment due to app compatibility. I had a previous version of 1.0.4 running with all the cores needed downloaded manually.It was the october 2014 version but you guys have even adding new stuff so I guess my 1.0.4 version is not the latest one you could get compiling directly prior to the release of 2.0.0 since you guys said that you were just updating and fixing stuff directly on github and if you wanted to try out the newest build you had to compile it.

This is what I am looking for, someone who compiled the latest 1.0.4 with all the fixes (multi disk PSX support for instance) https://www.reddit.com/r/OpenEmu/comments/3kafwp/osx_openemu_104_build_c711249_experimental/

**Comment by clobber** [comment]
Sorry, we won't be providing any updated 1.0.4 builds as that is now unsupported. All one can do now is use the old 1.0.4 release and then manually download the cores from their repos in our org that worked during that release.
