### ISSUE TITLE
(Option to) replace separate discs in library view by the combined (.m3u) game + cover art

### ISSUE THREAD

**Issue by aktau** [OpenEmu/OpenEmu#2264]
I'm not sure if what I'm seeing is just my stupidity or a "working as intended" thing.

I have a multi-disc PSX game, and created an .m3u file for it as detailed in the wiki. It works fine, I can start the newly created game via the icon created in the library view. There's two things that I think could be improved:

- The old, separate disc games are also still present in the game library view.
- The cover for the multi-disk game (the one created by importing the .m3u file) is not automatically recognized, so it stays with the default "rainbow" icon. I named the .m3u file as <name-of-the-game-without-disk-identifier>.m3u, so I thought it would work. **EDIT**: I just noticed #1146, which implies cover art to use is matched by hash. Which explains why the .m3u is not getting any cover art. Perhaps it would be OK to just use the cover art of the first disc (which is the same as all the other discs in my experience).

**Comment by clobber** [comment]
Yeah, we won't be able to match covers for .m3u files. You can just drag and drop your own cover art files onto the .m3u file.

To remove the old separate discs, just right click on them and delete making sure to delete the file from your library but keeping the binaries in your Game Library folder. You will be prompted for this as long as you haven't previously clicked the "don't ask me again" checkbox. Otherwise, go into Library preferences and click the "Reset Warnings" button to enable these dialogs.

**Comment by aktau** [comment]
Sure, seems reasonable. However, it would be nice if I was able to easily re-use the cover art of one of the discs to the multi-disc icon. At the moment, I'm finding it art which of the UUID-like filenames in "Game Library/Artwork" corresponds to the one I want. Am I missing something obvious?

**Comment by aktau** [comment]
My current solution is to do:

```bash
$ parallel "cp {} ./{/}.png" ::: ~/Library/Application\ Support/OpenEmu/Game\ Library/Artwork/*
```

I had guessed that the UUID-like filenames were supposed to be .png's, it being the natural format for cover art.

And then to do "Add Cover Art from File". It works but it's a bit clumsy, and does stand in stark contrast with the general ease-of-use of OpenEmu. Perhaps its can be added like that to the wiki.
