### ISSUE TITLE
video standard mismatch

### ISSUE THREAD

**Issue by stynae** [OpenEmu/OpenEmu#2274]
So, I'm totally new at this, but, i've downloaded some games for ps1 and most of them are running perfectly but with one, i get first the ps logos (like normal) but after, the screen turns black with a message "video standard mismatch". I still hear the sounds of the game as is it was running normally (can choose the name, press X, start button, etc.) without the image.
So i just don't know what to do and hope you could help me
Thank you

**Comment by mrvacbob** [comment]
Which game is it specifically, and which original region (US, EU, Japan)? Could you try it with a standalone emulator, especially Mednafen?

**Comment by velvetman** [comment]
I used to have this problem with PS1 games. It turned out to have something to do with either the bios files I installed or the way I installed them. Not sure which. Anyway, I had a hard time getting the bios files to install and work in 1.0.4, so I ended up following instructions I found on some random website Google pointed me to. It kind of worked because I could play the games, but I always go the "video standard mismatch" error screen at startup. After upgrading to 2.0, I noticed that the new System Files tab in Preferences had a lot of orange triangles with exclamation points by the bios files. So I did another search, and found this official bios tutorial: https://github.com/OpenEmu/OpenEmu/wiki/User-guide%3A-BIOS-files  After following that, and verifying the MD5s, everything is working perfectly now. Hope that helps.
