### ISSUE TITLE
Show filtered view of consoles in Library, so as to make selecting games easier

### ISSUE THREAD

**Issue by epheterson** [OpenEmu/OpenEmu#2276]
Seeing a list of dozens of consoles of which no games exist makes selecting the consoles which do have games that much more difficult. Ideally, we could filter the view and ALSO show a count on the right hand side of how many games exist in the library for each console.

**Comment by clobber** [comment]
Simply right click on the sidebar to hide the ones you don't want to see or are empty.

**Comment by nicolasmccurdy** [comment]
Hiding specific consoles manually doesn't fully satisfy this use case in my opinion. What I (and @epheterson probably) want is for the sidebar to automatically hide consoles with no games. This could either be default behavior or hidden behind an option. I don't like having to right click to hide individual consoles manually because it's tedious, and I might accidentally hide a console that I add a game for later, making it harder to play those new games.

**Comment by clobber** [comment]
Sorry, no useless clutter for a very specific use case to satisfy your OCD.
