### ISSUE TITLE
(PSX) Multiple Disc Games

### ISSUE THREAD

**Issue by SupahBawz1009** [OpenEmu/OpenEmu#2298]
First off, Happy New Year!
I've been playing Final Fantasy VII, and it tells me to insert disc 2. I cannot switch over, no matter what. I've done the .m3u thing, and when I drag the file in, it does absolutely nothing. It doesn't add a game, it doesn't modify a game, nothing. I opened Disc 1, and it has no option to do what the tutorial says to do.
Help and reason of why it isn't working would be greatly appreciated. Thank you.

**Comment by clobber** [comment]
>I've done the .m3u thing, and when I drag the file in, it does absolutely nothing.

This doesn't really explain what is going on, but you need to follow the guide closely.

All I can say is you need to have:
* both discs imported.
* the m3u file imported.
* started your game via the m3u file and not the individual discs, otherwise the Mednafen did not create a single memory card file to save your progress on.

Beyond that there isn't anything else I can help you with. I believe those following the guide are not realizing they need to launch their game with imported m3u file and not the individual discs.

**Comment by SupahBawz1009** [comment]
What I mean is that when I drag the .m3u file in, OpenEmu does not import the game. I've followed all the steps, and can send a screenshot of both the file and the name.

**Comment by clobber** [comment]
You cannot import the discs when you import the m3u file, you must import the individual discs first and then the m3u file. If the m3u file is not importing, well, you have done it wrong since any .m3u file should import into the PlayStation library.

**Comment by SupahBawz1009** [comment]
Below is a screenshot of both the file and the library.  When I drag .m3u in, nothing imports. I see nothing wrong with the file, nor the version I am on.
![screen shot 2015-12-31 at 2 33 39 pm](https://cloud.githubusercontent.com/assets/10931044/12067655/bb997384-afcb-11e5-9536-e429d8081fda.png)
![screen shot 2015-12-31 at 2 34 01 pm](https://cloud.githubusercontent.com/assets/10931044/12067656/bfe64f20-afcb-11e5-837c-0603da1c3694.png)
![screen shot 2015-12-31 at 2 34 17 pm](https://cloud.githubusercontent.com/assets/10931044/12067657/c1cbcf68-afcb-11e5-8918-9e77ae036afc.png)

**Comment by clobber** [comment]
Uh???

You need to be using OpenEmu 2.0 for multi-disc support.

**Comment by SupahBawz1009** [comment]
Oh.
Whoops.
Well, I updated, and sure enough the m3u file adds the games.

Now there's another issue that pops up.
I'll make a seprerate post, but thanks on help for this one.
