### ISSUE TITLE
Steam controller is not working

### ISSUE THREAD

**Issue by MrFrancOSX** [OpenEmu/OpenEmu#2306]
I have an steam controller, since the new update, Open Emu is not recognising my device.

Hope you can fix it asap. There is some post taking about it.
https://www.reddit.com/r/OpenEmu/comments/3y7wri/openemu_20_no_longer_recognizes_steam_controllers/

**Comment by Kithop** [comment]
I actually bought a Steam Controller, got it working with RetroArch on my Linux HTPC, went 'this is awesome!' and decided I'm going to bring my MacBook Pro to a party tonight.  Unfortunately, yeah, with the update this got completely missed.  However, rolling back to OpenEmu 1.04 works, and it detects as an MS Wired Xbox 360 Controller (when you set Steam's 'Desktop configuration' to a generic Gamepad).

I'm guessing that v2 had some refactoring on the gamepad input and this is some kind of regression?

**Comment by Kithop** [comment]
Console.app logs for OpenEmu v1.04 on startup ('GamePad-1' is what HIDBrowser.app shows):

2015-12-31 15:11:35.068 OpenEmu[72124]: CoreData: Failed to load optimized model at path '/Applications/OpenEmu.app/Contents/Resources/OEDatabase.momd/OEDatabase 1.3.omo'
2015-12-31 15:11:35.387 OpenEmu[72124]: Keyboard-1
2015-12-31 15:11:35.388 OpenEmu[72124]: Apple Internal Keyboard / Trackpad
2015-12-31 15:11:35.547 OpenEmu[72124]: Device is already being handled
2015-12-31 15:11:35.547 OpenEmu[72124]: Device is already being handled
2015-12-31 15:11:35.547 OpenEmu[72124]: GamePad-1
2015-12-31 15:11:51.370 OpenEmu[72124]: OE_removeStateWatcher

For v2.01:
2015-12-31 15:12:05.927 OpenEmu[72128]: Device does not have a location ID
2015-12-31 15:12:05.928 OpenEmu[72128]: Apple Internal Keyboard / Trackpad
2015-12-31 15:12:05.930 OpenEmu[72128]: Device does not have a location ID
2015-12-31 15:12:05.930 OpenEmu[72128]: Device does not have a location ID
2015-12-31 15:12:05.930 OpenEmu[72128]: Device is already being handled
2015-12-31 15:12:05.930 OpenEmu[72128]: OELibraryDatabase loadFromURL: 'file:///Users/kithop/Library/Application%20Support/OpenEmu/Game%20Library/'
2015-12-31 15:12:12.665 OpenEmu[72128]: OE_removeStateWatcher

**Comment by Kithop** [comment]
HIDBrowser output for the 'GamePad-1' Emulated MS device I believe the Steam Controller is using & working with in v1.04 (but doesn't show up in v2.01).  Location ID is 0x00 - potentially an issue?
![openemu-issue2306-steamcontroller-hidbrowser](https://cloud.githubusercontent.com/assets/11277115/12069043/891f8f46-afd1-11e5-818c-d3e0d5c72c81.png)

**Comment by Kithop** [comment]
Potentially related to #2209 (regression rather than new feature?)
Also, the Mouse & Keyboard emulation entries if you're interested:
![openemu-issue2306-steamcontroller-mouse-1-hidbrowser](https://cloud.githubusercontent.com/assets/11277115/12069055/396b6b2c-afd2-11e5-8cc1-7b2dfcbd773f.png)
![openemu-issue2306-steamcontroller-keyboard-1-hidbrowser](https://cloud.githubusercontent.com/assets/11277115/12069056/3b8ee88e-afd2-11e5-9fc7-75429e895c76.png)

**Comment by starsasumi** [comment]
For addition information, even I config the Steam Controller to output keyboard event (ex. d-pad to WSAD), OpenEmu can not receive these too.

**Comment by ninjajs** [comment]
Valve now provides mac drivers for the steam controller so it shouldn't be too difficult to add support in openemu.

**Comment by clobber** [comment]
@ninjajs Gee, uhh could you provide a link to information of said 'driver'?

**Comment by ninjajs** [comment]
@clobber inside the steam app theres a SteamInputInstaller.pkg. It may only be available with the beta client.
<img width="827" alt="screen shot 2016-02-15 at 10 19 27 am" src="https://cloud.githubusercontent.com/assets/5178973/13056989/0d138f4e-d3ce-11e5-9b30-f0400617fc3a.png">

**Comment by ascrane** [comment]
It seems that some OpenEmu component is preventing the standard HID functions of the controller from being recognized. The device acts as a standard keyboard/mouse and optionally joystick components, and doesn't require any special support in that regard. It seems as though there is some kind of partial support that is redirecting the controller's input into the void instead of treating it as a standard keyboard/mouse.

**Comment by kode54** [comment]
OpenEmu-SDK commit 132a27b684fdba8d4381ef540fd5761c795df663 references this. Steam's virtual controllers would return 0 or NULL for their location value. Unless someone wants to buy me a second Steam controller to determine if they increment that value for extra controllers, I think the only way to uniquely identify controllers is to check the device name, which contains an incrementing number, starting from 1.

**Comment by kode54** [comment]
Quick and dirty hack to OEHIDDeviceHandler, to support devices that return NULL for their Location parameter:

````
- (NSNumber *)locationID
{
    //return (__bridge NSNumber *)IOHIDDeviceGetProperty(_device, CFSTR(kIOHIDLocationIDKey));
    NSNumber * num = (__bridge NSNumber *)IOHIDDeviceGetProperty(_device, CFSTR(kIOHIDLocationIDKey));
    if (num == nil)
    {
        unsigned long sum = 0;
        NSString * str = [self product];
        const char * cs = [str UTF8String];
        while (*cs)
        {
            sum += (unsigned long)(unsigned char)(*cs);
            cs++;
        }
        num = [NSNumber numberWithLong:sum];
    }
    return num;
}
````

This also requires disabling the null check in OEDeviceManager. Confirmed for working Steam controller emulation mode.

**Comment by Kithop** [comment]
I've actually got two Steam Controllers, bought at the same time, that I've paired to the same USB dongle.  They work fine together in other games (and Retroarch on a Linux HTPC) together.  If I have them both on and hooked into my Mac here at the same time, what sort of stats/debug info can I pull for you to help with the identification of multiple controllers?

Just the same HIDBrowser output?

**Comment by kode54** [comment]
HIDBrowser output would be helpful, in case it actually turns out that one of those two devices actually has a non-zero Location value. I'm guessing that they do not, that they just have "GamePad-1" and "GamePad-2" product identifier strings. Which is why my null Location value handler is designed to produce a sum of the characters in the product identifier string, so that unique device names still produce unique device identifiers.

As I said, feel free to Git clone the entire source tree, and do a submodule update --init --recursive, select the correct build target, either release ready or plus experimental cores, and hit the Build for Profiling button to build a Release build. (I've found that some random steps tend to fail when actually Archiving, such as the make68k step of the MAME core.)

You'll want to apply the changes I indicated in my previous post here, commenting out the null check in the one file, and replacing the function in the other file, both parts of the OpenEmu-SDK submodule/project.

**Comment by Kithop** [comment]
I think you're right on the GamePad-1 vs GamePad-2 thing.  I'm not a developer and don't have the build system set up on my machine here but I might be able to give it a shot this weekend.
![openemu-2306-gamepad1](https://cloud.githubusercontent.com/assets/11277115/13887345/6725c630-ecf8-11e5-91db-320f311f084c.png)
![openemu-2306-gamepad2](https://cloud.githubusercontent.com/assets/11277115/13887346/67283fdc-ecf8-11e5-9def-2c792fc2ba9a.png)

**Comment by onetwopi** [comment]
Hello,
Has anyone found any resolution on this issue?

**Comment by maruxe** [comment]
anyone?

**Comment by JacobMillward** [comment]
This issue is still open. Has any progress been made?

**Comment by kode54** [comment]
I already reported that it's not working because the Location field is 0, and I already posted my own workaround, which is to generate a location from the full device name, using a simple sum of the characters, and I don't think they intend to accept it.

More of the simple belief that people who buy badly designed hardware with equally badly designed software should not expect their products to work at all, and should buy from the approved products list instead.

Perhaps go patronize Sony and buy some Dual Shock 3 or 4 controllers instead, those work with Macs out of the box.

**Comment by JacobMillward** [comment]
Maybe submit it as a PR so that they can provide feedback on the exact reason they won't accept it?

**Comment by kode54** [comment]
Sorry, I was being rude. I was feeling off at the time, maybe a bit tired. I'm about to submit a PR that will reference this issue.

**Comment by DuncanHillsCoffee** [comment]
Thanks!
