### ISSUE TITLE
Cannot Import any ROMs

### ISSUE THREAD

**Issue by ptiemann** [OpenEmu/OpenEmu#2320]
Nothing shows in library after importing.

Macbook Pro mid 2012 13 inch, El Capitan 10.11.2. 
Steps I've taken
1. Downloaded OpenEmu
2. Opened zip file
3. Double clicked expanded file and the app started. I didn't have any ROMs so downloaded several for Atari 5200 and tried to import by selecting and dragging them in. OpenEmu either ignores them or shows import error. 
I may be missing something or have the mac configured incorrectly. Open to any suggestions or help.

**Comment by clobber** [comment]
Atari 5200 games should either have the file extension .a52 or .bin

**Comment by elpico99** [comment]
Same problem for me and if i used directly Jum52 it work . my roms have the extension .a52

**Comment by Gerst20051** [comment]
it's not letting me import .bin roms

**Comment by Gerst20051** [comment]
you need to specify the platform you are importing for since the extension .bin is used for many different systems. just found the answer here: https://github.com/OpenEmu/OpenEmu/issues/2222

<img width="334" alt="screenshot 2016-07-03 02 08 10" src="https://cloud.githubusercontent.com/assets/235372/16544027/3ee6033c-40c3-11e6-86c7-4783b8d75fe2.png">

**Comment by Gerst20051** [comment]
it would be nice if there was a way to programmatically inspect the contents of a .bin file to determine which system it was intended for.
