### ISSUE TITLE
PS3 Controller Issues

### ISSUE THREAD

**Issue by therealdangles** [OpenEmu/OpenEmu#2334]
I'm having a lot of trouble getting the PS3 controller to work. I can sometimes get it to connect to my MacBook Pro (El Capitan), but even when it's connected, it won't show up in OpenEmu. Any known issues with El Cap and this version of OpenEmu related to PS3 controller? I've tried about 5 different tutorials on connecting the controller and none have worked.

**Comment by clobber** [comment]
No known issues with Dualshock 3 and the application. One thing comes to mind is that you may not have the official controller and perhaps a knockoff instead.

You can search through this issue for identifying if you have a knockoff or not: #1041

Otherwise, you can follow these various guides here:
* https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-DualShock-Controller-Pairing
* https://gist.github.com/3172711
* http://bit.ly/W26q2k
