### ISSUE TITLE
Two DS4 Controllers Don't Work

### ISSUE THREAD

**Issue by davidedwardclark** [OpenEmu/OpenEmu#2339]
I have two identical DS4 controllers and the second one doesn't work with OpenEmu. I am using the latest version.

**Comment by futurepr0n** [comment]
Hi David - I am finding that works perfectly actually. I tested this over the weekend, and am really curious how OpenEmu implemented this because I am unsuccessful trying to acheive the same configuration in RetroArch (please reach out to me OpenEmu Devs if you can!)

David, what you should do is have both your DS4's connected to the Mac wirelessly, now boot up OpenEmu. From here, you need to go to OpenEmu menu, and Preferences, look for the controls - and you will need to map your controllers. The Emulator I tested this with was the PSX emulator, so when selecting the PSX Controller from the Controls Menu, you then need to use the drop down at the bottom (under all the mappings), and select Device. You should see that after you select Playstation 4 Controller), that when you choose player 2 for PSX, and go to the same drop down - you will see that P1 and P2 are both set to different PlayStation 4 controllers.

You need to do the same for each of the controllers, for your emulators.

Let me know how it goes.

OpenEmu Devs - I am unable to get a configuration in RetroArch with 2 controllers - for whatever reason, P1 and P2 map to the same wireless controller. Can you help me understand how you built these controller profiles and saved them so that I can work on some RetroArch improvements?
