### ISSUE TITLE
mame issue on openemu

### ISSUE THREAD

**Issue by jameslinrf** [OpenEmu/OpenEmu#2349]
I have downloaded the the openemu 2.01 version. some of the arcade roms are working perfectly on openemu, they are still a lot roms doesn't work at all. personally a lot of times when i want to run a arcade rom, and it shows that "failed to make complete framebuffer object 8cd6" "Display's nominal refresh rate is 59.97 Hz" . does anyone know how to solve this issue? thanks a lot.

**Comment by clobber** [comment]
MAME is tricky, which is why the core port is still in the 'experimental' cores bundle and not officially supported. One needs to be using games from a MAME 0.149 ROM set as well as whatever required parent/bios/system file ROMs the game may need. Some games, even though they are included in a MAME ROM set, don't actually run at all. Best I can do is like you to a guide that may or may not be helpful: http://agreeordie.com/how-to-emulate-retro-video-games/
