### ISSUE TITLE
Game Boy / Colour

### ISSUE THREAD

**Issue by MuzakaEklekta** [OpenEmu/OpenEmu#2355]
Need to be able to distinguish the difference between the two consoles. e.g. rom for Tarzan exists for Game Boy and Game Boy colour. Same No-Intro name. Perhaps a different console category or an overlay saying (Colour) on the artwork or next to rom name.

As I like to audit my roms with clrmamepro, because of this behaviour, I have now disabled 'copy roms' and 'keep organised'.

**Comment by clobber** [comment]
We won't do this as it seems unnecessary, both Tarzan games would import into the Game Boy library which is fine. They will both have covers, etc.

**Comment by MuzakaEklekta** [comment]
Very true. What about list view? How do we differentiate between the two?

**Comment by clobber** [comment]
Game Boy Color games are essentially just Game Boy games (they can even be hacked to run on the original DMG), which is why we didn't make the distinction between the two in the library. If it really matters that much to you, create a new collection (+ sign at the bottom) and stuff applicable GBC games in there.

**Comment by MuzakaEklekta** [comment]
Great idea. Thank you :)
