### ISSUE TITLE
Arcade Core And MAME 

### ISSUE THREAD

**Issue by PJCL31** [OpenEmu/OpenEmu#2359]
Hi There, 
I've a problem with OpenEmu.
Hes run on a Macbook Pro Under Yosemite 10.11.02 but arcade core dosen't work and many games like Nintendo and SUPER NES create me some problem to run proprely on my computer.

The first time when add OpenEmu on my mac everything work right but since a clean disk he's disfonctional.

I made the new upgrade for OpenEmu i was download and updates many more core but Acrade is always not available and i've always some probs to open games.

Have you a solution ?

Thanks a lot

**Comment by clobber** [comment]
MAME is tricky, which is why the core port is still in the 'experimental' cores bundle and not officially supported. One needs to be using games from a MAME 0.149 ROM set as well as whatever required parent/bios/system file ROMs the game may need. Some games, even though they are included in a MAME ROM set, don't actually run at all. Best I can do is like you to a guide that may or may not be helpful: http://agreeordie.com/how-to-emulate-retro-video-games/

**Comment by PJCL31** [comment]
Thx Clobber for you help ... i understand nothing LOL but thx :)
