### ISSUE TITLE
Can't run Saturn game that works fine with Yabause 0.9.14

### ISSUE THREAD

**Issue by ffreling** [OpenEmu/OpenEmu#2392]
I can't run Saturn Bomberman with OpenEmu 2.0.1 but the same files (cue + bin) work fine with Yabause 0.9.14 standalone.

I checked the Console.app but I couldn't see anything relevant like a crash.
Where should I look to debug this issue?

**Comment by clobber** [comment]
Like Yabause standalone, some games require a BIOS file for better compatibility -- Saturn Bomberman is one of those games. This functionality is not yet supported in our 'experimental' core port of Yabause.

**Comment by ffreling** [comment]
Alright, thanks for the quick answer.
It does work in Yabause with the BIOS emulation though, that's why I thought a BIOS was not a requirement.

I'll wait a bit until the core port stabilises.

**Comment by clobber** [comment]
Our port of Yabause uses the last stable release, 0.9.14. There should be no compatibility differences between the standalone and our port as long as they are the exact versions and settings.

Yabause is 'experimental' and is unlikely to ever been in the 'standard' release of OpenEmu due to its very low compatibility in general.

**Comment by ffreling** [comment]
Any way to debug it except via Console.app?
