### ISSUE TITLE
MAME not working

### ISSUE THREAD

**Issue by Bass-N-Roll** [OpenEmu/OpenEmu#2419]
Hi there
The new version of Open Emu is like a dream come true for me ! The only problem is that each arcade games that I try to play is not working at all. Worst of it, it crashes OpenEmu.
Witch games are compatible ? Witch version of MAME is used on OpenEmu ?

Thx guys !

**Comment by clobber** [comment]
MAME is tricky, which is why the core port is still in the 'experimental' cores bundle and not officially supported. One needs to be using games from a MAME 0.149 ROM set as well as whatever required parent/bios/system file ROMs the game may need. Some games, even though they are included in a MAME ROM set, don't actually run at all. Best I can do is like you to a guide that may or may not be helpful: http://agreeordie.com/how-to-emulate-retro-video-games/
