### ISSUE TITLE
Occasional dropped frames without clear reason

### ISSUE THREAD

**Issue by burnburnrocket** [OpenEmu/OpenEmu#2463]
Hi there. I'm running OpenEmu 2.0.1. I also remember seeing this on earlier versions of OpenEmu as well, though I haven't tried them in a while. Basically, it's a very intermittent choppiness. Maybe once every couple minutes the game seems to start dropping frames for 2-5 seconds and then picks back up. I don't think I've noticed any change in sound during that time.

As a first troubleshooting step, I started by setting the filter to nearest neighbor. With any filter including nearest neighbor, the stutter still happens. I'm on 10.11.3 with a Core i7-4770, Geforce GTX 660, 16GB ram. My screen res is 1920x1200, and I've observed the stutter in both fullscreen and windowed. 

I've tried disabling both Fl.ux and BetterTouchTool, which are the two things I normally use that I thought could potentially interfere. I've also tried killing Chrome, which is normally the only processor/memory intensive program I leave running.

 If anyone's seen this, or has suggestions on how to debug it, I'd really appreciate it. Thanks!

*Edit, just realized I didn't mention which cores I was using. I've seen this happen on both GenesisPlus and Nestopia cores. I haven't spent a lot of time with any others.

**Comment by clobber** [comment]
Yeah, this is a general syncing issue where the game is running at a different rate than your display (e.g. ~59 fps vs ~60 fps), so there isn't anything you can do on your end to solve. It is usually not so noticeable and your eyes adjust, though some people are more sensitive to the issue.

The fix would possibly be adding an option for advanced syncing that would involve running the game at the same rate as your display refreshes. Closing this, though it is not solved, since we are tracking this in other issues.

**Comment by burnburnrocket** [comment]
Thanks, @clobber. Do you have a link to the open ticket, if any? I'd love to subscribe to it, if it's public.
