### ISSUE TITLE
Graphic "tearing" at screen edges in certain NES Games

### ISSUE THREAD

**Issue by Phalaric** [OpenEmu/OpenEmu#2472]
I've noticed this to happen in at least two games, Super Mario Bros. 3 and the Earthbound prototype rom. It happens horizontally for the former and vertically for the later. As the environment scrolls, the edges of the screen display jumbled tiles and colours. See the two videos in the attached archive to see what I mean.

I am running the latest OpenEmu (2.0.1) on El Captain 10.11.3. This happens for both NES cores (Nestopia 1.42.5 & FCEU 2.2.2).

[tearing-examples.zip](https://github.com/OpenEmu/OpenEmu/files/171078/tearing-examples.zip)

**Comment by clobber** [comment]
Um, that is just the way the games were on real hardware.

**Comment by Phalaric** [comment]
Sorry I was mistaken about Super Mario Bros. 3. This is in fact an issue with Earthbound though. If you look at the following walkthrough video: https://www.youtube.com/watch?v=HKJiTIQ7_os, you will see that that is not how the game ran on hardware. I ran the game on the Windows version of FCEUX and can confirm that this issue is specific to OpenEmu. I jumped to the wrong conclusion about Super Mario.

**Comment by clobber** [comment]
No, there is no issue specific to OpenEmu. We use the same emulator cores the Windows port use, without modifications.

Whatever you are seeing with the **prototype** version of the game is how it would be running on real hardware.

**Comment by Phalaric** [comment]
I'm aware of this, however if you were to run the rom on FCEUX as I have you would not experience this.

We should not get caught up on the word prototype here. The official English version of Mother (How Earthbound is known in Japan) was never released in the US. The so-called prototype rom of the English translation was eventually leaked on the Internet. So any time you see Earthbound being played on NES (i.e. that playthrough video), you are seeing the prototype rom. There is no such thing as an official rom of Earthbound.

Actually, this is the same rom that was released by Nintendo on the Wii U VC as Earthbound Beginnings and the tearing doesn't occur there either.

**Comment by Phalaric** [comment]
Also ran it on FCE Ultra GX on Wii, which is also based on the same core, and no tearing.

**Comment by clobber** [comment]
One has to have played these games on real hardware before to understand what is happening.

The Windows and GX ports are all cropping the vertical overscan area by default. Play this game on real hardware, on the right CRT television, and you will see the scrolling "glitch" at the top and bottom of the screens, which is the result of a NES PPU hardware limitation and the game's routine for vertically scrolling the screen. You can adjust the overscan area settings in all the ports to see this behavior. Now, how overscan area was cropped is highly subjective and varied from television to television - it is nothing to do with the NES console itself.

As for the OpenEmu NES core ports, we display the entire contents of the framebuffer by default (https://github.com/OpenEmu/Nestopia-Core/blob/master/NESGameCore.mm#L710-L718), which is why you are noticing this. There is no way to "crop" for overscan short of editing the code in the implementation and recompiling. Perhaps an "advanced core preferences" feature for the future.

**Comment by Phalaric** [comment]
I see what you mean now. Thank you for the clarification. I agree that displaying the entire framebuffer is probably best.

**Comment by clobber** [comment]
Sure, depending on the game there can be a loss of detail, though programmers knew that they could sometimes pull off tricks and count on the television hiding glitches in the overscan area.

![overscan](https://cloud.githubusercontent.com/assets/1303132/13731491/18bc71d8-e938-11e5-8b99-f29aa1008934.jpg)

**Comment by Phalaric** [comment]
I guess letting the user adjust the overscan as you mentioned would be a good solution. Although that might go against the "it just works" philosophy. What about preset game overscan settings stored in a database? Do you think that would be a pain in terms of maintainability?

**Comment by ayancey** [comment]
@Phalaric The "it just works" philosophy is nice and all, but when it gets in the way of an option like overscan, where it really **doesn't** "just work" at all, and might require some tweaking for the user to have it the way they like.

**Comment by clobber** [comment]
A difference in taste on how much to crop a screen doesn't mean that OpenEmu's "Just Works" philosophy has failed. As mentioned, how much a CRT would crop a screen differed by manufacturer and even region. All that console game programmers could count on was what they conservatively estimated as the "title safe area" which was the area of the screen that could fit most of their content without getting cut off by the TV. There is still content outside the "safe" zone and it doesn't make sense to cut it all off this day and age - just show the whole picture!

@Phalaric Sure, a database approach is best for games that are affected by a background scrolling/mirroring glitch (likely small number). At most one needs to crop off the top 8 and bottom 8 lines.

We prefer to keep things as tweak-free and optionless as possible, so that is the way to go.

**Comment by clobber** [comment]
Options to crop overscan for NES is now available in OpenEmu 2.0.8.
