### ISSUE TITLE
Desmume need advanced bus-level timing and DEBUG BUILD message

### ISSUE THREAD

**Issue by dani0025** [OpenEmu/OpenEmu#2480]
When I play Mario and Luigi Bowser´s Inside Story, the game freezes on a random battle, no matter what i do, the game will freeze every time i enter that battle.

Is bus-level timing there?, can i enable it?, how?

Also, in some games that i play, it appears:
"NAME OF THE GAME"(DEBUG BUILD), and it causes many lag

**Comment by mrvacbob** [comment]
Did you build from Xcode?

**Comment by clobber** [comment]
Heh, yeah that's a debug build.

@dani0025 You don't need to compile OpenEmu or Desmume from source (which you have done incorrectly, btw) since we already include the core port with the app. Download from www.openemu.org

As for advanced core options: no, that is not available. Use Desmume standalone app if there is a problem.
