### ISSUE TITLE
Cant get roms into Openemu

### ISSUE THREAD

**Issue by Deakstre** [OpenEmu/OpenEmu#2486]
Here is what im dealing with. I get the downloaded GBA roms and when i double click them i get the second screenshot and when i use an archiver i get the first screenshot which cannot be dragged or played in openemu. What other options do i have since my other zip files seem to play without a problem?

![screen shot 2016-03-26 at 2 40 19 pm](https://cloud.githubusercontent.com/assets/18083097/14061831/17c6eab4-f361-11e5-9ff7-b715cf449fd7.png)

![screen shot 2016-03-26 at 2 39 53 pm](https://cloud.githubusercontent.com/assets/18083097/14061826/ee1d3c40-f360-11e5-9e6b-7e6a543a8fb9.png)

**Comment by clobber** [comment]
You don't need to open a new issue, you can simply reply in the old one in #2484

>PokemonGlazedBeta7b.ups

Uh...that is not a ROM. That is a ROM hack patch, so no wonder OpenEmu doesn't import it. You need a patching tool and the original ROM in order to use that. I suggest http://projects.sappharad.com/tools/multipatch.html
