### ISSUE TITLE
Multidisc saved state

### ISSUE THREAD

**Issue by mushu8** [OpenEmu/OpenEmu#2489]
Hi,
i run into the problem of starting a disc 1 game and when it asks disc2, the emulator cannot charge my saved states from disc1.
I created a new file .cue with the list of file for my 4 discs.
This file is recognized in OpenEmu but still cannot see the saved states from disc 1.

How can i "convert" saved states from disc1 to the new file i created for the 4 discs please ?

**Comment by mushu8** [comment]
i tried to rename some files in the /Users/alexandresagette/Library/Application Support/OpenEmu/Mednafen/Battery Saves folder (only hash or full file name) but it doesn't whange annything…

**Comment by clobber** [comment]
You cannot get access to other save states this way when you have a multi-disc game. You have to start with an .m3u file from the very beginning.

**Comment by mushu8** [comment]
so my saved game is lost ?
There is no way i can use it ?
It would be so frustrating…

**Comment by PlutoX86** [comment]
Nah, don't give up. Once you saved with your *.m3u game, OE creates a virtual memory card for it. It's going to be saved in the "battery saves" folder. 

For example, i completed "tekken3.cue" and had access to the 'theatre mode', which lets you watch any cutscene, including the ones from t1 and t2, IF you insert the respective discs. So i decided to make a "t3+t2+t1.m3u" with all 3 games included. 

All i had to do is to rename my old "tekken3.cue" save file to the newly made  "t3+t2+t1.m3u" save file.. and voila.

Loaded it up and had access to my progress, costumes and theatre mode, including the new discs to switch to in order to watch the old crappy animated cutscenes. :D

**Comment by mushu8** [comment]
my **Final Fantasy 9.m3u** file :
```
Final Fantasy 9 CD1.cue
Final Fantasy 9 CD2.cue
Final Fantasy 9 CD3.cue
Final Fantasy 9 CD4.cue
```
in the _~/Library/Application Support/OpenEmu/Mednafen/Battery Saves_ folder :

- Final Fantasy 9 CD1.614fe52271c87a683c7eef65125349d2.0.mcr
- Final Fantasy 9 CD1.614fe52271c87a683c7eef65125349d2.1.mcr
- Final Fantasy 9.8f7ad91c92b7be45696da65db7c3ada6.0.mcr
- Final Fantasy 9.8f7ad91c92b7be45696da65db7c3ada6.1.mcr

in the _~/OpenEmu/Game\ Library/roms/Sony\ PlayStation_ folder :
- Final Fantasy 9 CD1.cue
- Final Fantasy 9 CD2.cue
- Final Fantasy 9 CD3.cue
- Final Fantasy 9 CD4.cue
- Final Fantasy 9.m3u

**Comment by mushu8** [comment]
@PlutoX86 
i renamed the _Final Fantasy 9 CD1.cue_ file as _Final Fantasy 9.m3u_ but it doesn't work

**Comment by PlutoX86** [comment]
Really? "Final Fantasy 9.8f7ad91c92b7be45696da65db7c3ada6.0.mcr" is now "Final Fantasy 9 "CD1.614fe52271c87a683c7eef65125349d2.0.mcr" and it still doesn't load the original save game?

Hmm, then i'm sorry for you. =/

**Comment by mushu8** [comment]
nope, i've just tried that. it doesn't work

**Comment by PlutoX86** [comment]
(Are you sure you don't use OpenEmus own save system too? Because when you load an OE savestate, it overrides any 'normal' PSone memory card (which we're talking about!). In my case i only use the regular PSone save state system)

**Comment by mushu8** [comment]
i had some saved files in my Saved State folder. deleted them.
try again but nope still not working

**Comment by mushu8** [comment]
each time i try, two files are created in the Battery Saves folder :
- Final Fantasy 9.8f7ad91c92b7be45696da65db7c3ada6.0.mcr
- Final Fantasy 9.8f7ad91c92b7be45696da65db7c3ada6.1.mcr

**Comment by PlutoX86** [comment]
IF the save is still there, just name the "memory card" you want to use: "Final Fantasy 9.8f7ad91c92b7be45696da65db7c3ada6.0.mcr".

**Comment by mushu8** [comment]
yes it works !!
thanks ;-) have nice week-end

**Comment by davidalexandertan** [comment]
@PlutoX86 Hi pal, my situation's pretty similar.. I've played FF8 DISC 1 and it required me to switch discs and so googled and found the way to merge all the files together to form the .m3u file, in which:

1) FF8.m3u
2)Final Fantasy VIII (USA) (Disc 1).cue

Battery Saves:
1) FF8.5dd5b35b0f8b1e5512398aa668be894c.0.mcr
2) Final Fantasy VIII (USA) (Disc 1).9ccc2eae0d49842699a383c15af9eff3.0.mcr

How do I rename FF8.5dd5b35b0f8b1e5512398aa668be894c.0.mcr to Final Fantasy VIII (USA) (Disc 1).9ccc2eae0d49842699a383c15af9eff3.0.mcr? Does it actually work? Coz i've been trying but it doesn't allow me to rename over the same files.. Please do give me a hand here :(

**Comment by clobber** [comment]
@davidalexandertan Really not the best place for this since it's not an OpenEmu issue (one should be using .m3u files for multi-disc game from the start, as the [guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) states). Try the subreddit which has dozens of these same threads opened: https://www.reddit.com/r/openemu
