### ISSUE TITLE
Open emu won't run any roms or quit

### ISSUE THREAD

**Issue by sparkes3000** [OpenEmu/OpenEmu#2511]
Hi

Have installed Experimental version of open emu and an unarchiver app as per recommends. However can't seem to run any roms (only have 2). Just get a black screen and then unable to close program so have to switch off using power button.
Roms only appear in 'recently added' menu of Open Emu. I have manually put the rom zip files into the game library folder location of 'Library/Application Support/OpenEmu/Game Library'

I'm not by any means computer savvy!

Any help would be great.

cheers

**Comment by clobber** [comment]
Need to be specific. Which games and version of OpenEmu?

**Comment by sparkes3000** [comment]
Hi

It's the latest version of open emu as I have only just downloaded it. 
The two rooms I tried were ghouls n ghosts and sega rally.

**Comment by clobber** [comment]
Okay, sounds to me you are trying to run Arcade games.

MAME is tricky, which is why the core port is still in the 'experimental' cores bundle and not officially supported. One needs to be using games from a MAME 0.149 ROM set as well as whatever required parent/bios/system file ROMs the game may need. Some games, even though they are included in a MAME ROM set, don't actually run at all. Best I can do is like you to a guide that may or may not be helpful: http://agreeordie.com/how-to-emulate-retro-video-games/
