### ISSUE TITLE
Black screen with many popular .cgp shaders

### ISSUE THREAD

**Issue by HalSamuel** [OpenEmu/OpenEmu#2516]
I've been playing around with custom shaders in OpenEmu, with mixed success. Some appear to load properly, but I'd say a majority of the shaders I've been using (mostly popular shaders from the Libretro GitHub collection) cause a black screen while the emulator continues to run.

It's frustrating as OpenEmu is far and away the nicest emulator I've ever used, but some of these shaders are also a labour of love, and it would be an awful shame not to have them available.

Any idea what the problem might be?

Thanks for your help.

**Comment by clobber** [comment]
Nvidia deprecated their Cg framework a long time ago and support for Cg shaders will go away in a future version of OpenEmu. That said, not all of the multipass shaders that work in their frontend will work in ours, mostly because theirs is a evolving spec in which they've kept adding features to it.
