### ISSUE TITLE
Glitchy controller wii u pro

### ISSUE THREAD

**Issue by mike0128012** [OpenEmu/OpenEmu#2520]
I have no trouble pairing wii u pro controller and it works but periodically it will lock up or character will move on its own and i must wait for it to work again i have followed instructions and i do not have wjoy or anything else im wondering if this is just the way wireless controllers are working or is it just me

**Comment by clobber** [comment]
Sorry, a quick glance at past issues doesn't show anyone else with this issue. Given that it is a wireless device that is unofficially supported on OS X, it could be any number of things, including brief disconnects due to signal interference. Closing until others happen to have the same problem - they can chime in on this issue and take a look.
