### ISSUE TITLE
Revisit OEGameCoreRewindBufferSeconds in some core plugins

### ISSUE THREAD

**Issue by clobber** [OpenEmu/OpenEmu#2553]
cc: @kylewlacy on this.

Some cores (SNES9x) end up using more memory than we want with a default buffer length of 20 minutes, so we probably want that down to a more reasonable 1-5 minutes. In theory a long rewind buffer is nice but we also record every frame by default and this quickly balloons up mem in OpenEmuHelperApp. All options are easily configurable though.

A user reported 6GB use after 20 mins with SNES9x, but might be a nasty mem leak lurking.

**Comment by kylewlacy** [comment]
Honestly, I kind of doubt if that 6 GB peak was caused by a memory leak. I just double-checked too by running S9x in Instruments with a shorter rewind buffer, and memory use levels out once the rewind buffer is full (since older states start getting freed).

For the most part, I tuned the `OEGameCoreRewindBufferSeconds` by running a game for a bit to figure out roughly how many MB/s each core eats up. Of course, that's a really imprecise way to figure out actual peak memory use, so I'm not surprised there's games that use 3 GB+. Short term, I think reducing the rewind buffer to 5 minutes is fine (back-of-the-napkin: 6 GB / 20 min = 307 MB / min; 307 MB / min * 5 minutes ~= 1.5 GB peak).

Longer term, I wonder if it would be better to limit the rewind buffer to a certain size (e.g. 1 GB max, then start dropping states). This could also be based on how much memory the user has (maybe no more than 50% total memory, or no more than 80% of free memory, etc.). Also, this could go hand-in-hand with a new feature I've been thinking about: saving rewind states to disk (which I imagine would then be limited to a certain number of frames). I think this would be the best of both worlds: lots of rewind time, and a lower memory footprint (and the added advantage that you can rewind past the point when you last closed your game).

(Side note: I've also been thinking about refactoring the rewinding code. Like I mentioned on IRC a few months ago, I also started some work on Netplay, which would rely on de/serialization of both save states and console inputs. Adding input de/serialization ended up being much trickier than I thought, and I believe that it would make things a lot simpler if both things were handled outside of `OEGameCore`)

**Comment by clobber** [comment]
Pushing core updates alongside OE 2.0.2 with shortened rewind buffers.
