### ISSUE TITLE
"Couldn't communicate with helper application"

### ISSUE THREAD

**Issue by MonitorX** [OpenEmu/OpenEmu#2554]
I've been having some trouble launching MAME ROMs in OpenEmu, as this message comes up whenever I try. This only happens during arcade games, and I'm unsure exactly what to do. I did some poking around and saw some other people were having similar issues, but I tried all of the solutions and it is still showing the message. I deleted and redownloaded the cores, redownloaded the software, tried multiple fresh ROMs, and it's still showing up. Can anyone help?

I would have posted an error log or something, but I am not sure where exactly to find that or what I would need to post specifically.

**Comment by clobber** [comment]
MAME is tricky, which is why the core port is still in the 'experimental' cores bundle and not officially supported. One needs to be using games from a MAME 0.149 ROM set as well as whatever required parent/bios/system file ROMs the game may need. Some games, even though they are included in a MAME ROM set, don't actually run at all. Best I can do is like you to a guide that may or may not be helpful: http://agreeordie.com/how-to-emulate-retro-video-games/

**Comment by MonitorX** [comment]
Alright, thanks, I'll look into that. The weird part is that I had no trouble running these ROMs before on this computer using OpenEmu, and had the exact same setup working perfectly on another computer. Not sure what changed or why the helper app isn't communicating right. I'll read the guide and hopefully it'll give me some tips.

**Comment by MonitorX** [comment]
Okay, I managed to resolve the issue by using Time Machine to restore older versions of the cores and games are now running again. The message had also been showing up for Genesis, PSP, and Turbografx games, but all of them are now working again. Weird.

**Comment by clobber** [comment]
Sounds like you are using OpenEmu 1.x and had downloaded the new cores which require 2.0. Really best to upgrade OS X at this point.

**Comment by MonitorX** [comment]
That's probably why. Might be best to upgrade, then.
