### ISSUE TITLE
MAME ROMs

### ISSUE THREAD

**Issue by grayskyclouds** [OpenEmu/OpenEmu#2559]
I've tried 'drag' & 'drop' a few MAME roms (i.e. NeoGeo, Metal Slug 6 and etc) but the "Fix Import Issues" always comes up - when I select all the paths, the drop down lists on the top right do not have the option of 'Arcade'. 

Is there something wrong?

I downloaded the experimental version OpenEmu and have enabled and installed the core for Arcade and Sega Saturn.

**Comment by clobber** [comment]
MAME is tricky, which is why the core port is still in the 'experimental' cores bundle and not officially supported. One needs to be using games from a MAME 0.149 ROM set as well as whatever required parent/bios/system file ROMs the game may need. Some games, even though they are included in a MAME ROM set, don't actually run at all. Best I can do is like you to a guide that may or may not be helpful: http://agreeordie.com/how-to-emulate-retro-video-games/

Also, please search previous issues next time. And, Metal Slug 6 is *not* going to run - it's not Neo Geo, it's Atomiswave and not supported or emulated by MAME.

**Comment by grayskyclouds** [comment]
I did, previously tried using games from a MAME 0.149 ROM set and also followed the instructions closely of the BIOS given based on the guide previously and have encountered the exact same problem as with #2245 - with each drop returning a "Fix Import Issues" screen. 

For example, I was trying to install the first two BIOS in the guide (e.g. 22vp931 & bsmt2000), and here's a screen grab;
![screen shot 2016-05-23 at 11 01 27 am](https://cloud.githubusercontent.com/assets/19513652/15459257/1079e8cc-20d6-11e6-8028-27593649841b.png)

I also tried installing a ROM from MAME 0.149, and here's a screen grab;
![screen shot 2016-05-23 at 11 01 52 am](https://cloud.githubusercontent.com/assets/19513652/15459275/2f7c5f7a-20d6-11e6-9690-29d50ee02839.png)

I've been searching for similar issues but was hoping if someone can guide me in the right direction?
