### ISSUE TITLE
MAME Giving Me Trouble.

### ISSUE THREAD

**Issue by PY23** [OpenEmu/OpenEmu#2615]
Hello, I'm having trouble with arcade games playing. Whenever I download the rom and start it, it will play but once I close it and than try to play again it it only shows a black screen and has to be forced quit. 

MacBook Pro: OSX 10.11.5

Openemu: 535-gc11c17e-Release

**Comment by clobber** [comment]
Arcade/MAME is unsupported because it is 'experimental'

That said, some Arcade games/systems in MAME don't save states properly, and aren't really supported - so don't restore an autosave if you are using them.

**Comment by ylluminate** [comment]
@clobber what can we do to help this to work as far as the state saves / restores go?  I'd like to try to get my hands around this to figure out what the real core problem here is...

**Comment by fgimian** [comment]
Thanks @clobber.  Resume did work correctly in v2.0.1 however.  Perhaps it is possible to go back to that implementation of resume for MAME?

Almost all arcade games I tried in v2.0.1 would resume perfectly.  But in v2.0.2+, none of them work sadly.

Cheers
Fotis

**Comment by ylluminate** [comment]
@fgimian he is very adamant about not using MAME games in any reliable fashion within OpenEMU.  It's a real shame and heart breaker, but that's the sad truth of the matter at the moment.  I think we'd all love to see first class MAME support in OpenEMU, but... I guess someone else will have to take up that torch.

**Comment by dgrcode** [comment]
Would it be possible to add a feature that allows the user to "Continue where you left off" with all consoles but not with MAME?

I would be happy to add it, but I have no idea how to create that feature. Can you guide me with that so I can work on it? (files needed to be changed for example)

**Comment by maddenpj** [comment]
@ylluminate 
> he is very adamant about not using MAME games in any reliable fashion within OpenEMU. It's a real shame and heart breaker, but that's the sad truth of the matter at the moment. I think we'd all love to see first class MAME support in OpenEMU, but... I guess someone else will have to take up that torch.

Then why is MAME even included? Why include something you refuse to support?

**Comment by clobber** [comment]
https://github.com/OpenEmu/UME-Core/commit/999565397d3fb867e68a958a7e468aa59059d168

This is fixed now.

Restart the app and an updated MAME core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for MAME 0.149.3

Note: The usual still applies as per the [Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](http://choccyhobnob.com/articles/demystifying-mame-roms/)."
