### ISSUE TITLE
DS Codes not working on Open Emu

### ISSUE THREAD

**Issue by Adambennett44** [OpenEmu/OpenEmu#2624]
Ive tried 2 ways,
94000130 FFBB0000
62101140 00000000
B2101140 00000000
00000090 000F423F
D2000000 00000000
and
94000130 FFBB0000+62101140 00000000+B2101140 00000000+00000090 000F423F+D2000000 00000000
neither are working. am I doing it right?

**Comment by clobber** [comment]
Action Replay codes for NDS can be inputted just about any way: https://github.com/OpenEmu/OpenEmu/issues/1121#issuecomment-33430587

You have to be sure that the codes you are using are for the proper region. Since there are different versions of the game for various locales, there are also different codes that have to be used. For example: Action Replay codes for the US version of the game wouldn't work for an EU version of the game. Also verify on standalone Desmume just to be sure it's not a problem on our end, but shouldn't be.

Here is our wiki guide on using cheats:
https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Cheat-codes
and here is a good resource for cheats:
http://gamehacking.org
