### ISSUE TITLE
[Feature] Create m3u in app.

### ISSUE THREAD

**Issue by Socapex** [OpenEmu/OpenEmu#2650]
Multi-disc is tedious and not very elegant (3 files for a 2 disc game, correct one without art).

Feature request:
- Drag multiple cue game.
- Select roms in library, right-click, create multi-disc.
- OpenEmu generates .m3u file for you, removes the individual disk previews from library and sets the m3u file artwork and name according the the CD1 hash.

Thx

**Comment by Socapex** [comment]
I'd like to know if you want this or not. I might write it myself, but I wouldn't want to spend all the time and pain to get the project building/understanding your codebase if you don't want this.

Ty

**Comment by 3ntrax** [comment]
i think indeed this would be a nice feature cause its true it's a bit of a hazzel right now

**Comment by Socapex** [comment]
Agreed. I'm more of a c++ guy myself, but I think this is a sweet simple feature to get me going with your project. Do you have an irc channel for the (unavoidable) questions I'll have?

**Comment by 3ntrax** [comment]
you should wait until some of the dev's respond cause i'm only a user of this emu

**Comment by clobber** [comment]
The feature you are describing is much more complicated to implement than you think it is, especially because of our import system and game library data store and the modular design of the app/core plugin relationship . There are also a bunch of cases that allow room for error and make it more complex:

What if the user selects the wrong games and creates an m3u?

What if the user needs to add more games to the m3u?

What if the user needs to remove a game added from the m3u?

How do we ensure the user added all the games to the m3u in the correct order? Games aren't always labeled properly.

What if the user expects their mem card save to automatically be converted over for the m3u?

...and so on.

Although creating an m3u file could be tedious, it helps cut down on the number of possible issues of trying to semi-automate the process that I don't care to support. For these reasons, I don't wish to implement a feature like this. I will instead add a step in the core plugin itself that checks if a user is trying load a known multi-disc game without using an m3u file, and deny loading the game and send them to the guide.
