### ISSUE TITLE
Visual Boy Advance Freezing

### ISSUE THREAD

**Issue by jdavi3** [OpenEmu/OpenEmu#2659]
I am playing pokemon on the openemu emulator and it is freezing constantly. I have tried everything i know to do and nothing is working

**Comment by clobber** [comment]
Which version of OpenEmu?

**Comment by jdavi3** [comment]
2.0.2

**Comment by clobber** [comment]
What exactly is freezing? During what? Which Pokemon game? Which gamepad are you using, if any? Is there any output in Console?

**Comment by jdavi3** [comment]
The game freezes. Its like i can play for like 1 minute or so and then everything stops working. I am using the ruby Rom and no game pad and no output

**Comment by clobber** [comment]
Okay, try using mGBA to emulate the game instead. VisualBoyAdvance isn't very accurate, has issues and we've since made mGBA our default GBA core plugin.

To switch: while running the game, click the cog wheel icon on the HUD bar, choose Core > mGBA.

Let me know how that works out.

**Comment by jdavi3** [comment]
is there a way to move over a save data

**Comment by jdavi3** [comment]
It does the same thing... Its like the controls just stop working... the game keeps going

**Comment by clobber** [comment]
That doesn't sound like the same thing. One was the game freezing, the other is the controls aren't working. Controls not working usually means another application is interfering with input, so close other running applications until you find the one.

**Comment by jdavi3** [comment]
I have close every application i had up and same thing

**Comment by clobber** [comment]
Doesn't sound like we can help you then. If you are using something like a DualShock 4, that is currently causing issues with input so unplug it.

Otherwise, try a restart of your machine and after don't launch any other applications (including web browsers) besides OpenEmu.

Input not working usually means another app is interfering with input (like google chrome, some third party input apps or a terminal, etc). Close apps until you find the problem. Reboot your machine and don't open anything but OpenEmu.
