### ISSUE TITLE
Strange cheat happenings

### ISSUE THREAD

**Issue by lede1243** [OpenEmu/OpenEmu#2662]
Okay, so I figured out why my cheats weren't working before, but I have an even weirder problem now.  Refering back to my my previous problem, I seem to have a lingering "walk through walls" glitch that stays in my Ocarina of Time's memory, even with me shutting down openemu, restarting, etc. It seemed to have glitched out a specific save state (I saved when I went through the gate to get the boss key to the water temple), where I can't turn it off, and it doesn't appear in my list of cheats (it was empty). I now implemented a speed glitch to get through the water temple's gate to the boss key in Ocarina of time, to find that just by going through the gate, I activate the glitched cheat. It is unrelated to what save state i'm in. If I go through the gate, I start walking through walls. I can turn the speed cheat on and off, it is irrelevant. But every time I walk through the gate, I suddenly have the ability to walk through walls. I originally implemented these cheats so that I could get through that gate (circumstances made it physically impossible), and I need this cheat out of my system's memory, or a way around it. Any help would be greatly appreciated.

**Comment by clobber** [comment]
Sorry, there is absolutely no way to help in these cases. You should have deactivated the cheat when you were done using it the very first time before you closed the game.

It's either resident in memory of your save states or there is an emulator glitch -- both of which we can't fix.

I'd suggest loading your saved game from the in-game memory instead of restoring an autosave or save state, to ensure no cheats are active in memory.

To do this:
* In-game, go to the Zelda sub menu and save your game
* Close your game
* Go to OpenEmu > Preferences > Library and click "Reset warnings"
* Open Zelda and when it prompts you to "Continue where you left off" click "No"
* Load your in-game save and **don't** use any of your old save states. Delete them.

Aside from all of this, buy a gamepad with analog sticks.
