### ISSUE TITLE
Lost Higan GBA core ? 

### ISSUE THREAD

**Issue by Yohmi** [OpenEmu/OpenEmu#2680]
Hello,

I remember I used to play my GBA roms with Higan, because I try to always stick to the highest accuracy possible (and it's especially relevant for Mother 3), but I noticed it's been a few versions I can't access to Higan core for GBA, it seems to be exclusively for the SNES core now. 
I can't find any mention about this in the changelogs, so I'm wondering if there's anything wrong with my copy of OpenEmu 2.0.2 (535-gc11c17e). I saw there's been mGBA added to the lot, which seems to be a great improvement over VBA, but as far as I can tell, my recent sessions of Mother 3 were terrible, which might be because of an infinitesimal lack of accuracy of the emulation's clock (or my fingers). Besides, I can't load my old saves…
Hopefully there's a trick somewhere to get Higan 0.95 back for GBA (and we can expect sometime in the future a working macOS binary for 10x version :D).

Thank you :)

**Comment by clobber** [comment]
In an old version of OpenEmu, Higan was included with GBA support by mistake. It never should have been due to it's Work In Progress status. It will not be included again due to changes with other core modules in later versions of Higan.

mGBA is what you want to use. It's actively developed and more accurate that the others out there, including the version in Higan you once used (which was quite old and unfinished at the time).

If you want to transfer save files and use the new mGBA core plugin, you should be able to figure out it from this guide: https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files
