### ISSUE TITLE
Video(Performance) lag

### ISSUE THREAD

**Issue by jcgamer60** [OpenEmu/OpenEmu#2685]
First off, I want to say how much I love Openemu and it's interface, but as of recent performance seems to have taken a hit.

Pretty much all emulators lag a bit from time to time. No audio lag, just on-screen video lag. I have tried with every filter yet to no avail. I'm assuming it is due to the new releases? Performance was fine, for the most part, before.

I have tested out NES and SNES on standalone emulators and I did not encounter this performance issue.

Feel free to ask any further questions. I am willing to pay a donation as well if it will help towards this cause.

Specs:
Macbook late 2011
Intel HD Graphics 3000 512 MB

**Comment by clobber** [comment]
>Performance was fine, for the most part, before.

There wasn't a change in OpenEmu v2 (or any point release thereafter) that should have negatively impacted video performance. Do you have any programs running such as f.lux and/or have you tried setting the filter in OpenEmu to Nearest Neighbor?

The GPU in your machine (Intel HD 3000) can't handle all of the filters/shaders, so best to stick with Nearest Neighbor or Pixellate.

**Comment by Zrkhyfs** [comment]
I have OpenEmu installed on my MacBook Pro 2011 since 2016, everything worked fine even within macOS Sierra v10.12.5, but for some unknown reason, now it doesn't, I reinstalled to the latest version but I still experiencing this video and audio lag as it is shown [here](https://www.youtube.com/watch?v=EAFKn3tZysE&feature=youtu.be&t=17), specifically, with the n64 core, the rest of my console games are working good.
I tried to remove all OpenEmu related files, reinstall all cores again, updating image filters, but none of these worked.

**Comment by clobber** [comment]
@Zrkhyfs This is not the same problem. See #3447

**Comment by clobber** [comment]
This should be resolved as of OpenEmu 2.1
