### ISSUE TITLE
Sound lag while running PSP games on PPSSPP core

### ISSUE THREAD

**Issue by Koznoz** [OpenEmu/OpenEmu#2696]
Although I've only run PSP games on OpenEmu, I seem to have encountered an issue exactly resembling this (https://www.youtube.com/watch?v=EAFKn3tZysE). The game also stutters as well and concedes with the lagging sound, rendering it unplayable. Please help? Thank you in advance!

**Comment by clobber** [comment]
As long as you are using OpenEmu v2, that issue you reference doesn't have anything to do with it -- that was related to a specific GPU problem in OpenEmu 1.x.

Possible scenarios:

* PPSSPP's emulation is imperfect and you are experiencing a glitch in a certain game (which is why we also have a glitch warning and ask you not to report those issues).
* You using a shader/filter other than Nearest Neighbor or Pixellate that your GPU cannot handle.
* You are running a game that your CPU cannot handle. Some games require more power than others. The GTA series comes to mind.

**Comment by clobber** [comment]
#1036
