### ISSUE TITLE
Entering text into Spotlight Search also triggers the assigned buttons

### ISSUE THREAD

**Issue by bjorrn** [OpenEmu/OpenEmu#2716]
Hey,
I hope this is really just a bug and it's somehow fixable.
When I open the Spotlight Search via cmd+Space while OpenEmu is active and I type, the respective buttons are "pressed".
Example: I assigned the key "7" to be "reload save state" and I try to search via Spotlight for something that contains the number 7, the game reloads my last save state…
Same works for any other key of course
:)

**Comment by clobber** [comment]
Yes, this is a bug and thanks for reporting!

So when a game is running, we watch the keyboard directly in a background process -- and not handling keyboard events through Cocoa, but through IOKit. Normally with Spotlight when an application is the frontmost, everything works as expected (as ours does when a game is not running) but because of our special setup when the game is running, we cannot tell when Spotlight is visible to intercept the events.

Since there is not yet an official method, we cleverly worked around this problem in commit https://github.com/OpenEmu/OpenEmu/commit/57512c81812f9bbff7867a40f37912525c635d11 so it's fixed for next release.
