### ISSUE TITLE
loud Crackling/popping in VBA core for Beyblade V-Force

### ISSUE THREAD

**Issue by hullstar242** [OpenEmu/OpenEmu#2743]
Core: VBA 
Rig: MacBook Pro 13in Retina 2015
OS: OS X El Capitan
Version: 2.0.3
Any other info you need?  I went to the games sound options and turned all the sound off and the crackling in the game remains at the same volume meaning it isn't directly connected to the game audio.  is it just a bad rom do you think?

**Comment by clobber** [comment]
>Core: VBA 

VisualBoyAdvance is lousy in terms of accuracy, which is why we switched to mGBA as the default GBA core plugin in OpenEmu 2.0.2.

Follow this guide which will show you how to set mGBA as your default as well as transfer over your save file. https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files

**Comment by hullstar242** [comment]
i changed to mGBA and the crackling is still happening :( I'm going to try and download a different rom of the same game

**Comment by hullstar242** [comment]
what makes VBA lousy? i never noticed a difference and i kinda want to know if i should do the save file transfer thanks ! :)

**Comment by hullstar242** [comment]
Tried the rom from a different source and it is still occurring.  bummer :( it could be just the game.

**Comment by clobber** [comment]
Yes you should do the save file transfer, and be playing all of your GBA games with mGBA instead of VisualBoyAdvance.

mGBA is an actively-developed GBA emulator with a focus on accuracy. It has improved speed, audio and compatibility versus that of the now ancient VisualBoyAdvance. It's better GBA emulation all around.

Btw, I can replicate that audio clicking issue in both emulator core plugins. It's not an OpenEmu problem (remember, we don't develop the emulators) but it could either be an emulation bug or the way it was on real hardware. Unless someone can run the game on real hardware to verify, we don't know for sure.

**Comment by clobber** [comment]
Dupe #2626
