### ISSUE TITLE
Save file transferring for Soul Silver 

### ISSUE THREAD

**Issue by soulsilverquestion** [OpenEmu/OpenEmu#2744]
Hello,

I started a game of soul silver a few days ago, but I realized that I wanted to have some pokemon that required trading to evolve (Kingdra specifically). So I googled my problem and used the "Universal Pokemon Randomizer" to fix the evolution problem. It created a new ROM, and all that'd be left to do is transfer my on going save into that new ROM of Soul Silver where there are new rules for trade specific evolutions. Is there any way to do that? I'm just hoping to transfer a save from one ROM to another within OpenEmu on just one computer, but whenever I try to move the battery saves or anything from the old ROM to the new one, it just bounces right back to the old one. 

Thank you

**Comment by clobber** [comment]
Two things:
* The filename of your save needs to match the filename of your ROM file e.g. My Game.nds = My Game.dsv
* Launch OpenEmu, go to OpenEmu > Preferences > Library, click "Reset warnings" and when you launch your game click "No" when prompted to "Continue where you left off"

That should be enough, assuming you've done everything else correctly with your .dsv save file.

**Comment by soulsilverquestion** [comment]
Could you go into a little more detail on your first point? The save files aren't saved as .dsv but as .oesavestate

Should I change them to .dsv then?

**Comment by clobber** [comment]
.oesavestate is a save state, not a battery save (.dsv file). You mentioned "battery save" in your original post which led me to believe you know the difference.

If you used some kind of randomizer program, I doubt your previous save states or battery saves from another ROM will be compatible with the new.

Sorry, your issue is kind of outside the realm of standard OpenEmu-related stuff so I think this is all I can do for you.
