### ISSUE TITLE
it's important nds

### ISSUE THREAD

**Issue by gabro49** [OpenEmu/OpenEmu#2768]
i've saved a stories from pokemon Soul Silver but in last city from johto i want eliminate a attack from a pokemon and my screen became white and when i try open this save my screen is white.(i'm not speaking from the start screen)!!!!

**Comment by clobber** [comment]
Have to search because this comes up a lot.

In general, Desmume doesn't support Pokemon games very well - this is sometimes AP patch related. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility, or you can read up on AP patches.
