### ISSUE TITLE
Arcade 2 Player Problems

### ISSUE THREAD

**Issue by dperry23** [OpenEmu/OpenEmu#2770]
When playing arcade games, pressing the start button on the second player's controller enables "2UP."  However, when it's the second players turn to play, the controller does not work.  This does not happen in NES or Genesis.

I am using MacBook Pro with a Dualshock3 and Steelseries Stratus XL.

**Comment by clobber** [comment]
Arcade is still experimental, so unsupported right now but as far as I know multiplayer games should work okay. Could be a specific problem with that particular game.

**Comment by lordwookie** [comment]
i have a similar problem when i use 2 separate arcade sticks the 2up and the coin buttons work for player 2 but when its player 2's turn the player 1 controller takes over. I thought this was happening because the 2 single player xin-mo encoders have the same product id but when i put a cronusmax in front of player 2 to change the id I get the same result

**Comment by ladirection** [comment]
Hello,

I have the exact same issue. I plug two Logitech 310 on a Macbook pro (latest), I can "put in quarters" and press start but then nothing on player 2. Player 1 works fine. Both controllers are set to "D". Both work fine in SNES, Genesis or NES.

I tried X-Men 2 players, TMNT, Contra and Final Fight.

I'm running OpenEmu 2.0.6.1, Latest Mac OS and updates.

Thanks!
