### ISSUE TITLE
OpenEmu Experimental 2.0.3 doesn't work issue..

### ISSUE THREAD

**Issue by Iamcaobin** [OpenEmu/OpenEmu#2777]
Hey I'm new and I got few troubles while I run OpenEmu...

1 >> I dragged a PSX iso into OpenEmu but it doesn't add to the library.

2 >> I dragged an arcade game rom (MAME 0.164 ROMs) of groovef.zip into OpenEmu and it added already to the library but it's blank when I run it.

OpenEmu Experimental 2.0.3 on OS X EI Capitan 10.11.6 with complete Core and Systems. Thanks!

**Comment by clobber** [comment]
1. Follow the [CD Guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#importing).

2. You are likely missing stvbios.zip, now here is my standard spiel regarding MAME:

MAME is tricky, which is why the core port is still in the 'experimental' cores bundle and not officially supported. One needs to be using games from a MAME 0.149 ROM set as well as whatever required parent/bios/system file ROMs the game may need. Some games, even though they are included in a MAME ROM set, don't actually run at all. Best I can do is like you to a guide that may or may not be helpful: http://agreeordie.com/how-to-emulate-retro-video-games/

**Comment by Iamcaobin** [comment]
I dragged stvbios.zip into OpenEmu but arcade game still blank..
