### ISSUE TITLE
Failures and errors launching roms

### ISSUE THREAD

**Issue by OBPremier** [OpenEmu/OpenEmu#2784]
I downloaded OpenEmu in order to play MAMEs.  When I first installed all the necessary files I was playing merrily, no problems launching/opening the roms.  Then a few hours later, I experienced 1 or 2 ROMs going into some kind of service or software check mode, upon launch.  These screens I didn't know how to escape from in order to get to the gameplay.  

After this happened, my games are normally failing to launch at all.  Some of them launch, sometimes, but usually not.  And the ones that displayed the service and checking screens still do so, IF and WHEN they open at all.  

I actually have a Super Nintendo core and a few ROMs as well as the MAMEs, and when I tried launching the Super Nintendo ROMs it's the same problem: they fail to launch.  

I don't know if this is related necessarily to the service/checking screens or not, all I know is once that happened the ROMs started failing to launch.

The only way to launch any roms is to restart OpenEmu, and even that doesn't work most of the time.  I have to keep restarting, restarting, restarting, until something finally launches.  

Hope you can help me out.  Thank you!  I really like this software.

These are my specs:
MacBook Air (13-inch, Mid 2012)
Processor:  1.8 GHz Intel Core i5
Memory:  4 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 4000 1536 MB

**Comment by clobber** [comment]
MAME is tricky, which is why the core port is still in the 'experimental' cores bundle and not officially supported. One needs to be using games from a MAME 0.149 ROM set as well as whatever required parent/bios/system file ROMs the game may need. Some games, even though they are included in a MAME ROM set, don't actually run at all. Best I can do is like you to a guide that may or may not be helpful: http://agreeordie.com/how-to-emulate-retro-video-games/
