### ISSUE TITLE
Cannot Launch OpenEmu (previously working, very grateful for any help)

### ISSUE THREAD

**Issue by cosmicfetus** [OpenEmu/OpenEmu#2787]
Apologies since this is likely a horrendously noob mistake, but I appear to be stuck.  

Had been using OpenEmu  loving it, enough to buy a bluetooth nes style controller.  

Unfortunately that thing has been a pain to pair, and somewhere in that mess the OpenEmu program itself got messed up.  I tried to install a newer version and now no new versions will launch nor the older one i had previously.  

I simply get error message "The operation could not be completed. No other information is available about the problem"  Argh!  Massive bummer blocking battletoads action.

Any help would be much appreciated!

THANK YOU

**Comment by gingerbeardman** [comment]
Use [AppCleaner](https://freemacsoft.net/appcleaner/) to remove every trace of OpenEmu. 
Make sure to backup any files you want to move across to the new install (roms?)

Tick/checkmark all items it finds and trash them, then empty the trash. 
Do this for all OpenEmu apps on your system.

Then download a new OpenEmu, it should run OK.

**Comment by cosmicfetus** [comment]
THANK YOU so much!  You RULE! ;D 

Sprry for the caps, just want to show my appreciation ;D

Now to get this freaking 8bitdo NES30 controller to work ;)

Have a wonderful wknd gingerbeard!

**Comment by clobber** [comment]
While that might have fixed it, that method takes a sledgehammer to the problem. Without additional details, we can't address what was going on there as it could have been any number of issues.

Anyway, the 8Bitdo devices (which turned out to be pretty nice) will 'Just Work' on Mac. Get the [latest firmware](http://forum.8bitdo.com/thread-942-1-1.html) and use Mode 1/Joystick Mode by holding the START button to power on.
