### ISSUE TITLE
New Sony Dualshock 4 Wireless Adapter - L2 and R2 Buttons not working

### ISSUE THREAD

**Issue by J0JC** [OpenEmu/OpenEmu#2788]
When the standard Dualshock 4 is connected via the new Sony Dualshock 4 Wireless Adapter the buttons L2 and R2 are not recognized correctly in OpenEmu.

They get mapped as Rx+ and Ry-

When L2 and R2 are then pressed inside of a game (PS1 for example) they stay pressed and cannot be released which makes the controller unusable.

**Comment by clobber** [comment]
We might not be able to support that new adapter if it's doing something different from how OS X normally recognizes the DS4. I'd suggest just connecting the DS4 *without* the adapter, because you don't need it on Mac. It's really easy and Just Works: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-DualShock-Controller-Pairing#dualshock-4

**Comment by J0JC** [comment]
I am using the new adapter because I want to be able to play on my Macbook and my Mac Pro without the painful re-pairing. I just put the dongle into the Mac I want to use.

I think the current OpenEmu PS4 support might just need a small tweak.

**Comment by clobber** [comment]
I don't think it's painful to re-pair the device. As it currently stands now, we cannot support that wireless adapter but might look into it in the future.
