### ISSUE TITLE
games not loading

### ISSUE THREAD

**Issue by kanaanaman** [OpenEmu/OpenEmu#2796]

**Comment by kanaanaman** [comment]
OSX 10.11.6 el capitan and i have experimental version of openemu.  i have added all cores

**Comment by kanaanaman** [comment]
it appears some games work but very few and as soon as one that doesnt work is added to library then no games work,

**Comment by clobber** [comment]
You need to be specific; please provide examples.

**Comment by kanaanaman** [comment]
ok it looks like al sega mega drive and nintendo games works.  however if i add neo geo games when i try to launch one nothing happens, and then none of the games work at all that worked previously.

**Comment by kanaanaman** [comment]
same just happened with n64 game.  i could play famicom and megadrive games.  as soon as i launch n64 game that doesnt work whole system blocks up and no games will launch when i click on them

**Comment by clobber** [comment]
>however if i add neo geo games when i try to launch one nothing happens, and then none of the games work at all that worked previously.

MAME is tricky, which is why the core port is still in the 'experimental' cores bundle and not officially supported. One needs to be using games from a MAME 0.149 ROM set as well as whatever required parent/bios/system file ROMs the game may need. Some games, even though they are included in a MAME ROM set, don't actually run at all. Best I can do is like you to a guide that may or may not be helpful: http://agreeordie.com/how-to-emulate-retro-video-games/

There might also be an issue when a core fails to load a game and it doesn't shut down cleanly, which will we address in an update.

**Comment by kanaanaman** [comment]
Im following the instructions to add bios but openemu wont accept qsound zip which means i cant play capcom games

**Comment by clobber** [comment]
qsound.zip (left zipped, simply drag and drop the file) imports just fine with OpenEmu 2.0.3

Anyway, I can't help you out any further. The policy is that 'experimental' core ports such as MAME/Arcade are unsupported, so you are on your own here.

**Comment by kanaanaman** [comment]
yeah that method doesnt work for me on the same version...ok i understand its experimental.
