### ISSUE TITLE
Only one Wiimote can bind at a time in 2.0.3

### ISSUE THREAD

**Issue by pareidoliax** [OpenEmu/OpenEmu#2816]
I used to be able to use multiple Wiimotes for multiplayer. I use Wii u Pro controllers. After the last update OpenEmu will only link with one Wiimote at a time.

**Comment by clobber** [comment]
I can't replicate a problem pairing two Wiimotes, and the code was unchanged since the last update, but maybe the Wii U Pro is a little more fickle to pair. Try these guides to see if anything applies:

* https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing
* https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
