### ISSUE TITLE
Controls not responsive on macOS Sierra (10.12)

### ISSUE THREAD

**Issue by GiveMeAnthony** [OpenEmu/OpenEmu#2817]
I've updated to macOS Sierra and now the keys don't work within a game or on the Controls Preferences screen. However, they do work in the OpenEmu search box. Also, clicking on the virtual touch screen works just fine for the Nintendo DS.

**Comment by clobber** [comment]
Check here: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by GiveMeAnthony** [comment]
It turns out that Karabiner Elements was the issue. Karabiner never had a problem with OpenEmu, but it stopped working with macOS Sierra. The vendor advised to use their alternate project, Karabiner Elements, until it became merged with Karabiner.

**Comment by revolter** [comment]
Can't it be solved instead of specifying it in the Wiki?

**Comment by GiveMeAnthony** [comment]
@revolter The way Karabiner Elements goes about modifying input interferes with OpenEmu. So something would have to change on their end. Before macOS Sierra, on their Karabiner software, it wasn't like this. I suspect they had to change the way the input is modified based on the new OS update. Right now, you'll just have to close Karabiner Elements while using OpenEmu or uninstall it.

**Comment by revolter** [comment]
But other apps don't have problems with either Karabiner nor Chrome.

**Comment by clobber** [comment]
What program X does compared to program Y is irrelevant.

OpenEmu handles input differently than most applications, due to our special nature of responding to both keyboard and HID events while a game is running. Keyboard events, especially, are handled at a lower level - not through Cocoa but through IOKit - so often times other applications running can cause interference. This is the purpose of the [wiki guide](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) which outlines common issues.

No, this isn't going to change so close other applications that are a problem.
