### ISSUE TITLE
Trying MAME 0.151 ROMset with OpenEmu

### ISSUE THREAD

**Issue by DRMINDBENDER** [OpenEmu/OpenEmu#2827]
I'm loving OpenEmu so far. All my emulation launched from one app!

And the experimental version even supports MAME 0.149.1 !!

I trying out ROM set 0.151 , plus CHDs (~300GB). I cannot personally test all 28,000 games, of course. But most of them that I tried, are working.

Once the titles get into late 90s, OPenEmu doesn't like to cooperate. ie: Tekken 3 plays perfect. But Tekken 4 and 5 won't boot.

I cannot get any of the rail shooter games to boot.... House of the Dead, Time Crisis, etc.

My only complaint is the minimal controller settings that are available. The joystick sensitivity ought to be adjustable. For driving games, paddle games, roller ball games, etc.

Hope that  helps.

2014 27" iMac 5K display.
OS 10.11.6 El Capitain

**Comment by clobber** [comment]
Newer games will not run it, despite there being a copy available for you to download.

MAME is tricky, which is why the core port is still in the 'experimental' cores bundle and not officially supported. One needs to be using games from a MAME 0.149 ROM set as well as whatever required parent/bios/system file ROMs the game may need. Some games, even though they are included in a MAME ROM set, don't actually run at all. Best I can do is like you to a guide that may or may not be helpful: http://agreeordie.com/how-to-emulate-retro-video-games/

It is recommended to use the official standalone version of MAME: http://bamf2048.github.io/sdl_mame_tut/

Additional details on MAME here: http://choccyhobnob.com/articles/demystifying-mame-roms/
