### ISSUE TITLE
MAME logging?

### ISSUE THREAD

**Issue by ylluminate** [OpenEmu/OpenEmu#2828]
When MAME games don't work, I'd like to see some additional logging to ascertain what may be going on with them.  Is there a way to enable logging of some sort within MAME?  I tried to execute from the shell and don't see any output there (eg, `/Applications/OpenEmu.app/Contents/MacOS/OpenEmu`) that indicates the problem for such ROMs.

**Comment by clobber** [comment]
* MAME is really unsupported since it is still experimental and likely will not be a standard core plugin.

* Logging already occurs in Console when files are missing.

It is recommended to use the official standalone version of MAME: http://bamf2048.github.io/sdl_mame_tut/

Additional details on MAME here: http://choccyhobnob.com/articles/demystifying-mame-roms/

**Comment by ylluminate** [comment]
Is there any area in particular that you could use help on to get MAME working better in OpenEMU @clobber?

**Comment by clobber** [comment]
MAME has inherent usability problems that don't fit our model. It's best as standalone.
