### ISSUE TITLE
Unable to add ROM, does not show up in the menu

### ISSUE THREAD

**Issue by GigaCrush** [OpenEmu/OpenEmu#2922]
I recently updated to Mac OS X Sierra from Yosemite, and updated OpenEmu as well. I tried adding a new ROM into the app (specifically Project Justice, pjustic.zip), but it did not show up in my library, nor did it get added to the ROMs folder.

I tried several other things, including reinstalling the MAME core, using a different download of the ROM, reinstalling OpenEmu entirely, and putting the ROM into the "Automatically Import" folder (the game scanner continued to scan for about 5 minutes then the bar froze). I had been able to import the game prior to the update, although it wasn't running how I had wanted, so I removed it from the library and decided to try again later. I'm a bit confused at the moment.

**Comment by clobber** [comment]
That file cannot import due to the Arcade system plugin seeing its [file size as too large](https://github.com/OpenEmu/OpenEmu/blob/master/OpenEmu/Arcade/OEArcadeSystemController.m#L37) which was originally added in commit https://github.com/OpenEmu/OpenEmu/commit/724d861564c2dbf01c871f0ae3f3c8e538573286 to workaround accidental import issues relating to CD-based games. All this doesn't matter though, because MAME cannot really run Naomi hardware games which Moero Justice Gakuen/Project Justice is.

Also noting that Arcade/MAME is 'experimental' and not a focus, so it's unsupported at this time. Instead, you may want to use the standalone version of MAME.
