### ISSUE TITLE
PS4 Dualshock 4 analog sticks not working with PSX games (OpenEMU)

### ISSUE THREAD

**Issue by conchis1** [OpenEmu/OpenEmu#2925]
I am currently unable to use the left and right analog stick while playing PSX games. Turning analog mode on does not seem to help. I have tried remapping in OpenEMU. I have also updated to the latest version of open emu. I have tried with multiple games. Any recommendations would be greatly appreciated.

OpenEMU V2.0.4
Ps4 DualShock 4 Model CUH-ZCT1U

Thanks 
Conchis

**Comment by clobber** [comment]
Mine works. Some older PS1 games will not support analog at all, and some others will require you to press the 'analog' button to activate them.

Beyond that, you can see a guide for [troubleshooting input problems](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) and try reseting your input bindings:

1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.

**Comment by hughkenety** [comment]
I am having the same issue as the user. Left and right analog sticks do not work on the PSX1 core of OpenEmu despite being properly mapped. Analog sticks work on all other cores such as Nintendo or PSP. The PSX Mednafen core is up to date as 0.9.48

The gamepad I am using is the 8Bitdo SN30 Pro with up to date firmware 1.25. Other game pads such as Dual-shock and the older 8bitdo N30 Pro are able to use the analog sticks (without need for analog mode). Have tired remapping analog mode to multiple different button to activate. Not sure if analog button is being registered or not since analog sticks continue to not work.

As a test I flipped the analog and d-pad directional buttons. Analog stick will work as a d-pad. While D-pad will no longer work. Thus, it appears the issue is that analog mode is not registering. I have done as instructed above and cleared out input bindings to no avail.

I am running High Sierra 10.13.4 on a 2017 MacBook Pro. Any further recommendations or instructions would be greatly appreciated.

Thanks,
Hugh
