### ISSUE TITLE
Background image (2x) doesn't look right (macOS Sierra)

### ISSUE THREAD

**Issue by PlutoX86** [OpenEmu/OpenEmu#2960]
The low-res version looks fine though. Since i saw a screen cap from another user, i thought this might be relevant..

(Low-res for new 'Collections' and 'Homebrew' on Sierra)
![bildschirmfoto 2016-12-22 um 01 44 11](https://cloud.githubusercontent.com/assets/10595183/21411422/b409aa0e-c7e8-11e6-93ac-0154e9018dea.png)

(High-res since Sierra)
![bildschirmfoto 2016-12-22 um 01 45 03](https://cloud.githubusercontent.com/assets/10595183/21411419/aa6886aa-c7e8-11e6-9461-ddeaa4fad453.png)

**Comment by robotoad** [comment]
I'm afraid I don't understand what you're describing in your issue. The title says the background image doesn't look right on 2x screens, but you posted standard resolution images. There appear to be artifacts in the background gradient in the second image, but it looks like image compression.

**Comment by PlutoX86** [comment]
Ok, since english isn't my first language, i try to explain it a little bit better..

OE uses 2 backgrounds with different resolutions in certain menus. These can be found in OpeneEmu/Graphics.xxassets/background_lighting.imageset. 

The low-res one (see below) is active when you make a new collection, or to the "Homebrew" section. 
<img width="322" alt="background_lighting" src="https://cloud.githubusercontent.com/assets/10595183/21412621/e07a07a6-c7f1-11e6-9b23-9e7391047ed3.png">

The high-res one is used for any other menu. BUT since i updated to macOS Sierra, the high-res one looks like you described it. Compressed and with artifacts... And since other people postet pictures on your Git (https://github.com/OpenEmu/OpenEmu/issues/2955), i thought it'd be nice if someone could fix this. Since this graphics error doesn't appear on El Capitan!
<img width="322" alt="background_lighting 2x" src="https://cloud.githubusercontent.com/assets/10595183/21412626/e9f1599c-c7f1-11e6-9fb9-258d34482dc8.png">
In my case, i use a Retina MacBook Air 2011 btw.

**Comment by robotoad** [comment]
I can't reproduce this in OpenEmu 2.0.4 on an early 2013 MacBook Pro running Sierra.

**Comment by PlutoX86** [comment]
Okay.. just wanted to tell you guys. :)

![bildschirmfoto 2016-12-22 um 04 32 51](https://cloud.githubusercontent.com/assets/10595183/21414451/d129c10c-c7ff-11e6-8ad3-7238a154a856.png)

**Comment by robotoad** [comment]
To clarify, based on the screenshot that was edited out, you're running a MacBook Air (I thought you meant a MacBook Pro), so this issue doesn't appear to be related to 2x assets. Regardless, it's probably better to use a solid color for the background instead of a textured gradient to better fit current macOS conventions.

**Comment by PlutoX86** [comment]
I see, sorry for the confusion. Also apologies for spamming posts and edits in this thread.. hope you didn't get a notification every time i edited something.. 

Well.. final words, i still think your old style look suited OE best ;) http://imgur.com/M4Da1eb

Happy Christmas! :)

**Comment by shysaur** [comment]
I also get this problem, and I have a non-retina screen; as @robotoad said, it's not asset related, it's a bug introduced by Apple in Sierra that affects a private API used by the grid view to draw the background. (Basically, the call to -drawImage:inRect:fromRect:alpha:1.0 in line 733 of OEGridView.m does not stretch the background anymore.) By disassembling the function, one can see that it has various code paths that are triggered depending on the surrounding OpenGL context's state, so it's entirely possible that only some people are affected just because they have a different graphics card. 

Luckily there is a non-private API that does exactly what is needed here; I did a quick code change to use the non-private API and everything is back as it should be. In my opinion, the real bug here is OpenEmu relying on private APIs: it's inexcusable to leave this thing in and say "apple should fix it"; since it doesn't affect any of their code, they won't (moreover, the ImageKit API the grid view is based on has also become deprecated as of late).

I was planning to submit a PR with the fix, along with other appearance-related fixes, but real life got in the way and I have not submitted anything yet.

**Comment by shysaur** [comment]
> I was planning to submit a PR with the fix

That PR has been submitted just now.

**Comment by robotoad** [comment]
Thanks for the PR!

With regard to private API usage, much of the codebase dates back several years when there may have been no other solution at the time. Updates this year have been smaller in scope as the dust settled after the 2.0 crunch, but eventually, there will be larger changes, I'm sure.
