### ISSUE TITLE
how to run mame on OpenEmu

### ISSUE THREAD

**Issue by greengamerUSSR** [OpenEmu/OpenEmu#3008]
is it possible to run a mame emulator on OpenEmu?

**Comment by clobber** [comment]
- MAME is really unsupported since it is still experimental and likely will not be a standard core plugin.

It is recommended to use the official standalone version of MAME: http://bamf2048.github.io/sdl_mame_tut/

Additional details on MAME here: http://choccyhobnob.com/articles/demystifying-mame-roms/
