### ISSUE TITLE
Couldn't communicate with helper application?

### ISSUE THREAD

**Issue by moe207** [OpenEmu/OpenEmu#3027]
Hello, just downloaded OpenEmu just for the mac N64 emulator. Keep trying to open games and I can play them for about 30 seconds before I get the error " Couldn't communicate with helper application" and I get booted out. Tried deleting cores and redownloading just the one I wanted, but still no luck. Not sure where to go from here. Thanks!

**Comment by moe207** [comment]
OpenEmu v. 2.0.4 and Version 10.12.2

**Comment by clobber** [comment]
Which game is crashing?

**Comment by moe207** [comment]
Majoras mask and ocarina of time

**Comment by moe207** [comment]
I've tried both I can play for a couple minutes then it boots me and the error shows up

**Comment by MrGoomba** [comment]
I'm having this exact same problem - Except I can't even open the games. it gives me the message "Couldn’t communicate with a helper application," as soon as I click on a game

**Comment by clobber** [comment]
Post crash logs + which game you tried, if this still occurs using OpenEmu 2.0.5 and the latest Mupen64Plus core plugin (version 2.5.3).

Also, what happens if you try to load the games without restoring an autosave state on first load?
* Go to OpenEmu > Preferences > Library, click "Reset warnings"
* Open your game and click "No" if prompted to "Continue where you left off"

**Comment by clobber** [comment]
Closing for lack of info.

**Comment by vis2k** [comment]
Just encountered this too.
It happens when resuming from a save state.
If I move them out of OpenEmu save states folder, the game starts just fine.

@clobber should I attach the save states to reproduce?
