### ISSUE TITLE
N64 issue with Goldeneye 

### ISSUE THREAD

**Issue by SomeEmuUser** [OpenEmu/OpenEmu#3056]
I think this is a convert issue with the N64 emulator. I was having issues with 007 goldeneye in the menus. The crosshair cursor would only go side to side and up, not down, making it very hard to choose a level beyond the first layer. Then I downloaded the Mupen64plus as a stand alone emulator (M64py) and boom, it worked just fine, moving up and down. 

Any help please.

**Comment by mrvacbob** [comment]
What controller are you using? Do you know if it works in other games/systems?

**Comment by SomeEmuUser** [comment]
@mrvacbob I am using my key bored (WSAD) configuration. Like I said, it does not go down in the menus in openEUMU but it does in Mupen64plus stand alone. If it is still no clear, I can make a quick video.

**Comment by clobber** [comment]
> I am using my key bored (WSAD) configuration.

Well that really isn't going to work. Analogs aren't mapped to the keyboard, just d-pad. Pretty sure you will need a gamepad with analog joystick to properly navigate the menus.

**Comment by SomeEmuUser** [comment]
@clobber but like I said above, how come it works in Mupen64plus by itself but not when Mupen64plus is played through openEMU. Would you like me to make  quick video that might clear the air?

**Comment by clobber** [comment]
Because one instance of Mupen64Plus running is not like the other. Various reasons:

* Standard ports of M64P use an input plugin that OpenEmu does not need to use. The plugin may be attempting to do a (lousy) approximation of digital-to-analog input for keyboard users.
* The frontend (M64Py) might be handling inputs differently, attempting to convert keyboard to analog too.
* There could be a bug in the version of Mupen64Plus that our core port is based from.
* There could be a bug in our implementation of Mupen64Plus.

Without having GoldenEye on actual hardware with a real N64 gamepad in front of me, I don't know how d-pad input actually behaves at the menu.

OpenEmu handles input differently and attempting to route digital (keyboard) to analog isn't going to be supported. A gamepad with analogs is recommended to enjoy those games properly.

**Comment by SomeEmuUser** [comment]
you are probably right, that it is a lousy plugin in openEMU. I will leave a link to a video showing how it does not work in openEMU and does in M64Py. If anyone in the future can fix the issue, i'd be most gracious ( https://vimeo.com/204301143 )

**Comment by clobber** [comment]
Testing with an analog gamepad (SteelSeries Nimbus). The issue actually appears to be axis peak/deadzone related, at least for the y-axis, as pushing analog DOWN all the way will force it UP, but a slight press DOWN will move down as expected. This is why mapping the analogs to keyboard buttons (which count as full analog presses against whichever axis direction) don't work properly for this game, at least in the menu.

We can probably mitigate this by limiting the min/max values for analog presses in the core implementation, but I'm going to dupe this with #1303 since that is the real problem.

**Comment by clobber** [comment]
Our implementation was calculating the analog range wrong for the N64 controller. The SDL input plugin handles it right, which is why the other port worked for you.

This is fixed in https://github.com/OpenEmu/Mupen64Plus-Core/commit/44dd073396e104c32d8dd5768b427ec9c93fe775 and the core update will go out alongside OpenEmu 2.0.5 or before then.

Note: you will still want an analog gamepad because a keypress means the analog range is fully saturated (max value) so mario will never be able to walk, just always run.
