### ISSUE TITLE
OpenEmu doesn't listent to Swift CGEvent

### ISSUE THREAD

**Issue by Tchoupinax** [OpenEmu/OpenEmu#3077]
Hi every one,

I tried to simulate keydown with an Swift Application. For exemple, i simulated "d" key down. It works well, in Safari, in others applications. I can assign "d" in OpenEmu with "edit Game Control". It works well in this windows but when i come back to the game, it does not work. However, my keyboard button works. And use my keyboard or my app to simulate d work everywhere... except for OpenEmu. 
:(

Someone has an idea about why it does not work ?

-> And simulated key down is working in "Edit Game Control" !! But not in game. It's crazy.
Thank you for your time,

Tchoupinax

**Comment by clobber** [comment]
That's not going to work.

OpenEmu handles input differently than most applications, due to our special nature of responding to both keyboard and HID events while a game is running. Keyboard events, especially, are handled at a lower level - not through Cocoa but through IOKit.

This is also why often times other applications running can cause interference. Our [wiki guide](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) outlines common issues.
