### ISSUE TITLE
Controls appear "stuck"

### ISSUE THREAD

**Issue by forrestburke** [OpenEmu/OpenEmu#3097]
I apologize if I'm doing this incorrectly

I was playing Final Fantasy III (VI in Japan) and suddenly the controls have been acting strangely. At first the menus wouldn't allow me to select anything because it seemed as if the up button was stuck. Now it's the Left and Right triggers that seem to be "stuck" causing the characters to run away during a fight. I just upgraded to Sierra and perhaps it's as simple as that. HELP

**Comment by clobber** [comment]
Try here first: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by goocy** [comment]
I had the same issue. The cause was that I playing with a USB gamepad, but saved my state by pressing Cmd+S. OpenEmu interpreted the S as the press of a virtual gamepad button because that's the default keyboard mapping. When I loaded this state, the virtual gamepad button still was registered as permanently pressed. Pressing the button on the USB gamepad did not relieve the issue, and neither did removing the keyboard mapping.

My solution was to re-map the keyboard to its previous gamepad buttons, to press S a single time and to remove the mapping again.
