### ISSUE TITLE
Dualshock 3 Analog Stick On PS1 Emulation

### ISSUE THREAD

**Issue by joo456** [OpenEmu/OpenEmu#3123]
I'm trying to play Ape Escape on PS1, which uses the analog controller. But when I try to run around (with the left stick) it will sometimes make me walk instead often. so my analog stick will be like this
(o      ) but the game thinks im doing this ( o       ) so it makes me walk around instead of running. Also, sometimes the right analog stick will stop working entirely for a second or two. I've tried using wired and wireless, and using different computers but the problem is still there.

**Comment by clobber** [comment]
What version of OpenEmu? What gamepad?

**Comment by joeb456** [comment]
Most recent version and the dualshock 3 (ps3) controller

**Comment by AhimsaBjorn** [comment]
I am having same or similar issue with Dualschock 3 analog sticks not working for PS1 games. OpenEMU v2.0.5. Games either don't recognize sticks or they behave erratically.

**Comment by clobber** [comment]
@AhimsaBjorn That doesn't sound similar to me. Many PS1 games don't support analog, others require you to press the 'analog mode' toggle to enable them. Besides than that, make sure nothing in the [input troubleshooting guide](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) is an issue.

**Comment by AhimsaBjorn** [comment]
I have tried pressing the analog mode toggle button to no avail and do not have any conflicting apps installed. Games I am trying to run are Syphon Filter, Twisted Metal 2 & 4, Spider-Man 1 & 2, X-men Mutant Academy, and Resident Evil 2.

**Comment by AhimsaBjorn** [comment]
The analog sticks seem to glitch out on some games causing random movement of characters or selection of menu items.

**Comment by clobber** [comment]
Nothing in the implementation is wrong to the point where analogs won't respond at all.

Both Twisted Metal 2 and Resident Evil 2 are digital-only games, no analogs. There is a special Resident Evil 2 DualShock version which supports analog, though.  

The range issue could be due to https://github.com/OpenEmu/Mednafen-Core/commit/3247fcf46efb6a9c7f7f71bb1697c4ebc7bf2d65

**Comment by Daplesco** [comment]
@clobber Has anybody ever told you how arrogant you sound? He asked you to help with a problem, and you tell him he is wrong.

Jerk.

**Comment by clobber** [comment]
Fixed in https://github.com/OpenEmu/Mednafen-Core/commit/b18fbd0ab241ed3a208666cad1b10b3058379ff5. Restart the app and an updated Mednafen core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for Mednafen 0.9.47.
