### ISSUE TITLE
Previous GBA cores

### ISSUE THREAD

**Issue by AledonCS** [OpenEmu/OpenEmu#3125]
Hi there, I recently updated my gba core this week which is now the mgba 0.5.2 . Unfortunately I can't load my save states using this new core, and I've been trying to find the previous gba cores but I'm not sure where to get them. Could you please give me the .oecoreplugin file for the gba's previous core? Thanks a lot!

**Comment by clobber** [comment]
mGBA has not broken save state compatibility between versions. You must have another problem occurring, possibly with VBA save states.

See the [Default Cores guide](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Default-Cores) and the [Save File Transfer guide](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files) which may be helpful.

**Comment by AledonCS** [comment]
Thanks clobber, the issue I have is that I don't have the core that I saved my states with. When I load a save state it first says: 

"The save state was created with a different core. Do you want to switch to that core now?". 

But after it states: 

"The operation couldn't be completed (OECoreUpdaterErrorDomain error -1.)" 

I think the problem here is I don't have the original core plugin I used to create those save states. But it must be the VBA core I used before, however I'm not exactly sure where to get the core plugin. Could you look over this issue? Thanks!

**Comment by clobber** [comment]
@AledonCS Honestly, follow the guide I linked you to transfer your battery save files to mGBA (hoping those exist in your VBA folder), because VBA is a really broken GBA emulator and no longer supported here. It's why we switched to using mGBA as the default.

The only other way to get our old VisualBoyAdvance core plugin would be to manually download it from its repo and copy to your folder. Sorry, I don't really want to give step-by-step directions to do this. Using that plugin with OpenEmu could break in the future, so **please** switch to using our mGBA core plugin for GBA games. It's for the best.
