### ISSUE TITLE
Saturn game is falsely identified as PSX game

### ISSUE THREAD

**Issue by xXSlick-JimmyXx** [OpenEmu/OpenEmu#3128]
I recently posted about an issue with importing multi-disc games for the Saturn.  As it turns out, one of the .cue files had a typo and I corrected it.  However, there is now a separate issue that doesn't seem to involve the multi-disc nature of this game (I'll note that I did follow the instructions on creating the proper .m3u file, however).

To start, I went into Finder and cleared out any instances of the game's files in all folders within the OpenEmu library.  Then, I dragged the game's .m3u file into the Saturn library in the OpenEmu application to import it.  After scanning the game for a few seconds, OpenEmu crashed and quit out.  Reopening it, the Saturn library was unchanged.  The PlayStation library, however, had this:

![screen shot 2017-04-06 at 2 07 06 am](https://cloud.githubusercontent.com/assets/26951161/24740171/d3806ea4-1a6d-11e7-8e74-0f7ce4584972.png)

('Utena.m3u' was the file I dragged in before this appeared)
Running that brought me to the PlayStation's disc menu with no special message or anything.  I then located the game's files in ~/Library/Application Support/OpenEmu/Game Library/roms/Sony PlayStation, and deleted them.  After restarting OpenEmu, the game was still shown in the PlayStation library, but trying to run it turned it into this:

![screen shot 2017-04-06 at 1 55 53 am](https://cloud.githubusercontent.com/assets/26951161/24740215/fec09a9e-1a6d-11e7-99b2-5e4cb5991979.png)

I was then given a prompt to locate the game's files, which I canceled out of.

One last thing to mention: I already have 14 games imported into my Saturn library that all run fine when clicked.  One of those is a multi-disc game like Utena, and another one is a Japanese game (although it is untranslated, unlike Utena).

**Comment by clobber** [comment]
A Saturn game cannot be identified as a PS1 game. What seemed to happen is your original m3u file ended up in your PS1 library due to an error in your crafted cue sheet, possibly from an importer bug where an unmatched m3u defaults to that library (don't know yet, just speculating).

You are in the current predicament because you manually deleted a file from the game library folder instead of through the UI, so it's showing up as a missing entry in the database.

So what exactly is actionable here? Can you simply right click on the "missing" entry and delete it from your PS1 library to get it off your screen? Does that work? I would have to break a game in my library as you have in order to test.

**Comment by xXSlick-JimmyXx** [comment]
When I right-click the file and click "Delete game", OpenEmu crashes.  I should have mentioned that this happened before, when it didn't have the error triangle over it; that's the reason I opted to delete the files manually like I did.
The remaining options when right-clicking the game are the same as any other game around it, except that it is missing "Show in Finder" and "Download Cover Art", for obvious reasons.

**Comment by xXSlick-JimmyXx** [comment]
If it is of any interest, here is the text of the .m3u sheet I wrote:
Utena_English_Disc_1_D-ko_Version.cue
Utena_English_Disc_2_D-ko_Version.cue

Text of the Disc 1 .cue sheet:
FILE "Utena_English_Disc_1_D-ko_Version.bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00

Text of the Disc 2 .cue sheet:
FILE "Utena_English_Disc_2_D-ko_Version.bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00

I double-checked to make sure that the binary file names were correct in the above .cue files.

**Comment by clobber** [comment]
Okay, so it sounds like now that you have that Saturn game correctly imported, you want to remove that incorrect/broken entry from your PS1 library, right?

Couple things:

* Paste the crash log.

* Zip your `Library.storedata` file in `~/Library/Application Support/OpenEmu/Game Library` and upload to https://transfer.sh/ and link it back here. I can use that to check out what ended up in the db file and, at the very least, remove the bad entry for you and send you back the corrected file. Just in the mean time don't add any new games to your library, otherwise the file I send you back will not contain those new games!

**Comment by xXSlick-JimmyXx** [comment]
It seems I also neglected to mention that, even after all of that, the Saturn game still has not been imported correctly (I apologize for my lack of clarity tonight).  That is the issue I would like to resolve.  I'm not broken up about an incorrect entry in the PSX library, but if it's somehow connected to this importing problem, then I'm happy to get it fixed.
Here is the zipped file you've requested:  https://transfer.sh/UFPjf/Library.storedata.zip
Here is a txt file of the crash log (generated when trying to import the .m3u again):  https://transfer.sh/fafmX/crashlog.txt

**Comment by xXSlick-JimmyXx** [comment]
Huh, it seems like putting the files back in the PSX folder allowed me to delete the bad entry.  What's more, now the game imports correctly and plays just fine.  Go figure!
Thanks for your patience tonight.  Keep up the good work <3
