### ISSUE TITLE
NES games play too fast

### ISSUE THREAD

**Issue by BoogiePL** [OpenEmu/OpenEmu#3132]
hello, NES games run TOO FAST, like pitched up (picture+sound), and after update they run even faster!! oh come on, can you do something with it? change the clock or at least make any choice of region settings, like pal/ntsc because in europe we had pal, and games were having normal sound and picture pitch, just slow them down a little bit so they could oplay normal tempo

**Comment by clobber** [comment]
NES games run at their correct rates and there was nothing in the update that could have affected them. My guess is you have bad ROM dumps with incorrect headers and so they aren't be ran properly by the emulator.

Instead of a vague comment assuming we know something is wrong, how about providing details such as an example game and your machine specs.

**Comment by BoogiePL** [comment]
here is the original game how it is and should be working on nintendo/famicom: https://youtu.be/tWO3FmOdT84

here is the OpenEmu speeded up: https://youtu.be/GbzWnC_5OG8

all games sound and are played faster, because there is no fps/region option, i don't know anyway why they are pitched up version. Some of Windows emulators have the adjustable option

my laptop is Macbook Pro mid 2015:
![mac](https://cloud.githubusercontent.com/assets/26942266/24877402/6686fa5a-1e2f-11e7-9f49-7dbe5b0f74b8.png)

why is it going so fast? there is no fun of playing those games like movies before ww2 or charlie chaplin/benny hill speeded up u know what im saying...

**Comment by clobber** [comment]
Sorry, you aren't making any sense here and your video doesn't tell me anything. Maybe you are running an NTSC game on a PAL TV at 50hz, so it runs slower? Nestopia and most other emulators run all games at the correct speeds, provided that the ROM contains a proper ines header.

The game in question, Treasure Hunter, is a North American (NTSC) game that runs at 60 fps. Both of our emulator core plugins are running this games at the correct speeds.

Perhaps what you are looking for is a Russian-style famiclone Dendy/Pegasus mode which would enable running NTSC/60hz games at a slower rate and adjusted pitch. We don't have that sort of option, and probably won't.

Instead, you should probably get used to running and hearing games at their correct rates and not what a famiclone ran them at. Otherwise, you can try to find another emulator that allows for more functionality to change to your preferred rate.

**Comment by antonio1310** [comment]
Hello!
I have the same problem, games run a little faster, than it is necessary.
All ROM's are normal, once there was a video game console, also used various emulators on various operating systems, such problem wasn't anywhere and what speed a favourite game has to have I know too. 
It's only on NES emulator.
