### ISSUE TITLE
How To Find a Lost Battery Save File

### ISSUE THREAD

**Issue by lydiahongamata** [OpenEmu/OpenEmu#3136]
Hey Everybody, I'd appreciate some quick help. 

I'm using the GBA emulator on OpenEmu to play some FireRed and it's been pretty smooth-sailing for the last two weeks or so: about 15 hours of game time in with no issues, its a great emulator. I've been creating my saves by going to the in-game menu and saving manually, rather than using the save option on the HUD (floppy-disk). Whenever I reopen the game, I'd simply just select "Continue my last game" and I'd automatically start where I left off. 

However, this time I accidentally selected the "No" option. I was transported to the title screen and when I went to the in-game load screen, the only save there was of a game missing about seven hours of play through. To make things more confusing, it seems to line up perfectly with the one "floppy-save" I ever made. Shouldn't I be able to load battery saves from the game menu since I always saved in-game?

I tried to pursue the save files in the game repository but it seems that my path is different. If I open Home in Finder, there is no Library folder. If I open Computer however, I can find Library, and Application Support, but there is no OpenEmu in the Application Support folder. Very Frustrating. 

I am running Mac OS Sierra on a mid-2010 MacBook Pro. Can anybody give me some help? I'm at my wit's end here.

**Comment by clobber** [comment]
>However, this time I accidentally selected the "No" option. I was transported to the title screen and when I went to the in-game load screen, the only save there was of a game missing about seven hours of play through.

Can't help with lost saves - usually due to inadvertent user error and they will be gone for good. One needs to be very careful when using save states and in-game battery saves, especially if mixing the use of both methods, which is what you did.

What likely happened is you forgot to save in-game before the last time you quit, so when you selected "No" at your next launch, the game had no choice but to take you to the last time you saved in-game. There is only one in-game battery save file so there are no "lost" files to be found.

You may have also loaded a save state file, which would have overwritten your battery save to the time the state file was created. Loading a save state restores the contents of everything in memory at the time the save state was created, which means the in-game battery save is also overwritten if you close the game having just loaded a save state. There is nothing you can do to recover the in-game batter save.
