### ISSUE TITLE
OECoreUpdaterErrorDomain error

### ISSUE THREAD

**Issue by ExacjiuOfErea** [OpenEmu/OpenEmu#3139]
I recently updated all of my cores, but when I try to load some save states in platforms it tells me I need to use the original core to load them, however when I click the option for switching cores I get the error, OECoreUpdaterErrorDomain -1. How can I fix this?

**Comment by clobber** [comment]
You're not being very detailed, but I know that updating core plugins would not have deleted others that weren't updated.

It sounds to me that you are loading a save state for a GBA game (I don't know, just guessing, because you're not being detailed!) that was created using VisualBoyAdvance. The VisualBoyAdvance plugin was deprecated and is no longer distributed, and you are on a machine where you do not have that plugin installed.

You should fix this by migrating you VBA battery saves to mGBA following the  [Save File Transfer guide](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files).

**Comment by clobber** [comment]
#3125
