### ISSUE TITLE
HELP!!  The EMU could not load ROM.....

### ISSUE THREAD

**Issue by cubadaddy** [OpenEmu/OpenEmu#3140]
this game.....  
http://coolrom.com/roms/psx/66780/Astronoka_(Japan)_(Disc_1).php

i tried so many time and follow the step it still doesn't work.....but other games works 

did i do something wrong or OpenEmu can't play this game!?
 
Anybody can help me......PLS!

what can i do.....

THX a lot!!!
-----------
OpenEmu ver.2.0.5
http://i.imgur.com/TcsRbJj.png
http://i.imgur.com/oAXcRYr.png

my OSX ver. 
http://i.imgur.com/2BspKaH.png

ROM problem:
http://i.imgur.com/8aViD8Y.png

**Comment by clobber** [comment]
>i tried so many time and follow the step it still doesn't work.....but other games works

Looks like a bad dump of the game to me, so find it somewhere else and stop using that shitty ad and malware covered warez site. Also, that game is multiple discs, so it should be prompting you to have both required discs and to follow the [multi disc guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game).

**Comment by clobber** [comment]
Just to verify our app works as expected, I got that file to download so I could check it out.

Basic checklist stuff here:
* First of all, you need unzip 7z file obviously.

* Secondly, the cue sheet and .bin filenames don't match up (of course, because you are downloading from a shit site).

* For the file to import properly, you either need to rename `Astronoka (Japan) (Disc 1).bin` to `Astronoka (Japan) (Disc 1) [SLPM-86088].bin` (this is the simplest and most error-proof method) or you need to open up the cue sheet and rename `Astronoka (Japan) (Disc 1) [SLPM-86088].bin` to `Astronoka (Japan) (Disc 1).bin` (more prone to making mistakes inside the file). So just go with the first method of renaming the .bin file to match what the cue sheet is looking for.

* After importing the file via the cue sheet and trying to launch the game, OpenEmu rightfully warns you:
<img width="532" alt="screen shot 2017-04-12 at 11 30 20 am" src="https://cloud.githubusercontent.com/assets/1303132/24968637/75e7e35c-1f73-11e7-85fd-c16adafce83a.png">

If you didn't get this, you did not follow the guide and import properly. Now to actually play this game, you will need to follow the [multi disc guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game) as I stated earlier.

**Comment by cubadaddy** [comment]
THX for your response !!  really!!!

but i unzip the Astronoka (Japan) (Disc 1) [SLPM-86088].rar

i  got two  file 

one called  "Astronoka (Japan) (Disc 1) [SLPM-86088].7z"  another  is Astronoka (Japan) (Disc 1) [SLPM-86088].cue

there's  no  "Astronoka (Japan) (Disc 1).bin"

and i unzip the Astronoka (Japan) (Disc 1) [SLPM-86088].7z

its shows "Track 01.bin.ecm"

should i decoded "ecm"  to  "bin" first? or just rename it to "Track 01.bin"??

or i can simply get a file  called  "Astronoka (Japan) (Disc 1).bin"

THX for your help again!!!

**Comment by clobber** [comment]
You aren't having issues with OpenEmu. Please fully read the guide; it tells you exactly what to do and which files can be imported.

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-an-ecm-or-ape-file

Either that, or find another dump.
