### ISSUE TITLE
Bug: After deleting multi-disk Playstation game it won't import again

### ISSUE THREAD

**Issue by Voley** [OpenEmu/OpenEmu#3151]
Steps to reproduce:

1. Add .cue and .bin files to your playstation library (didn't test with m3u)
2. Select games in menu, delete, choose "keep files" option
3. Try adding m3u or .bin files to the library again - it will process, but won't add the games.

What helped me is deleting Sony Playstation and unsorted folders in Application Support and relaunching OpenEmu.

**Comment by clobber** [comment]
> choose "keep files" option

Not really a bug. Keeping those files in the Game Library Folder means the importer cannot write the new files to the folder because they already exist. For cart ROM files, this is okay and our importer simply renames the file, but for CD-based games we cannot do this because the files need to be precise. We also want to make sure that everything that is supposed to be imported gets imported and that there are no conflicts with other files (on the off chance something has the exact same name), so we bail if some files already exist in the folder.

Solution is to select "delete files" instead of "keep files" when removing a CD-based game from the Library.

**Comment by Voley** [comment]
Maybe the app should say something and not just fail silently on import?

**Comment by clobber** [comment]
Users should **read** the guides and the app should present feedback, as we've noted: https://github.com/OpenEmu/OpenEmu/commit/97b48c865d70cf7e37979e4eccba7915de2d6bf0

Let's not waste each others time stating the obvious here.
