### ISSUE TITLE
Final Fantasy VIII M3U file not importing into Library in OpenEmu

### ISSUE THREAD

**Issue by Kim6990** [OpenEmu/OpenEmu#3163]
Hi there and thanks in advance for any help!

I have been trying for the past few hours to get FF VIII to work on OpenEmu. I have the .m3u file, .cue files, .bin files and also .sbi files.

![screen shot 2017-04-26 at 1 35 58 pm](https://cloud.githubusercontent.com/assets/28031205/25414497/e8f4a732-2a85-11e7-8490-f91085a695ba.png)

Initially I imported the .cue files without a .m3u file being present. I then deleted the files out of the library and then also reinstalled OpenEmu when the .m3u file failed to add the game into the library. It still does not add the game even though the .m3u file was created following the directions exactly!

Is there any way to fix this?

![screen shot 2017-04-26 at 1 36 12 pm](https://cloud.githubusercontent.com/assets/28031205/25414498/e93a2d34-2a85-11e7-9ee4-e254ea6ee7d9.png)

**Comment by clobber** [comment]
What output do you see in Console.app when you try to import the file? I'd guess that one problem is you appear to have a extra blank line at the top of your M3U where you don't need one. Also ensure your file is saved as plain text.

**Comment by clobber** [comment]
Also, why do you have SBI files for this game? It's the USA version (according to your files here) and doesn't require them, so what made you think you needed them?

**Comment by Kim6990** [comment]
![screen shot 2017-04-26 at 1 56 06 pm](https://cloud.githubusercontent.com/assets/28031205/25414854/35231902-2a88-11e7-9f91-7200211c98a5.png)

This is a few of the lines in console when I try to import the file.

I changed the m3u file so there is now no extra blank line at the top. Yes it is a plain text document with .m3u as the file extension.

There was a couple of lines at the bottom of the page on user guide for multidisk games about FFVIII needing .SBI files to work.

**Comment by clobber** [comment]
>This is a few of the lines in console when I try to import the file.

That isn't output from OpenEmu. Use the filter at the top to only filter for "openemu" and copy and paste all of the output from when you attempt to import the M3U file.

>I changed the m3u file so there is now no extra blank line at the top. Yes it is a plain text document with .m3u as the file extension.

So does it now import with the blank line removed??

>There was a couple of lines at the bottom of the page on user guide for multidisk games about FFVIII needing .SBI files to work.

That clearly states for PAL/European releases only. OpenEmu will prompt you if you try to run one of those games and it requires them...

**Comment by Kim6990** [comment]
No it does not import with the extra blank line removed.

This is the dialog from console:
![screen shot 2017-04-26 at 2 05 28 pm](https://cloud.githubusercontent.com/assets/28031205/25415073/861bfbfc-2a89-11e7-81c5-b491bb13554e.png)

**Comment by Kim6990** [comment]
Okay, so I go it to work by deleting the files already in the game library that were under OpenEmu in the Application Support folder. 

Tried importing the M3U files and it worked perfectly!

**Comment by Kim6990** [comment]
Thanks for your help!

**Comment by clobber** [comment]
Okay. From the error message, some or all of the files already exist in your Library. You maybe have *removed* them from your Library through the UI, but you did not actually *delete* them, so the M3U cannot import.

The fix is to first check your PlayStation library in OpenEmu to make sure you have removed+deleted the discs. If they are not showing up in the UI, you must manually delete them by:

* Navigate to `~/Library/Application Support/OpenEmu/Game Library/roms/Sony PlayStation` (~ meaning your Home folder where ~ is your username. [Guide here](http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/) if you don't know this.

* Delete all Final Fantasy VIII (USA) .bin and .cue files in the folder.

Once this is done, you will now be able to import the single M3U file and play your game. Just ensure there are no extra blank lines at the top or bottom of your M3U.

**Comment by clobber** [comment]
Okay great.
