### ISSUE TITLE
Pokemon White 2 Version Freeze

### ISSUE THREAD

**Issue by Tartarus2002** [OpenEmu/OpenEmu#3176]
Hello yes, I've been using OpenEmu for about three weeks right now and I've had about like 2 glitches and now I am experiencing a freeze. Im playing Pokemon White 2 and I'm stuck in a battle with a Jellicent and the screen stopped moving and none of the controls would work. Could someone please help me out with this. I've tried quitting the application many times and then rejoining. Didn't work. I even tried putting my laptop to sleep, restarting it, and even shutting it off and then reopening the application but nothing is working. Please help. I am using a MacBook Pro and I am using a DeSmuMe core, code or something I don't know to play the Pokemon game on.

**Comment by clobber** [comment]
Have to search because this comes up a lot.

In general, Desmume doesn't support Pokemon games very well - this is sometimes AP patch related. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility, or you can read up on AP patches.
