### ISSUE TITLE
Multi disc games

### ISSUE THREAD

**Issue by totneschap** [OpenEmu/OpenEmu#3182]
My openemu scans the files when they're dragged and dropped but then the games don't show! I have followed the multidisc instructions and I can get these games to work on my work mac!

**Comment by clobber** [comment]
Follow the import guide and check issue #3163. You probably have the same problem where the files are still imported or sitting in the Game Library folder, possibly in the 'unsorted' folder.

Beyond that, we don't offer additional help for this because the guide is very step-by-step and many simply don't follow it.
