### ISSUE TITLE
N64 games not playing

### ISSUE THREAD

**Issue by Amazee-Dayzee** [OpenEmu/OpenEmu#3186]
OK. NEW issue. The controller issue magically fixed itself which I am so grateful for so much you will never know, but now I can't get SM64 to load. All I get is just a black screen. I got it to load in the past before but now I can't. Is this a new issue?

**Comment by clobber** [comment]
Which version of OpenEmu?

**Comment by Amazee-Dayzee** [comment]
v2.0.5.

**Comment by clobber** [comment]
Need detailed information.

Is it loading the game but just a black screen and you still hear sound? Is nothing happening at all? Is it crashing? Is there any output in Console.app when this happens? What about after a machine reboot?

Also, what happens if you try to load the games without restoring an autosave state on first load?
* Go to OpenEmu > Preferences > Library, click "Reset warnings"
* Open your game and click "No" if prompted to "Continue where you left off"

**Comment by Amazee-Dayzee** [comment]
The game comes up but it is just a black screen and nothing happens. It doesn't crash, it doesn't make any sound there is nothing. Even when the computer is reset. I'm not sure what Console.app is. And its a new game that I didn't start yet so there are no save states.

**Comment by clobber** [comment]
Sounds like a possible bad ROM dump to me. Try another copy.

In addition, please check Console for any output when you open the game. Here are a few guides on how to do so if you don't understand:
* http://www.macworld.com/article/3102847/macs/hands-on-with-macos-sierras-console-now-its-easier-to-get-the-mac-information-you-need.html
* https://support.omnigroup.com/console-osx/

**Comment by Amazee-Dayzee** [comment]
I got a new ROM and it works. The only thing I'm worried about is that there is a warning when the game starts up saying that the core is incompatible and will glitch up.
