### ISSUE TITLE
Arcade and Saturn Options not appearing in experimental

### ISSUE THREAD

**Issue by rabnath** [OpenEmu/OpenEmu#3187]
Hi,
I downloaded the experimental version in order to play arcade roms. After downloading the experimental version I also downloaded the MAME core, however, "Arcade" is not showing up as an option on the list of consoles (which is what should be happening). I also downloaded the Yabause core and do not see Saturn as an option either. Not sure what I'm missing...
Thanks.

**Comment by clobber** [comment]
You need to explore the app a little bit before opening issues like these. Check both tabs, Library and Cores, in preferences. Tick boxes, click buttons. Or right click on 'Consoles' in the main window sidebar. Please keep in mind these systems are 'experimental' and unsupported right now.

Also, the Yabause core plugin was deprecated and removed from distribution - so that one won't ever be supported. I'm not sure how or why you grabbed that one. It's been replaced with Medanfen for Sega Saturn emulation.
