### ISSUE TITLE
Repo Wont sync Sub modules 

### ISSUE THREAD

**Issue by RaverX3X** [OpenEmu/OpenEmu#3213]
Before you say check the wiki , I tested this on 4 different machines that have properly configured githubs.   The main repo syncs fine but the sub modules seem to not want to sync, it seems like no account has access to them...  Checked to even make sure it was not a public key but actual authenticated account.  Even tested on windows with the desktop app and same error...

**Comment by clobber** [comment]
Sorry, we're not in control of GitHub's infrastructure nor are we responsible for troubleshooting user git issues - our issues pages are for bug reporting only.

The submodules are configured in such a way so that contributors can push commits via ssh. Unless there is a very specific reason you need to clone and compile the entire org, don't bother as latest core plugin updates are compiled and distributed over the in-app updater.

The proper configuration is indeed in the wiki: https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide#ssh-keys

#1925
