### ISSUE TITLE
READ NOW

### ISSUE THREAD

**Issue by Pixel0501** [OpenEmu/OpenEmu#3217]
I am using the experimental version of OpenEmu, and sometimes, when I drag a ROM into OpenEmu, it goes straight into Arcade. Anyway to move the roms around manually, because it seems the only way to sort your ROMs into the right console is to do it automatically. I really love this program, and I don't want to stop using it. I should mention I didn't have this problem before, but when I tried to change the location of the OpenEmu library, the problem started and is not going away. Please help right away! I've tried exporting only the ROM, but this doesn't solve my problem.

**Comment by clobber** [comment]
First off, stop opening new issues regarding this when you can post in the original one you opened here: #3214

Secondly, stop opening issues with annoying "READ NOW" titles like you have. This is free software and you are not entitled to immediate one on one support here. I can't tell you how much that irritates me.

In your original issue, post exact details on the problem with an example of a game. By exact, I mean filenames and expected system it should import to, instead of vague "it doesn't work!" type remarks which are unhelpful. Nobody can read your mind.

In the future, here are some handy guides in which you can learn how to properly ask for help for technical matters that I suggest you read:

* http://catb.org/esr/faqs/smart-questions.html

* https://www.mikeash.com/getting_answers.html
