### ISSUE TITLE
Mednafen core cannot open PC-Engine and PC-FX games with save files

### ISSUE THREAD

**Issue by Gankosakae** [OpenEmu/OpenEmu#3219]
When I open a PC-Engine/CD or a PC-FX game with save file(~/Library/Application Support/OpenEmu/Mednafen/Battery Saves/game.sav) and it will show "The emulator could not load ROM." just like the picture.
![12345](https://user-images.githubusercontent.com/29351630/27010059-9538fe82-4ece-11e7-9469-9ee92196456a.png)
If I remove game.sav and the game will work again.
But,the other games in different console like PlayStation or Saturn used Mednafen core with different save file extension have no problem at all.

**Comment by clobber** [comment]
Interesting. I remember a problem like this using an older version of our Mednafen core plugin where I had to work around it: https://github.com/OpenEmu/Mednafen-Core/commit/05d66b1bfcd96151fc75215c49709618c11bf447

Which version of the Mednafen core plugin do you have installed (check 'Cores' in Preferences)? Also, what happens if you delete the save file and simply start a new game and let it create a new save file - does it load okay then? I believe the older file is incompatible with the newer version, for some reason, so you will not be able to use the old save.

**Comment by Gankosakae** [comment]
It showed version 0.9.44.1.
![12345](https://user-images.githubusercontent.com/29351630/27013766-2bb2f4dc-4f1d-11e7-93d7-0c600a75fafc.png)
I deleted the Mednafen core in core folder and installed the core again.
It still showed version 0.9.44.1 and I think it is the latest one.
I made a test.
I removed old save file and play a PC-Engine/CD or PC-fx game and let it generated a new save file.
Then I closed the game and when I reopen the game with new save file and it show "The emulator could not load ROM." again.

**Comment by clobber** [comment]
Which game??? I cannot replicate this with "Akumajou Dracula X - Chi no Rinne (NTSC-J)".

Make sure you are **not** restoring an autosave or save state at launch or reusing your old save file...
* In the app, go to OpenEmu > Preferences > Library, click "Reset warnings"
* Open your game and click "No" when prompted to "Continue where you left off"

**Comment by Gankosakae** [comment]
OK,fallowing steps I reseted warnings and I removed save files again.
I opened my "Akumajou_Dracula_X_-_Chi_no_Rinne_(NTSC-J)_[KMCD3005]" and inputed player name.
I closed the game and checked if OpenEmu generated a new save file.
Yeah,the new save file had been generated.
I reopen "Akumajou_Dracula_X_-_Chi_no_Rinne_(NTSC-J)_[KMCD3005]" and clicked "No".
![2017-06-12 4 45 19 am](https://user-images.githubusercontent.com/29351630/27014428-639c827e-4f2b-11e7-825a-5c823d3dda8e.png)
Then it happened.....
![2017-06-12 4 45 54 am](https://user-images.githubusercontent.com/29351630/27014443-d85a75bc-4f2b-11e7-8cdc-d97c145022d3.png)

My OS is El Capitan 10.11.6 and system language is Traditional Chinese.

**Comment by clobber** [comment]
Those are the same steps I followed, running on 10.12.5, and I cannot replicate that problem. What is the size, in bytes, of your Akumajou_Dracula_X_-Chi_no_Rinne(NTSC-J)[KMCD3005].sav file?

**Comment by Gankosakae** [comment]
"Akumajou_Dracula_X_-_Chi_no_Rinne_(NTSC-J)_[KMCD3005].bcbf8be607a68560f39d05b03237b0ea.sav" file size is 2048 byte.

**Comment by clobber** [comment]
Okay, I tested this on 10.11 and I can replicate that problem. Having checked a conversation from a year ago with Ryphecha, the developer of Mednafen, they believe the issue is with error handling going out of order due to something wrong in zlib's `gzgetc()` function. This appears to only affect 10.11 which ships with zlib 1.2.5 and is why you experience the issue and I cannot on 10.12.

The work around here will be for me to either patch/hack it like last time or link in a newer version of zlib with the core plugin. I have to update Mednafen anyway since a new version is out.

**Comment by Gankosakae** [comment]
Thanks a lot!
