### ISSUE TITLE
Can't import .cue file (Playstation game)

### ISSUE THREAD

**Issue by xscaralienx** [OpenEmu/OpenEmu#3233]
I have read the user guide for cd based games and I can confirm that everything should be right with the cue file I'm using. The reference to the .bin file is correct and smart quotes and dashes are disabled.
Here is how the cue and bin files line up. [http://i.imgur.com/Rwky5Cc.png](url)

I was able to add it before but now it just won't get added. Game Scanner pops up and nothing happens

**Comment by clobber** [comment]
Possible issues:
* You didn't remove the game from your Library inside the app and only deleted them manually from the folder, or you chose to "keep files" instead of "delete files" when you last removed it.
* You have files lingering in the 'unsorted' folder that got stuck there during a bad import.

The solution is to delete the files that still exist inside the "PlayStation" or "unsorted" folder in `~/Library/Application Support/OpenEmu/Game Library/roms/`
