### ISSUE TITLE
"The Emulator could not load ROM"  on OpenEmu.

### ISSUE THREAD

**Issue by lucarav** [OpenEmu/OpenEmu#3234]
Hello, i have a Mac Book Pro 13 inch Mid 2010 with os Sierra. I'm italian, sorry for my poor English..i hope you will understand. 

I have downloaded all of the .bin files of Final Fantasy IX (4 discs), created the .cue files and the .m3u file following this guide "https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#getting-started" and in the end i dragged the .m3u file into the Playstation 1 folder on OpenEmu.
The download went good and i have now the game in the library.

But when i try to open it, it says "The Emulator could not load ROM". 
So i went to the Console app and it says (marked as "error"): 

"Detected missing constraints for <private>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once."

Help please! I'm trying to play this game for a very long time, and i was so close! Also i don't know anything about programming..so i really don't know what the Console app is saying to me.
Thank you so much, I really hope you can help me find a solution for this.
bye

**Comment by clobber** [comment]
Sorry, I'm not going to step by step troubleshoot these sorts of problems every time they come up, as there could be any number of issues with the files you downloaded or created, but the game will not load because there is something wrong with them. If you manually created cue sheet files, that is especially troubling as you may have downloaded bad rips of the game from the start. I suggest you look at a few past issues with multi-disc games for clues (use our search) and possibly download other files packaged with properly created cue sheets.

**Comment by lucarav** [comment]
Thank you for the answer. I downloaded new files (this time with the .cue files inside, so all normal), and when I try to drag the .m3u file in the playstation folder OpenEmu crashes directly. And it does it every time i try to drag the file..what do i have to do?
