### ISSUE TITLE
Rename Game Library to Games?

### ISSUE THREAD

**Issue by ItsSohma** [OpenEmu/OpenEmu#3273]
I've noticed that when relocating the game library, if you don't name your folder game library, it adds that folder as a subfolder. Would it be possible to rename game library itself? I like to store it in my user folder with Documents, Downloads, Music, Movies, Pictures, and... Games. Game library in with those doesn't flow as nicely. Especially since there is also a folder called Library. There must be a reason that this isn't currently possible (or if it is, I apologize).

My temporary solution has been:
```bash
chflags hidden game\ library
ln -s ~/game\ library games
```

**Comment by robotoad** [comment]
In addition to ROMs, the Game Library folder contains the library datastore and cover art. Except in cases of troubleshooting, it's not intended to be user-accessible, so I'd say it's unlikely for it to be able to be renamed since the name isn't supposed to be relevant to users. Using a symbolic link is probably the best solution to accomplish what you want, but I recommend against this because you might be tempted to manipulate the contents in Finder or use the folder for general storage, and this could negatively affect OpenEmu's behavior.

**Comment by ItsSohma** [comment]
I didn't realize it could have performance issues. I was not just tempted, that was my whole idea originally. I stored all my games in there, not just OpenEmu. Anyway, maybe a better way to do this would be to create the Games folder and then create an alias in there that leads to the roms folder. Thanks for helping me out @robotoad.

**Comment by robotoad** [comment]
You shouldn't need direct access to the ROMs folder since those files are managed by OpenEmu. Manipulating the contents of the Game Library folder outside the application will cause problems.
