### ISSUE TITLE
The Controller mapping

### ISSUE THREAD

**Issue by Elatarisi** [OpenEmu/OpenEmu#3275]
I want to map some buttons besides the usb controller, like keyboard.

Because, for example ps1 controller has a dedicated analog button that not many usb controllers have, so I want to map some of my keys to usb keyboard and some of them to my computers keyboard which is not possible in open emu, which makes me kinda sad.

**Comment by clobber** [comment]
>which is not possible in open emu

OpenEmu responds to both keyboard and gamepad input at once. So you are able to press a keyboard button (and use that) even while a gamepad is plugged in.

**Comment by Elatarisi** [comment]
![screen shot 2017-07-23 at 00 48 23](https://user-images.githubusercontent.com/30377192/28494762-a87854ce-6f40-11e7-8f38-6d32cdbc78f4.png)
So what am I doing wrong here? Keyboard does not responses to anything

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by Elatarisi** [comment]
I am not using any of these applications or hardware but thanks.

**Comment by Elatarisi** [comment]
Isn't it a tiny little bit bs that you closing the issue immediately, but while me having the problem is consistent.

I have an issue that effects my openemu experience deeply, but all you do is saying "no it's not" and closing the issue and giving me a troubleshoot link which has no use for me.

Is there anywhere else that I can ask for help for this issue, because I can't use this software and it seems like I have nobody to ask for help.

**Comment by clobber** [comment]
Sorry, no. That is a problem on your end (I suspect a lack of understanding and exploring in the app), not an OpenEmu issue, and I've already given you all the information I can. We cannot troubleshoot a problem that no one else can replicate. Perhaps you don't understand that you need to **select 'Keyboard' in the input dropdown box** in Controls Preferences in order to map keyboard buttons from...the keyboard. That cannot be done with a gamepad selected, which is supposed to be obvious, and why 'Keyboard' has a dedicated entry in the list.

OpenEmu responds to both keyboard and USB input at the same time. It's why I can play a PS1 game with, say, a Logitech Dual Action gamepad and also press 'backslash' on my keyboard which is mapped by default to 'Analog Mode'.

This is a feature we've had since the beginning, and it always works, provided you don't run into some known edge cases outlined in the [input guide](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) - or simply didn't intuit how the dropdown boxes work in Preferences.
