### ISSUE TITLE
Required m3u file missing (after i've already played this disc??)

### ISSUE THREAD

**Issue by spencerparenteau** [OpenEmu/OpenEmu#3300]
Hello All,
I had worked through to get open emu working with a multi disc game after I found out I had needed to do this step prior to beginning.  I havent played FF9 in a few months and was going to sit down and play a bit more.  Im at the final point on the 4th disc, so i've played all 4 discs already, i havent deleted anything.  Why on earth would it not allow me to play the 4th disc now?  I have active save points showing for all discs.. 1 through 4 in the save states tab, wont allow me to load from there.. wont allow me to load from the game itself, whether i choose load from last game state or not, saying i need the m3u file that I'm fairly sure i never had or at the very least had never "changed/deleted" throughout the whole game. This is wild guys.  I lost my save data when i was a kid right before the final boss battle and i was so mad i never played again, here i am like 10-15 years later and viola... the same thing haha.

**Comment by clobber** [comment]
Yes, M3U playlist files are always required to play multi-disc games. It has always been in the directions, just never strictly enforced until now so that users do not make mistakes from the beginning due to failure to read (as you did).

Follow the guides to set this up and to successfully transfer your save file over: https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Required-m3u-file-missing

Cannot do anything for you beyond that.

**Comment by spencerparenteau** [comment]
Just seems so odd that I've made I've made it through all 4 discs without needing it till now.  Was there an update to open emu?  Like i played all the discs and just translated my save files over to the next disc when the time came... I'm fairly interested in what happened as of now, if you know what I mean.

**Comment by clobber** [comment]
What happened was you didn't follow directions, so you had to transfer your save file over each disc swap instead of creating the proper M3U file which handles the saves automatically. We improved the experience so users can no longer make the same mistake you made (by not reading the directions) and ultimately mess up their saves or wonder how to swap discs. The emulator works by requiring M3U playlist files for multi-disc games in order to facilitate disc switching and save files. I'm...not sure what you don't understand about this.

Accept the change, correct your setup and save file and then continue playing.
