### ISSUE TITLE
"Battle Heat" for PC-FX launches in TurboGrafx-CD

### ISSUE THREAD

**Issue by jeansebastienbg** [OpenEmu/OpenEmu#3305]
Don't know if it's a ISO related issue, but I've downloaded a couple of them and the problem persists.

When I add the .BIN+.CUE files in openemu, the Battle Heat ISO show up into the TurboGrafx-CD section.

Something lauches. I see a background with the characters of the game, a music from the game plays, and a scroll-up japanese texts appears. Can't understand anything of course but you can see PC-FX written in western characters. My guess is that it's what would happen if you inserted a PCFX disc in a  TurboGrafx-CD console.

**Comment by clobber** [comment]
Thanks for reporting, I can replicate this. "Battle Heat" appears to be the (as far as I know) only PC-FX game that also contains the magic string that mistakenly identifies it as a PCE-CD game. That's why it's getting added into your PCE-CD library instead. I'll come up with a fix after I check it out some more.

**Comment by jeansebastienbg** [comment]
Wow thanks for the quick feedback and congrats for your awesome work on this sweet software.
