### ISSUE TITLE
PCE 2/6 controller switch problem.

### ISSUE THREAD

**Issue by unexpectedstuff** [OpenEmu/OpenEmu#3319]
Hello, thanks for your work.
The problem is: 
When pushing "2/6 mode' on the keyboard or on any controller during the game emulator registers [down+"1"] input(I guess). This problem valid for both PCE and TurboDuo games.
Thank you.

**Comment by clobber** [comment]
Not sure I can replicate this or understand what you mean. The mode key works as expected for a six-button game (Street Fighter II' - Champion Edition). Can you give me a good example of what you mean?

**Comment by romuloellery** [comment]
SF2CE works fine, but all PCECD games I tried didn't work at all (in 6 button mode). One example is Garou Densetsu Special.

**Comment by clobber** [comment]
The problem here is that you both were attempting to use the "6-Button" controller mode on unsupported games, which causes input glitches. Since Street Fighter II is pretty much the only game that supports it, I've limited use to only supported games.

https://github.com/OpenEmu/Mednafen-Core/commit/c07a4e8960ae426bf87ec751d2f9a988f19f21ad

This is fixed as of the Mednafen 1.24.1 core plugin
