### ISSUE TITLE
Allow advanced search for arcade games

### ISSUE THREAD

**Issue by viniciusccarvalho** [OpenEmu/OpenEmu#3333]
Hi, it would be great if OpenEmu could enable some sort of filtering by Manufacturer on the arcade collection. It would go a long way on organizing collections such as CPS1, CPS2, NeoGeo ...

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](http://choccyhobnob.com/articles/demystifying-mame-roms/)."
