### ISSUE TITLE
Lost save states when adding discs to multi-disc game

### ISSUE THREAD

**Issue by MaxMartin** [OpenEmu/OpenEmu#3334]
I started playing a multi-disc PSX game, and initially only added the first disc to OpenEmu. After an update, OpenEmu now requires all discs of the game to be present, so I went through the process of adding the other discs and got the game properly added to the library, but now it won't recognize my save states. I tried renaming them to remove the " (Disc 1)" so that their name matched the name of the new game in the library, but no dice. Is there any way for me to recover these save states?

**Comment by clobber** [comment]
No.

Save states for multi-disc games that weren't previously created under the correct setup will not work. You should have followed the guide from the beginning. Multi-disc games have always required a M3U playlist file in order to enable disc swapping and sharing of the memory card files between all the discs. 

Moving forward, we made it impossible to screw this up for situations just like this.

You can recover/transfer **mem card saves** by following this guide completely: https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Required-m3u-file-missing
