### ISSUE TITLE
Games Won't Load

### ISSUE THREAD

**Issue by HarryAwesome06** [OpenEmu/OpenEmu#3352]
When I double click on a game it doesn't load. I have tried resetting OpenEmu and it stills doesn't load.

**Comment by robotoad** [comment]
Need more information. Does OpenEmu crash?

**Comment by HarryAwesome06** [comment]
No.

**Comment by HarryAwesome06** [comment]
Oh! It loaded. But then it gave me this error. Cheer1

**Comment by duckey77** [comment]
What emulated console are you playing?  What game? Are you on the latest OE?

**Comment by HarryAwesome06** [comment]
I'm trying to run all different games. But I'm trying DS the most rn. And yes, I am UTD.

**Comment by HarryAwesome06** [comment]
https://gyazo.com/2074f553a3a6f510dbcdb426452138f1

**Comment by clobber** [comment]
I don't know what any of your acronyms mean but I know that when troubleshooting it's important to be as detailed and specific as possible, noted in our [contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md).

The problem you seem to be experiencing is due to a bug with zipped ROMs in the latest release. The solution is to delete the games you imported, redownload, unzip and then import only the ROM files (.nds, .n64, ...). This bug is fixed for next release.

#3127
