### ISSUE TITLE
m3u File Doing Nothing?

### ISSUE THREAD

**Issue by LiamTheLlama** [OpenEmu/OpenEmu#3361]
I have made an m3u file for Metal Gear Solid 1 on the PS1 on OpenEmu but when I drag it into my OpenEmu Window it does nothing. I have tried downloading the experimental build but it does nothing (Version 2.0.5 experimental and normal)

**Comment by clobber** [comment]
Lacking details. Please search before opening a new issue.

* Make sure none of the files currently exist in folders in your Game Library.
* Search our issues to see if you are experiencing a known bug.
* Read both of our disc guides ([User guide: CD based games](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game) & [User Guide: Required m3u file missing](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Required-m3u-file-missing)).

Besides the few bugs I found and have fixed for next release, if an M3U file doesn't import, it's because you don't have something right so follow the guides closely. Sorry, I can't help you beyond that.
