### ISSUE TITLE
Final Fantasy IX not working

### ISSUE THREAD

**Issue by cyazz19** [OpenEmu/OpenEmu#3362]
Ok the problem with this is it wanted me to have all the discs before I played the game so I downloaded them all and followed the directions for a MacBook and I try to upload it to the game library and it won't  import. It drags in but won't show up. Please help!

**Comment by clobber** [comment]
Lacking details. Please search before opening a new issue.

* Make sure none of the files currently exist in folders in your Game Library.
* Search our issues to see if you are experiencing a known bug.
* Read both of our disc guides ([User guide: CD based games](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game) & [User Guide: Required m3u file missing](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Required-m3u-file-missing)).

Besides the few bugs I found and have fixed for next release, if an M3U file doesn't import, it's because you don't have something right so follow the guides closely. Sorry, I can't help you beyond that.
