### ISSUE TITLE
Black bars for Playstation emulation also at top/bottom 

### ISSUE THREAD

**Issue by Niwilai** [OpenEmu/OpenEmu#3377]
Hi guys,

for some reason I get black bars in each direction. I understand the bars are there to keep the aspect ratio of the games and I was used to have this for left/right, but I don't understand why this is happening for top/bottom also?

Please see attached screengrab

<img width="1440" alt="screen shot 2017-10-25 at 23 57 00" src="https://user-images.githubusercontent.com/9334296/32025397-3fd0d0aa-b9e0-11e7-83ee-4f8ddba13e92.png">

Anyone got an idea?

**Comment by clobber** [comment]
Looks like you are playing the PAL version of the game. That is simply the way it looks with the overscan area borders.

**Comment by Jackson-S** [comment]
I've been playing around with the Mednafen core settings, and adding
`MDFNI_SetSetting("psx.slstartp", "15"); // Starts rendering for PAL games from scanline 15
 MDFNI_SetSetting("psx.slendp", "272"); // Ends rendering for PAL games at scanline 272`
to MednafenGameCore.mm minimises the borders for every PAL game I've tested without cropping any of the image, and leaves NTSC games unaffected.

Could this be added as a toggle option or implemented in some other way? I have mostly PAL games due to growing up in a PAL region, and this would greatly improve the experience.

Before/After images from a few games:
<img width="252" alt="a_new" src="https://user-images.githubusercontent.com/19158781/52457794-c96ac680-2baf-11e9-9674-af2bafcae18e.png"><img width="252" alt="a_old" src="https://user-images.githubusercontent.com/19158781/52457795-c96ac680-2baf-11e9-940c-19efc055ac12.png">
<img width="252" alt="b_new" src="https://user-images.githubusercontent.com/19158781/52457797-ca035d00-2baf-11e9-930d-0e3d977239a1.png"><img width="252" alt="b_old" src="https://user-images.githubusercontent.com/19158781/52457798-ca035d00-2baf-11e9-85ad-bbfa68795300.png">
<img width="252" alt="c_new" src="https://user-images.githubusercontent.com/19158781/52457799-ca035d00-2baf-11e9-9de5-02633a35ce37.png"><img width="252" alt="c_old" src="https://user-images.githubusercontent.com/19158781/52457800-ca9bf380-2baf-11e9-9ead-622c9f92bbf3.png">
