### ISSUE TITLE
No luck with qsound despite all kinds of troubleshooting

### ISSUE THREAD

**Issue by frustrater** [OpenEmu/OpenEmu#3380]
I've been delighted with opener having loaded hundreds of SNES games I'm now onto MAME, I've again acquired hundreds but the few games I REALLY wanted to play won't run sound (AVP, Punisher, presumably any others with qsound).

I came across the qsound (which is displayed as a screen on booting one game, AVP) I've tried putting it in the games folder, I've unzipped it to put it in the same zip WITH the game but It's already there! But it still won't run with sound!!

It's driving me insane can anyone give any assistance?

(Sierra, OpenEmu 2.05 etc)

I've also had NO luck with CHD despite following all kinds of instructions and youtube grr

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](http://choccyhobnob.com/articles/demystifying-mame-roms/)."

**Comment by frustrater** [comment]
Ha, 'chock hob nob', nice. Tasty those.
To quote a section of the page on that site, though
"OK I understand all that, I still don’t know why my games don’t work."
Because generally all MAME games are working, just a few that don't, the same ones that I've read that other users using the same software and the same games have had success with. Maybe I should just delete it all and re-install because I started with the standard OpenEmu then downloaded the experimental build afterwards.
