### ISSUE TITLE
Unable to import multi disk game

### ISSUE THREAD

**Issue by CaseyDizzy** [OpenEmu/OpenEmu#3389]
I followed the guide, and I completely uninstalled it and deleted all the files from ~library. Started from scratch. when I drag the .m3u into openemu nothing happens. When I attempted to drag the 2 .bin files and the m3u file it scans then nothing, it doesn't put anything in the ~library file either. Just doesn't do anything.

**Comment by clobber** [comment]
You're only supposed to drag in the .m3u file. 

* Make sure none of the files currently exist in folders in your Game Library.
* Search our issues to see if you are experiencing a known bug.
* Read both of our disc guides ([User guide: CD based games](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game) & [User Guide: Required m3u file missing](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Required-m3u-file-missing)).

Besides the few bugs I found and have fixed for next release, if an M3U file doesn't import, it's because you don't have something right so follow the guides closely. Sorry, I can't help you beyond that.
