### ISSUE TITLE
Suikoden for PS1 freezes midgame

### ISSUE THREAD

**Issue by Saefeo** [OpenEmu/OpenEmu#3407]
Hi

I have been playing a long classic Playstation RPG game, Suikoden, for 15 hours when it suddenly freezes after a certain fight in the game. i have rebooted it and tried over and over, but it continues to freeze every time. I would so love to finnish the game, is there anything I can do to try and fix the current game or transfer my save file or something like that? Or skip the part somehow?

Best
Saefeo

**Comment by clobber** [comment]
- Which version of OpenEmu and the Mednafen core plugin?
- Which version and region (US, EU, JP, 1.0/1.1) of the game?
- Is this a [known bug](https://encrypted.google.com/search?hl=en&q=Suikoden%20freeze) in the game?
- Is this freeze repeatable every time?

**Comment by Saefeo** [comment]
Hi again, thank you for getting back to me

1. I have an Apple Macbook air
2. Open Emu is version 2.05
3. It is Suikoden (USA) version 0.1 (.cue)
4. It isn't a known bug. And I can't find any similar problems in the suikosource forum
5. It freezes every time I defeat a boss in the middle of the game. (The Duel between Pahn and Teo Mcdohl). The music goes into repeat mode, as if the game had a scratch (though its not a physical copy), and I can't make any progress in the game from there. I've tried repeating the duel 20 times, but it keeps on freezing the same place, no matter what I do.

I really hope theres a way to get past this place.
Best of hopes, Saefeo

![skaermbillede 2017-11-30 kl 19 50 07](https://user-images.githubusercontent.com/33932448/33449036-df1907fc-d607-11e7-857c-35f0d957e200.png)

**Comment by clobber** [comment]
>It is Suikoden (USA) version 0.1 (.cue)

Do you mean 1.0 or 1.1?

There are known freezes and issues in this game, notoriously so in the initial release which is why they pressed a revised disc. First thing I would try is the 1.1 version if you are not already using it. You will have to rename your mem card save file to match the filename of the 1.1 version. There is information in [this guide](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Required-m3u-file-missing) to figure that out. I'd also be interested in having a copy of your mem card save so I can test this on my own. Upload it to a service such as [transfer.sh](https://transfer.sh/) and link it back here.

**Comment by mortdeus** [comment]
I also run into this issue using a macbook air playing gba games. the entire program freezes and forces me to use force quit.

**Comment by clobber** [comment]
@mortdeus That is not at all the same as this - let's not comment in unrelated issues please. That is a High Sierra bug that is already fixed for our next release.

@Saefeo Any update?

**Comment by Saefeo** [comment]
It was the version of the game. Version 1.1 runs fine, I just switched the save files. Thank you so much   for your help.

Best
Saefeo

**Comment by RafaelOliveira71594** [comment]
We Are Glad It's Working Now
