### ISSUE TITLE
Trouble importing Sega CD game

### ISSUE THREAD

**Issue by bongymo** [OpenEmu/OpenEmu#3418]
I'm attempting to import a Sega CD game into OpenEmu (specifically the European version of Sonic CD), and am having some trouble. The file I have includes numerous .ape files and a .7z file, which I uncompressed into a .ecm file.

I've followed the [instructions in the user guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) on importing CD-based games, and have converted the .ape files to .pcm files, and renamed them to .bin to match the cue sheet using XLD. I also converted the .ecm file into a .bin file using unecm. All the filenames match up exactly as they are listed in the cue sheet, but when I try to import them into OpenEmu, the cue sheet does not import.

Honestly kind of stumped, would appreciate some help.

**Comment by clobber** [comment]
Uh I'm stumped too - I cannot help you without more information. How would you expect anyone to? I need to see all the filenames in the folder of the cue sheet you are trying to import, including the contents of the cue sheet. Honestly though, instead of going through all the trouble, you can just download another proper dump of Sonic CD.

**Comment by bongymo** [comment]
My bad, I just checked and one of the filenames did not match up, it's working fine. Feel kind of dumb now, thank you anyway!
