### ISSUE TITLE
Spy Hunter rom (0.149) doesn't load

### ISSUE THREAD

**Issue by punking006** [OpenEmu/OpenEmu#3424]
I've tried the following 0.149 roms for Spy Hunter

spyhunt.zip
spyhuntp.zip
spyhuntr.zip

spyhunt and spyhuntr gives the message "The emulator could not load ROM:
spyhuntp gives a black screen and locks up openemu.

I'm using v2.0.5

Has anybody else managed to play Spy Hunter? Thanks.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](http://choccyhobnob.com/articles/demystifying-mame-roms/)."
