### ISSUE TITLE
Unable to download cover are for .z64 roms

### ISSUE THREAD

**Issue by jbwzrd213** [OpenEmu/OpenEmu#3429]
Cover art will download for other roms but not for files with the .z64 extension.

**Comment by clobber** [comment]
Header data needs to be added to OpenVGDB for all N64 ROMs in order to pull cover art for non byte swapped dumps, after which OpenEmu will be able to automatically query the database by their headers alone (https://github.com/OpenEmu/OpenEmu/blob/master/OpenEmu/N64/OEN64SystemController.m). Since this is a large, tedious task it will not happen any time soon. The alternative is to use the format of ROM dump that works or to simply drag and drop in your own cover art image on game in your library.

**Comment by grandpixel** [comment]
I don’t understand what is OpenVGDB or byte swapped dumps. What is the format of rom dump that works? All I know is that they are Z64 file inside ZIP. Can you explain in end-user terms? Thanks.

**Comment by clobber** [comment]
The other formats aren't necessary to understand, as you will not easily find them and are based on the hashes of older no-intro sets. Drag and drop in your own cover art as my latest sentence above says to do...
