### ISSUE TITLE
No menu/button for frame advance?

### ISSUE THREAD

**Issue by maskedbyte** [OpenEmu/OpenEmu#3463]
Frame advance is a common feature for all emulators. OpenEmu is the only emulator I have found so far that doesn't support it. I use it often for studying what goes on a little closer. But as far as I know, snes9x and/or higan (talking mainly about SNES here) have frame advance implemented; they do in their standalone applications, at least. It should be a matter of adding "support" for a hotkey/button for it so the user can trigger it, instead of it sitting dormant in the code.

**Comment by clobber** [comment]
OpenEmu drives the emulation loop. We wouldn't be using emulator code for this, but our own frontend implementation so that it is available for all emulator cores. Currently we have code stubbed out for Step Frame Forward and Step Frame Backward. If it makes sense to do so, we will finish it and expose to the frontend. Not at this time though.
