### ISSUE TITLE
Optimization by using Low Resolution mode on games

### ISSUE THREAD

**Issue by danilobytes** [OpenEmu/OpenEmu#3466]
Macs with Retina Display can use the Low Resolution option from the app info screen to improve graphics performance a bit. Of course it will decrease that app resolution but for some that already use low resolution (such as old games that don't need higher resolutions) it makes sense to do so – and the frame rate really goes up, I've tested it.

Well, nobody likes a blurry UI then I ask if it's possible to use Low Resolution mode only on the game screen or something that simulates that option setup while leaving the app UI on retina/default.

**Comment by clobber** [comment]
No, and that won't improve anything.

**Comment by mrvacbob** [comment]
I can see it being faster for some filters, but we can improve this by running the filter up to some size cap, then a faster scaler the rest of the way. Or get faster filters!

**Comment by danilobytes** [comment]
Which filter is the lightest?

**Comment by clobber** [comment]
If you have an old Mac or a slow GPU, you can use:
* Nearest Neighbor (applies no extra filtering, preserving the pixelated look)
* Linear (applies linear interpolation for a smooth/blurry look, best only for N64 or maybe other true 3D consoles)
* **Pixellate** (our default - keeps all the pixel rows and columns at even widths so that there is no horizontal pixel shimmer effect when the image is at a non-integer scale, working around the issue of playing retro games at non-integer scale on a fixed pixel display (LCD) - more info https://youtu.be/uMwBxL5ZlGw?t=654 timestamp 10:54)

None of the emulator core plugins have trouble running at full speed on any Mac that we support (hardware capable of running 10.11 El Capitan or above), with the exception of the very CPU-intensive PS1 and Sega Saturn. GPU-bound N64 may also have issues on slow GPU's. Can't resolve any issues related to CPU or GPU slowness besides getting a faster machine. Simply not fast enough/not enough shader units.
