### ISSUE TITLE
macOS High Sierra Wiimote Pairing Problems

### ISSUE THREAD

**Issue by guac2018** [OpenEmu/OpenEmu#3469]
Hello,

I have been having issues when attempting to pair and use a Wiimote+ with OpenEmu on my Macbook (12", early 2016) running MacOS High Sierra (10.13.2). 

As I follow the [pairing guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing), the Wiimote will vibrate and show up as paired in my bluetooth preferences, but OpenEmu still shows "no available controllers" and does not respond to any input from the controller. 

Just to address potential issues: 
- I am running OpenEmu 2.0.6.1 
- I have removed all previous pairings from my bluetooth preferences prior to attempting a new pairing
- I do not have any 3rd party controller apps/kekts installed, nor have I ever
- I am not running any of the known applications that could be interfering with OpenEmu

Let me know if there is more info I can include. Thanks in advance!

**Comment by clobber** [comment]
It worked for me when I last tried just a few weeks ago and nothing has changed with the latest release. I suppose it could possibly take a few attempts and it seems like you are following the proper steps, so just keep trying. The fact that you say it ends up in Bluetooth preferences but not in OpenEmu Input preferences is very odd. That would imply it is not being paired through OpenEmu, but another application or some other issue on your end. Since I cannot replicate this, there isn't much else I can do to help beyond suggesting you run through all the steps again, making sure you have removed previous pairings again and pressed the red reset button on the Wiimote. Let us know if you figure it out.
