### ISSUE TITLE
OpenEmu won't open

### ISSUE THREAD

**Issue by goleyeth** [OpenEmu/OpenEmu#3481]
I've been running OpenEmu perfectly on OSX 10.11.6 El Capitan for a long time, but I decided to try my hand at using the cheat functions and now I seem to have messed something up. I'm getting the (Foundation._GenericObjCError error 0.) prompt that is referenced in issue #3044, but when I look for ~/Library/Application Support/OpenEmu/Game Library to delete the data as instructed in that post I can't find it because the OpenEmu folder doesn't even exist in my Application Support folder. I tried fully deleting the OpenEmu app and re-downloading it but I'm still getting the same error (I made sure to right click and open with the built in Archive Utility) and I still don't have an OpenEmu folder within the Application Support folder. 

Any help would be greatly appreciated!

**Comment by clobber** [comment]
Using cheat codes could not have placed OpenEmu in an unopenable state.

1. Use the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu.
2. Only unzip using the built-in Archive Utility and no other third party app: Right click on the zip file and select Open With > Archive Utility.
3. The tilde (~) in the path `~/Library/Application Support/OpenEmu/Game Library` refers to your Home folder where ~ is your username. See the [guide here](http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/) since you don't know this.
