### ISSUE TITLE
GenesisPlus Soft-Reset 

### ISSUE THREAD

**Issue by VonnegutFive** [OpenEmu/OpenEmu#3485]
Hey everyone,

I'm not sure if this is the right place to include but I'll mention it anyway.  I understand that Open Emu is utilizing GenesisPlus for Sega games and I can see that they included the soft-reset feature that a few old school games utilize in order to beat them.  I was wondering is this included with Open Emu?  I'm not sure how to download GenesisPlus directly, they mention OpenEmu as a platform that uses it, but I'd just really like to know how I could possibly get soft-reset working in Open Emu for Sega games. 

Thanks!

**Comment by clobber** [comment]
Currently there is no way to do this - our API cannot distinguish between a hard or soft reset and there is no support for core options. The core plugin performs a hard reset (also the default of the emulator) in order to restart the whole console hardware in case of an in-game bug occurring that halts the game. This is one of the things that could be available if we ever add advanced/core options. #1281
