### ISSUE TITLE
Saturn games report controller disconnect if you press left and right at the same time

### ISSUE THREAD

**Issue by VivaLosDoyers** [OpenEmu/OpenEmu#3515]
I tried Megaman 8 in Saturn emulation. I've found that if you press the left and right arrows on the keyboard simultaneously, the system will report that the controller has been disconnected.

This is using the default keyboard mapping.

**Comment by clobber** [comment]
Yeah, some games will bug out if left and right are pressed on the "d-pad" at the same time, since this isn't supposed to be possible in the first place. Obviously you want to use a real gamepad instead of a keyboard, and nothing can be done aside from adding some extra logic in the core implementation to ignore simultaneous inputs.
