### ISSUE TITLE
Way to disable 2p-4p?

### ISSUE THREAD

**Issue by juanshot2** [OpenEmu/OpenEmu#3519]
Playing N64 on Mupen64Plus 2.5.4 and the emulator automatically assigns 2P - 4P to keyboard

This means on certain games an opponent must be played by 2P

Is there anyway to disable 2P-4P (i.e. not assign them keyboard , or anything) ?

**Comment by clobber** [comment]
The emulator is configured to have all virtual N64 controllers plugged in. Most (all?) N64 games allowed you to play single player despite having all controllers plugged in, where sometimes you had to deselect the additional controllers on an options/config screen before playing. Maybe that the case with whatever game you are trying? There is no other way to disable them in the UI.

**Comment by ancarda** [comment]
Could we re-open this issue?

Even single player games can be affected by this, for instance the [Wind Waker randomizer](https://github.com/LagoLunatic/wwrando), when built from source, will inject a noisy profiler which only shows up if there's a controller on port 3: https://github.com/LagoLunatic/wwrando/issues/306

In this particular case, there are some workarounds -- running the production build of wwrando in a Windows VM, or disabling the code before running -- but it would be easiest if OpenEmu could allow ports 2, 3, and 4 to be disabled

Is this caused by the fact not every core supports disabling ports? It would be fine if "Input: None" were available for some platforms, like N64 and GameCube, even if not every platform offered that
