### ISSUE TITLE
Warning Sign on Some Cores?

### ISSUE THREAD

**Issue by bwhite201** [OpenEmu/OpenEmu#3528]
So I just compiled OpenEmu through GitHub through the Terminal. The installation went smoothly, with no issues and all my tested games running fine. But when I went into the library section of the preferences tab I saw that near some cores (such as the 4do core shown in the picture) There was a warning symbol next to its name and I couldn't do anything with it. Could somebody explain what that means? Maybe a way to run the cores? I'm a little confused here. 
<img width="461" alt="screen shot 2018-02-14 at 7 55 05 pm" src="https://user-images.githubusercontent.com/30762895/36241381-d607cf82-11ca-11e8-80ff-7a123f82a7ce.png">

**Comment by clobber** [comment]
It means there is no core plugin available. That is what happens when you compile from source for "experimental" - it includes some system plugins for in which there are no cores. Since you have no need to build from source, it is best to use a pre-compiled bundle from here: https://github.com/OpenEmu/OpenEmu/releases/latest
