### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by 1900forever** [OpenEmu/OpenEmu#3544]
i was trying to compile the latest code and the following error popped up

> 
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/yan/Library/Developer/Xcode/DerivedData/OpenEmu-gavmlegqhpvvaneukshebrfoznzk/Build/Intermediates.noindex/FCEU.build/Release/FCEU.build/Objects-normal/x86_64/cheat.o src/cheat.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by clobber** [comment]
I don't think I can replicate that, and you didn't specify which version of Xcode or give the full error output. Anyway, you don't have any reason to build the app + the core plugins, since those haven't changed. Just follow the guide and compile only the application with the follow 3 commands. https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide#cloning--compiling

**Comment by 1900forever** [comment]
i was using xcode 9.2 on macos 10.13.3, and i simply used
`xcodebuild -workspace OpenEmu.xcworkspace -scheme "Build All + Experimental" -configuration Release`
