### ISSUE TITLE
Vulkan support using MoltenVK

### ISSUE THREAD

**Issue by chrisballinger** [OpenEmu/OpenEmu#3545]
A number of emulators now include Vulkan graphics backends. It's now possible to support most cross-platform Vulkan code using the newly open-sourced [MoltenVK](https://github.com/KhronosGroup/MoltenVK/). MoltenVK translates Vulkan calls into Metal, allowing for new features and potentially higher performance than macOS's ancient OpenGL stack.

Here's a few emulator cores with Vulkan backends:

* Mednafen/PSX https://github.com/libretro/beetle-psx-libretro
* Mupen64Plus/N64 https://github.com/libretro/parallel-n64

Not really a feature request, just wanted to spread awareness. I don't think OpenEmu has any cores with Vulkan support yet, but it could be something to consider when pulling upstream cores in the future.

**Comment by clobber** [comment]
Those are pretty hacked up forks that we won't be using, but we are already aware of them. Our only 3D-accerated core plugin is obviously Mupen64Plus, so some sort of Vulkan-Metal compat layer isn't useful to us. The upside is that eventually our shader system and main render will support Metal, but there is no urgent need for it as we are 99% 2D/software rendering cores here.

**Comment by mrvacbob** [comment]
I am willing to believe in this for PS2/Dreamcast/etc when the time comes.

N64, PSP, and our main renderer should go Metal someday, but we should do it to make things more stable/accurate rather than faster.

**Comment by mrvacbob** [comment]
There's one called Play! that'll at least boot on 64-bit Macs - looks like the last build was 2017/8/29 which isn't great. I made a very very alpha-quality core for it in a GitHub repo here somewhere.

**Comment by chrisballinger** [comment]
Btw after I made this issue someone emailed me directly about some experimental cores they were working on that seem pretty cool. It seems that there are many people working on experimental cores, but no central place to discover and help get these individual authors get their cores off the ground. I was wondering if it would be okay if I started a wiki page to list the various non-official cores (linking to source code repositories only) so developers see what other people are working on and help each other out.

**Comment by clobber** [comment]
>Btw after I made this issue someone emailed me directly about some experimental cores they were working on that seem pretty cool

Who was it and what were they?

> was wondering if it would be okay if I started a wiki page to list the various non-official cores

We already have a wiki page for the various core ports. As an aside, just making it clear that experimental and WIP/alpha stuff is officially unsupported by us and won't be shipped out. Some are in various states of compatibility, others aren't a good fit for OpenEmu. I have to manage expectations about these for users because they may never be available, and we definitely don't want the support burden for something that barely works or has 50% compat. Anyway, wiki is here:
https://github.com/OpenEmu/OpenEmu/wiki/Console---Core-Plugin-Status-&-Wishlist#work-in-progress-ports

**Comment by duckey77** [comment]
Hey Clobber,  I sent him an email about some of my work on my unofficial cores, and my interest in MoltenVK   All unofficial and not as part of the OpenEmu community.  Sorry that is caused any issues.  It won't happen again.

**Comment by chrisballinger** [comment]
@duckey77 I feel like open communication and collaboration are at the heart of open source software. I don't think you should censor yourself, and you should be proud of your work. I don't think that was the intention of @clobber's post, if anything, quite the opposite. Looks to me like you should add your work-in-progress to [this list](https://github.com/OpenEmu/OpenEmu/wiki/Console---Core-Plugin-Status-&-Wishlist#work-in-progress-ports) so it's more discoverable! As long as that page isn't linking to binaries, I don't think there is a chance that adventurous end users will be asking for support.

**Comment by clobber** [comment]
We are aware of @duckey77's couple external WIP ports. In fact he's a team member here with push access who has contributed much help, so he should already know the deal on those and shouldn't feel that for some reason his work isn't appreciated. Anyway, this issue is growing outside of the original Vulkan fork port discussion, which is irrelevant to our purposes.

>I don't think there is a chance that adventurous end users will be asking for support

Actually, we get those from time to time. I just got one 30 minutes ago, and it's annoying. :P

**Comment by chrisballinger** [comment]
Lol, I know the feeling. Sorry for veering OT. Glad to hear y'all are working together.

Thank you all for your amazing work!
