### ISSUE TITLE
Genesis aspect ratio is not corrected

### ISSUE THREAD

**Issue by timsoret** [OpenEmu/OpenEmu#3553]
Hello dear devs.
First, thanks for OpenEmu. Incredible app.
I'm struggling to capture pixel-perfect footage of some old Genesis games, as exotic resolutions appear stretched, instead of 1:1 pixel ratio.

Flashback: Quest for Identity
Original: 256x224
OpenEmu: 300x224 (stretched)

Aladdin
Original & OpenEmu: 320x240 (pixel perfect)

Is it a bug, are you enforcing 4:3, and if yes, how can I get a 1:1 pixel ratio?

**Comment by clobber** [comment]
Yes, the aspect ratio correction for Genesis/Mega Drive is indeed wrong - it hasn't actually been fixed yet: https://github.com/OpenEmu/GenesisPlus-Core/blob/master/GenPlusGameCore.m#L315

Since the Genesis VDP uses the TMS9918 [dot cock rate](https://pineight.com/mw/index.php?title=Dot_clock_rates), like all other systems around that time, a 256px image outputted to a 4:3 CRT TV will actually come out to 256 * 8/7 PAR (~1.143:1) = ~292 pixels wide (more info http://wiki.nesdev.com/w/index.php/Overscan). This will soon be fixed in a core plugin update. Our current policy is to display all games as they would have looked on a CRT in order to preserve the original look of the pixels, so there is not a "1:1 Pixel Perfect" option as you are alluding to for showing the native aspect (that being considered an emulator/incorrect look since nobody would actually see the games this way).

To answer your question, we do enforce correct aspect ratios on the rest of the systems and there is no way to get a different ratio except for in [screenshots](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Preferences:-Secrets) (although this probably won't work correctly for Genesis at the moment).

**Comment by timsoret** [comment]
That's very informative, thank you.
Well as long as you provide the fix soon, even with a slight stretch for match 4:3 like good old times, that should be fine. Right now it just feels incorrect. A 1:1 pixel ratio option would be welcome one day, but I understand if that's too much work.

**Comment by clobber** [comment]
https://github.com/OpenEmu/GenesisPlus-Core/commit/c06e10d45871e2ac95371d5e3c80385db7f41797

This is fixed now so that both 320px and 256px modes are corrected to their proper NTSC CRT aspect ratio (292px wide).

Restart the app and an updated Genesis Plus GX core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for GenesisPlus 1.7.4.8.

Note: There is a bug in the frontend where scaling will be slightly off for 320px mode Genesis games when using the popout gameplay window. This will be fixed in the next OpenEmu update.
