### ISSUE TITLE
MAME roms not working/transfering

### ISSUE THREAD

**Issue by nokiot9** [OpenEmu/OpenEmu#3555]
So I downloaded a bunch of those massive MAME packs from emu paradise and a good 30% of the titles don't work. and when I delete them (click delete on my keyboard) and try to replace them with a hand picked replacement (drag and drop from downloads onto UI window), the replacement files don't show up. Sometimes the uploader down in the corner will say there is issues with files, but usually it doesn't do anything. Has anyone else had this issue with the titles not working? Or the files not transferring? Even some that don't seem to be in there at all that I pick individually won't appear in the menu after I drag the files over.
<img width="1578" alt="screen shot 2018-03-09 at 6 56 27 am" src="https://user-images.githubusercontent.com/37216506/37210770-21e1d5f8-2367-11e8-985a-ab96a67b2d98.png">

**Comment by nokiot9** [comment]
also when you're transferring roms, and it says there are issues that need to be resolved, and they're all .bin files, I just click the "don't import selected" right? will it still know where they are? or do I need to select the proper system? 
<img width="1133" alt="screen shot 2018-03-09 at 7 14 29 am" src="https://user-images.githubusercontent.com/37216506/37211555-8d5ce410-2369-11e8-80ba-d668c6fe8be3.png">

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](http://choccyhobnob.com/articles/demystifying-mame-roms/)."
