### ISSUE TITLE
changing the language

### ISSUE THREAD

**Issue by B-o-i** [OpenEmu/OpenEmu#3558]
i got openemu and opened it but it is in spanish :/ how do i change the language?

**Comment by shysaur** [comment]
By default, the language of OpenEmu is determined by macOS. Is your system language a language other than English?

**Comment by B-o-i** [comment]
yes, it's swedish

**Comment by shysaur** [comment]
Ok, then the issue is that there is no Swedish translation for OpenEmu, and you have Spanish in the preferred language list in system preferences.

Go to System Preferences -> Language and Region (the icon with a blue flag) and make sure that English is the second language in the list. The languages in the list can be reordered by dragging them with the mouse, and can be added with the +/- button below the list.
