### ISSUE TITLE
OpenEmu PSP Emalutaor Crashes when Downloading

### ISSUE THREAD

**Issue by kurranp** [OpenEmu/OpenEmu#3561]
Im downloading tekken 5 dr and I've extracted the file into an .io but it crashes every time I load it into the PSP emulator. Mac OS X. PLEASE HELP :(

**Comment by clobber** [comment]
I cannot replicate a crash on import having tested 3 versions of this game (USA, Europe, Europe v2), which leads me to believe that you either extracted the files incorrectly or have a bad dump of the game. Redownload another copy, extract the file using [The Unarchiver](https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12) and unrar any resulting split rar files using our guide: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Split-rar-files

**Comment by clobber** [comment]
@kurranp Where did you download the copy of this game? I need to see what's up with the header in order to replicate the crash. Also, please do the following:

1. Download and install [Hex Fiend](https://github.com/ridiculousfish/HexFiend/releases/download/v2.7.0/Hex_Fiend_2.7.dmg)
2. Open Hex Fiend and then open (Cmd+O) the PSP ISO you are trying to import (the one that causes the crash).
3. Press Cmd+F (Find), make sure the "Text" tab is selected and then in the field type `DISC_ID` **then click "Next" twice**.
4. Take a [screenshot](https://support.apple.com/en-us/HT201361) of the window and [upload](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) it back here.

What I'm wanting will look like this:
<img width="537" alt="screen shot 2018-04-22 at 2 54 01 pm" src="https://user-images.githubusercontent.com/1303132/39099319-96c1610a-463e-11e8-9976-e2e1b98d9897.png">

**Comment by clobber** [comment]
So my theory on this is that people are extracting multi-part/split rar's incorrectly ([due to the nature of rips available and lack of understanding](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Split-rar-files)), where only the very first rar gets extracted. They import and it gets detected as a PSP game, because the initial magic word string ("PSP GAME" at offset 0x8008) is in the beginning of the file but the actual header containing all the required information to pull the Disc ID (serial) is buried deeper in the ISO which cannot be found because they have an incomplete file. I verified this crash through some testing, but making a robust check for *complete* PSP games may slow down their import so I will decide what to do later. For now, the inserting nil into an NSMutableString crash serves as a somewhat safeguard against importing bad/incomplete files, which will definitely cause a bigger troubleshooting problem. :P
