### ISSUE TITLE
Does not switch to dedicated graphic card

### ISSUE THREAD

**Issue by SirKalrin** [OpenEmu/OpenEmu#3562]
Hello!
I have the issue of huge frame rate drop when using the SABR filter in fullscreen.
Yesterday when first using OpenEmu, I did not have this issue.
I can solve this by turning off my auto switch on graphic cards (intergrated/dedicated), tho this is rather annoying when using the function for all other applications, but everything runs smoothly!

I am using a MacBook Pro 2017. (7. gen 2.9 GHz CPU, 16GB ram, HDGraphics630 1.5GB/RadeonPro560 4GB, HighSierra OSX)
When I watch my Activity Monitor, I see that OpenEmu does not require high performance graphics.
Is there any way to change this/force OpenEmu to require the dedicated grapgics? So the autoswitch will switch properly to dedicated when I launch a game?

Kindly Regards
SirKalrin

**Comment by clobber** [comment]
This is by design so OpenEmu can be as low resource/power as possible, and there is no option to change it. There seems to be a driver bug or something going on with the Intel GPU's in the new MacBook Pro's - I've seen reports of fullscreen performance being bad as well. This is possibly an issue that will sort itself out in a future macOS update. On an older MBP, I can run all the shaders fine with an Intel Iris Pro. For now, you will have to rely on manually switching to your dedicated GPU either through System Preferences or a tool like gfxCardStatus.
