### ISSUE TITLE
Couldn't communicate with helper application 

### ISSUE THREAD

**Issue by BenCosmos** [OpenEmu/OpenEmu#3564]
Hi there! I really love OpenEmu so I hope someone can help me with this. I am using the latest version OpenEmu v2.0.6.1 on Mac OSHigh Sierra.
The problem is that with some emulators whenever I start a game I get nothing but a black screen. When I quit I get this message, "Couldn't communicate with helper application." 
But the only one I care to get fixed is the ppsspp a.k.a sony psp.
I'm not sure this is will help you but here is some things I am apparently missing.
<img width="420" alt="screen shot 2018-03-20 at 9 40 58 am" src="https://user-images.githubusercontent.com/37565254/37693560-dd6417e0-2c96-11e8-9ba1-2d6e89728522.png">
<img width="424" alt="screen shot 2018-03-20 at 9 41 22 am" src="https://user-images.githubusercontent.com/37565254/37693561-dd74b69a-2c96-11e8-9f29-a1478268ff18.png">
<img width="423" alt="screen shot 2018-03-20 at 9 41 42 am" src="https://user-images.githubusercontent.com/37565254/37693562-dd832c7a-2c96-11e8-8e80-a48887130fb9.png">
<img width="419" alt="screen shot 2018-03-20 at 9 41 56 am" src="https://user-images.githubusercontent.com/37565254/37693563-dd9779be-2c96-11e8-9e1c-24bba0f27732.png">
<img width="423" alt="screen shot 2018-03-20 at 9 42 03 am" src="https://user-images.githubusercontent.com/37565254/37693565-de8e5c3e-2c96-11e8-8a7a-157bddcab222.png">

Thank you for your time and help.

**Comment by clobber** [comment]
Lacking on details here, and the BIOS preferences has nothing to do with your problem. It sounds like for whatever system (PSP???) your game is crashing. This is due to a game or save state compatibility problem, possibly with an autosave state trying to restore on launch. In both cases, there is nothing much you can do about the current save state (or lack of compatibility) if that is indeed the problem. Try the following to get it to load:

* In the app, go to OpenEmu > Preferences > Library, click "Reset warnings"
* Open your game and click "No" when prompted to "Continue where you left off"
