### ISSUE TITLE
OpenEmu is very slow

### ISSUE THREAD

**Issue by MarioBrossss** [OpenEmu/OpenEmu#3565]
Hi. Not so sure what's going on but OpenEmu is running extremely slow. It glitches, drops frames, there is a lot of latency when pressing buttons. Any ideas on what I could be missing? 
My Setup should be more than enough:

macOS High Sierra v10.13.3
Macbook Pro (Retina, 15-inch, Mid 2014)
Memory 16 GB 1600 MHz DDR3
Graphics NVIDIA GeForce GT 750M 2 GB

OpenEmu v2.0.6.1
Filter: Pixelate or Nearest Neighbour

I mean, it should be fine, right? But it's really not

What's wrong? Some incompatibility with macOS High Sierra? Any ideas?

I only tried SNES with Super Mario World, Super Mario All Stars. And NES with Super Mario Bros and Super Mario Bros 3.

Thanks a lot

**Comment by clobber** [comment]
When doing what? Just running OpenEmu and any of those games? No other apps running in the background? None of those games should have 'glitches' but you haven't exactly described what that is. Sounds like something weird going on your end, maybe with the integrated GPU. Try forcing the discrete GPU with an app like gfxCardStatus or in System Preferences > Energy Saver to see if that makes a difference. Or maybe you need an old fashioned restart.

**Comment by danilobytes** [comment]
I can confirm this issue. OpenEmu started performing like this since some latest versions, I can't remember them specifically. But it was just fine. So I don't think it could be my machine, which is working just like before with other apps. However I noticed that if I turn Low Resolution mode on (or just decrease my resolution) it works smoothly again. Any chance of considering this issue?

**Comment by clobber** [comment]
@danilobytes "Me too" isn't helpful. Which Mac, what are the specs? Which version of macOS? Happens with all systems or only certain system/games? Happens with all filters or only certain?

**Comment by danilobytes** [comment]
Oh sorry.

macOS High Sierra v10.13.3
MacBook Pro (Retina, 13-inch, Early 2015)
Processor 2.7 GHz Intel Core i5
Memory 8 GB 1867 MHz DDR3
Graphics Intel Iris Graphics 6100 1536 MB
OpenEmu v2.0.6.1

It happens with all systems I use: Nintendo DS, PlayStation, PSP and SNES. Without difference between games. I have tested all filters and the behavior remains the same, consistent framerate drops.

**Comment by clobber** [comment]
You experience the same behavior as above (glitches, delayed input)? Because that sounds very extreme. First you said you "can confirm this issue" and now you say "consistent framerate drops." Please be clear to ensure you are not exaggerating or mistaking your issue from theirs. If you are running your display at a higher scaled resolution than the default, it's possible your GPU is too slow or there is a driver bug. It's also possible there is an issue relating to what we discussed in https://github.com/OpenEmu/OpenEmu/issues/3466. As far as I know, none of us on the dev team have a Mac with your configuration, so it will be difficult to troubleshoot your particular GPU (Intel Iris Graphics 6100).

**Comment by danilobytes** [comment]
I did some testing with the default resolution (still Retina, but default scale) and it seems that the framerate drop remains the same. Therefore we can conclude that my machine is only capable of running OpenEmu at a decent framerate if using Low Resolution mode or lowering the Mac resolution below Retina. I have some other applications open but if I recall correctly it does not make much of a difference running only OpenEmu. What is interesting is that I can run some similar Steam games better than on the emulator.

Anyway thank you @clobber for your time and explanations. I will no longer bother on this matter.

**Comment by clobber** [comment]
The "frame drops" is something that has existed in OpenEmu since the beginning, and will exist in any emulator depending on how they handle syncing (or not). This is due to games running at a faster rate than the refresh rate of your display. So every 10 seconds you may notice a dropped frame. This doesn't cause any 'glitches' though and running OpenEmu using Low Resolution should not correct it either. If you are experiencing this, it's far from the original issue described...you can't just say you confirm it's the same thing (running extremely slow) when it's totally not. If this is not what you are experiencing, then I would need to see video footage.

**Comment by danilobytes** [comment]
Sorry for the misunderstanding and confusion. It's now clear that they are different issues.
