### ISSUE TITLE
Not able to choose cheat code type when adding cheats GBA

### ISSUE THREAD

**Issue by MrDemocracy** [OpenEmu/OpenEmu#3572]
There is no way to choose what cheat code type I'm adding when I add a new cheat code (e.g. GameShark, Action Replay, CodeBreaker).
Because of this, I've had no codes working with OpenEmu. If I add the same codes on mGBA, it works just fine.

It would also be nice if I could rename and edit already added codes.

**Comment by clobber** [comment]
Normally, core plugins are able to automatically detect the cheat code type. This exception is Action Replay v3 for GBA and you can read all the details in the guide: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes#gba-cheats - we're waiting on the possibility of a heuristic to autodetect them. Probably won't add a checkbox for that edge case unless we absolutely have to.

I believe a Cheats Manager is being worked on by @drhr which will close issue #782

**Comment by drhr** [comment]
@clobber That's correct. I overestimated my free time, but am hoping to squeeze it in in the next few weeks.

**Comment by clobber** [comment]
@drhr Just pinging to see if you've had any free time on the Cheats Manager. By the way, if you want to keep in touch with dev activity easier, we've switched to a Discord server. Can drop by the old IRC channel and I'll send you the invite link.

**Comment by clobber** [comment]
@drhr Checking in to see if you still have interest in this, otherwise do you have a partial implementation you'd like to open source so that others can pick it up?

**Comment by drharrisusc** [comment]
@clobber Apologies for the disappearing act, I got clobbered with RSI and heavy workload and kinda threw my hands up in the air on side projects, if you'll allow the puns. I should have done a better job staying in touch.

I won't be able to continue work on this, but have a look at my `cheat-manager` branch on my fork. The UI still needs to be developed - I went down a road with it but scrapped it. I think we discussed having another menu option in the main GUI window, but I thought a popup would work better for adding cheats to a running ROM. I was about to write some sort of cheat window/popup class that inherited from your existing window code/styles, but didn't get that far.

Another intention was to set up a series of asynchronous loads from various sources, carving out room for a load from your central cheat DB (with caching?) even it was just a nop for now, possibly with a promise/future lib if you guys were using one or just a series of callbacks.

It's been quite a while since I merged the upstream, so you might need to sort out the db model name/version if that's been updated since.
