### ISSUE TITLE
Input not working properly

### ISSUE THREAD

**Issue by knightofjaffa** [OpenEmu/OpenEmu#3596]
the special keys are working however the gameplay keys are not

**Comment by clobber** [comment]
Not our bug. See your last issue. #3595

**Comment by knightofjaffa** [comment]
i have done what the input troubleshooting guide says and it is still not working

**Comment by clobber** [comment]
Sorry, it's still not our bug. Issues with input not working, especially ones I cannot replicate, pertain to the user's end. I just tried this game and pressed Enter on my keyboard (Start) and it works just fine.

Your issue is in the [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) guide or something close to it. I cannot help you beyond that.
