### ISSUE TITLE
Support for Parallel N64 core

### ISSUE THREAD

**Issue by ReallyReally17** [OpenEmu/OpenEmu#3607]
Mupen64plus runs terrible on my MacBook Pro (2011). Sure, my system can run Tomb Raider Anniversary (2007) fine at 1200x800 with 4XAA turned on and all options enabled, it just can't handle the title screen of Super Mario 64 without skipping.

No games are playable. 

However, the Parallel N64 core on RetroArch works just fine. I can Turok 3 on my system with it.  

Is it possible to add the Parallel N64 core to OpenEmu?

**Comment by clobber** [comment]
Not possible. We only support stable release Mupen64Plus paired with the [GLideN64](https://github.com/gonetz/GLideN64) GPU plugin as our main N64 core plugin. Parallel N64 is a modified version of Mupen64Plus, featuring a Vulkan-optimized renderer which will provide no benefit on Mac, especially your 2011 MBP with an old/slow GPU (Intel HD Graphics 3000) that does not even support Metal *or* Vulkan. Some notes:

* Your issue isn't Mupen64Plus running slow, but the current iteration of GLideN64 used which your old/slow GPU (Intel HD Graphics 3000) has issue with. This is issue #3447 
* Performance with GLideN64 may improve over time for old GPU's, but that is unlikely. They are missing modern features and more/faster shader units which GLideN64 takes advantage of.
* If you have a 15''/17'' 2011 MacBook Pro with the dual GPU configuration (AMD Radeon HD 6490M/6750M/6770M) you may get better performance by forcing the discrete GPU with an app like [gfxCardStatus](https://gfx.io/) or in System Preferences > Energy Saver.
* You are noticing playable performance with Parallel N64 because you are using it paired with an obsolete GPU plugin for low spec GPU's, either Rice or Glide64 (not to be confused with GLideN64). These are buggy, less compatible, no longer actively developed, and made obsolete by Gonetz' modern "GLideN64" plugin.
* We are not going to support any of the obsolete GPU plugins (Rice or Glide64).
* The comparison between the performance of a PC game (Tomb Raider Anniversary) versus the emulation in a GPU plugin using modern GL programming (GLSL shader heavy) for an N64 emulator is very irrelevant.
