### ISSUE TITLE
🚨(macOS 10.14 Mojave)🚨 Crashes on launch

### ISSUE THREAD

**Issue by gh0sti** [OpenEmu/OpenEmu#3635]
do you guys want the error report of when it crashes?
I know its a beta and I am not expecting any updates for awhile just thought I would let you know that it crashes.

**Comment by LoganDark** [comment]
So basically:
- We use Mojave to test new features and report bugs.
- When we report a bug, we are told not to use Mojave because it's for testing.

I think you should, like, maybe consider fixing the bug, because we are testing this for you and we're reporting bugs that need to be fixed. It's not a "this is a beta, so just leave things broken". It's a "here's a bug you can fix before the general public gets it".

I don't mean to offend in any way, but in all honesty I think your response of "don't use Mojave" is ridiculous in this situation. You should, in my opinion, try to make it play nice with Mojave, as it's the latest version, *regardless of whether it's a beta or not*.

**Comment by clobber** [comment]
Temporarily addressed with commit https://github.com/OpenEmu/OpenEmu/commit/19d82c94c4e1e1f8b046798fd1d1d8420ee4132c

**Comment by clobber** [comment]
This issue has been fixed but will remain open for some time in order to catch those that have upgraded to 10.14 Mojave before upgrading to 2.0.7. To fix this crash, download the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu.
