### ISSUE TITLE
OpenEmu Player Start button on mapped NES usb controller not working.

### ISSUE THREAD

**Issue by Joh221** [OpenEmu/OpenEmu#3643]
Everything works great except the start button. I'm on a MAC. I have restarted and an not using any conflicting programs ie Chrome. Trying to play Gauntlet on MAME.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](http://choccyhobnob.com/articles/demystifying-mame-roms/)."
