### ISSUE TITLE
Joy Con as a light gun for MAME shooters

### ISSUE THREAD

**Issue by Natmans** [OpenEmu/OpenEmu#3656]
When I learned about the Joy-Cons, I noticed that a couple of games, such as World of Goo, supports the motion controls on those controllers. 
This got me into thinking: will these controllers work in the same vein as a Wiimote if I play my light gun games on the OpenEmu emulator, including Lethal Enforcers and Mad Dog McCree?

**Comment by clobber** [comment]
Joy-Cons are unsupported in any form: #3093 

Arcade/MAME:

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](http://choccyhobnob.com/articles/demystifying-mame-roms/)."
