### ISSUE TITLE
Persona 3 Portable (PSP)- Texture Pack

### ISSUE THREAD

**Issue by LastChalice** [OpenEmu/OpenEmu#3705]
Hello everyone. 
I was just wondering how to add textures to the PPSSPP core of openemu. 
Right now, I am playing Persona 3 Portable, and I while I love the game, the graphics are so-so. 
I just found an HD Texture pack link [here](https://forums.ppsspp.org/showthread.php?tid=23509), but I couldn't find any instructions other than the ones pertaining specifically to PPSSPP. 
Having some help to install it would do wonders for my computer and my experience.

Thanks in advance guys!

P.S. -- Is the core stable enough to support such a mod?
System -- macbook Air, 2017
MacOs- High Sierra

**Comment by clobber** [comment]
They would be placed in `~/Library/Application Support/OpenEmu/PPSSPP/PSP` (~ meaning your Home folder where ~ is your username. Guide [here](http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/) if you don't know this.), and then create a folder named `TEXTURES` and then another folder inside that named `ULUS10512` (the game serial), so ultimate your path would be `~/Library/Application Support/OpenEmu/PPSSPP/PSP/TEXTURES/ULUS10512`.

That said, I doubt this using texture replacement packs will work using our core plugin because there is no setting exposed to tick/untick the "Replace textures" option.
