### ISSUE TITLE
Most Mame games not working 

### ISSUE THREAD

**Issue by sohojohn84** [OpenEmu/OpenEmu#3709]
Hello, 

I was running the experimental version of Openemu on my macbook pro from 2012 and everything was working seamlessly. I had the Arcade console setup, the bios files dropped on Openemu and I could drop any game and it would work.

I just purchased a 2018 Macbook pro, running on High Sierra, installed the experimental pack (v 2.0.6.1), dropped in the same bios files (Mame bios) and now most Mame games won't work.

Anyone could help?

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](http://choccyhobnob.com/articles/demystifying-mame-roms/)."
