### ISSUE TITLE
how to enter bios settings for neogeo games?

### ISSUE THREAD

**Issue by xpacificsoda** [OpenEmu/OpenEmu#3736]
I wanted to set game level in bios settings and found no where to set.

**Comment by clobber** [comment]
#1860

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](http://choccyhobnob.com/articles/demystifying-mame-roms/)."

**Comment by xpacificsoda** [comment]
> #1860
> 
> [Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](http://choccyhobnob.com/articles/demystifying-mame-roms/)."

thx!
