### ISSUE TITLE
Resize screen after 2.0.7 update

### ISSUE THREAD

**Issue by gh0sti** [OpenEmu/OpenEmu#3743]
btw thank you guys so much for fixing this app for macos 10.14 love the update after waiting all summer I really appreciate the hard work put into fixing the app. Anyways I can't resize the window when playing games since 2.0.7. And if I try minimizing the window the app stops working and I have to force close the app to restart it.

**Comment by clobber** [comment]
Going to need better details than that. I can't replicate the problem, so please provide exact steps.

**Comment by gh0sti** [comment]
I can resize the window after I put it into full screen and take it out of full screen by chance do you use the app better touch tool?

**Comment by clobber** [comment]
I do not use BetterTouchTool. I'm not sure the issue you are experiencing is related to the latest update either.

**Comment by gh0sti** [comment]
launch any game, notice the black boarder is pure black and I can't move the window at all
<img width="962" alt="screen shot 2018-09-19 at 9 50 57 pm" src="https://user-images.githubusercontent.com/4202657/45793110-2b08b380-bc56-11e8-90bd-44e69947add6.png">

after putting the screen into full screen and taking it out of full screen take a look at the board its now gray and I can move the window around

<img width="956" alt="screen shot 2018-09-19 at 9 52 31 pm" src="https://user-images.githubusercontent.com/4202657/45793153-568b9e00-bc56-11e8-9c45-f756c544c339.png">

**Comment by clobber** [comment]
You need to learn to be more specific and not generalize your problems. I cannot help you if the N64 core plugin is crashing - it's due to compatibility issues with the core emulator and GPU plugin.

First:
* You need to have the Mupen64Plus 2.5.5 core plugin
* If you for some reason edited the version number locally on an older plugin, you need to delete it and redownload the latest from us in-app (OpenEmu > Preferences > Cores).

To work around your loading/crashing issue with GoldenEye:
* In the app, go to OpenEmu > Preferences > Library, click "Reset warnings"
* Open your game and click "No" when prompted to "Continue where you left off"

**Comment by gh0sti** [comment]
This has nothing to do with it crashing, and all my cores are up to date. All I am talking about is resizing the window, it happens with all the cores I launch I have to put it into full screen mode then take it out of full screen to move and resize the screen.

**Comment by clobber** [comment]
Provide more details. Find precise conditions this happens under with exact steps to replicate, otherwise we cannot help you. I don't know how to be more clear than that.
