### ISSUE TITLE
MultiPatch not working with PPF patch

### ISSUE THREAD

**Issue by pleasejust** [OpenEmu/OpenEmu#3749]
Loading SotN [SLUS-00067 (crc32: 05BE47B2)] .cue file works fine. Sotn show in the library and autoloads the cover. yay. I used multipatch to apply hardtype 8.1 hack ppf file to the SotN bin. Changed where it says FILE "..." BINARY to the new name of the bin multipatch created. Drag and dropping the cue in library window does nothing. Nothing shows up. It worked before with previous Openemu version. FYI heads up. Anyone know how to fix this? Thanks..

EDIT: My bad.. I don't know if it worked before. I don't think so. Before, with previous version of Openemu, I loaded the hack with an unchanged cue file, so who it probably didn't work in the first place. So any way to make them work? Thanks.

**Comment by clobber** [comment]
This is **NOT** our problem. We are not the MultiPatch support center. MultiPatch doesn't appear to be patching the binary correctly (from the assumed [patch file](https://www.romhacking.net/hacks/2896/)), resulting in a ~75MB file of zeroes. Of course OpenEmu won't allow garbage to import, because it is **not** a valid PS1 game. You're an idiot. Do not post another issue here again.

<img width="1515" alt="screen shot 2018-09-20 at 7 48 11 pm" src="https://user-images.githubusercontent.com/1303132/45853973-2b648580-bd0e-11e8-930f-7eb4dda6fa4a.png">
