### ISSUE TITLE
能否给Snes9x增加一个高级选项 BlockInvalidVRAMAccess 关闭VRAM对这项操作

### ISSUE THREAD

**Issue by mingminglin** [OpenEmu/OpenEmu#3750]
能否给Snes9x增加一个高级选项 BlockInvalidVRAMAccess 关闭VRAM对这项操作，原因http://bbs.fireemblem.net/read.php?tid=249003

**Comment by clobber** [comment]
We speak English here.

The setting `BlockInvalidVRAMAccessMaster` is enabled and is going to stay enabled because those games are doing something that cannot be done on real hardware. Tell the ROM hackers to fix their crappy hacks.

https://github.com/OpenEmu/SNES9x-Core/blob/972d9bb82ec6a80d910ad0a969d153584c70670a/SNESGameCore.mm#L178
