### ISSUE TITLE
Add mGBA to list of Game Boy cores

### ISSUE THREAD

**Issue by tebruno99** [OpenEmu/OpenEmu#3765]
Would it be possible to allow mGBA to be added to the Game Boy list of cores? Over the years I've built up an extensive list of save files from mGBA using various homebrew devices and would like the ability to port these over to OpenEMU.

- OpenEmu Version: 2.0.7
- macOS Version: 10.14

**Comment by clobber** [comment]
Not ready to support multiple Game Boy cores, especially since mGBA's is still very much a WIP, but you can pretty much use the guide below to infer out how to copy your in-game battery save files over to the folder that Gambatte needs to see them in:

https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files

They would obviously go in `‎⁨~/Library⁩/Application Support⁩/OpenEmu⁩/Gambatte⁩/Battery Saves⁩` and be named `Your_ROM_Filename.sav`
