### ISSUE TITLE
Unlimited Sprites Mode in Nestopia

### ISSUE THREAD

**Issue by JoaoPinheiro** [OpenEmu/OpenEmu#3771]
Is there any way to enable the Unlimited Sprites mode for specific NES games on Nestopia?

Mega Man 2, for instance, would greatly benefit from being run with unlimited sprites.

**Comment by clobber** [comment]
I'm finishing up code that will lead to having core options available in the HUD bar menu, so for example things like "No Sprite Limit" for NES games. This will be available in a future version, possibly the next release.

advanced/core options. #1281

**Comment by JoaoPinheiro** [comment]
Those are awesome news, I'm glad to hear it'll become possible to enable core options soon. :)

**Comment by clobber** [comment]
This option is now available in OpenEmu 2.0.8. The caveats are:

* For NES/FDS only.
* It removes the 8-sprites-per-scanline limit.
* There will still be flickering in many cases, because:
* There is still a hardware limit of 64-sprites-per-frame.
* There may still be [slowdown in NES games](https://forums.nesdev.com/viewtopic.php?f=2&t=11040) despite removing the 8-sprites-per-scanline limit.
* **The option does not persist between games because it breaks many that rely on the hardware limits.**
