### ISSUE TITLE
Controller has a mind of its own since Mojave update

### ISSUE THREAD

**Issue by retrodave80** [OpenEmu/OpenEmu#3773]
- OpenEmu Version: 2.0.7
- macOS Version: Mojave 10.14

Hi! I am running Mojave 10.14 on an Early 2015 Macbook Pro and I have OpenEmu 2.0.7. I use an 8BitDo SNES Gamepad and mainly emulate NES and SNES games. Since downloading 2.0.7 I suddenly find there are times when I'm playing the game and the controller suddenly gets a mind of its own and behaves as if I'm pushing buttons I'm not really pushing (EX: You're playing Castlevania and walking to the right when suddenly it's like Simon gets possessed and starts walking the opposite direction no matter what you do).

At first I thought it might be the controller but I have the same issue when playing with just the keyboard. The issue is intermittent and comes up every couple minutes while playing, basically making the program unusable most of the time. I've tried multiple different games and get the same result.   Any thoughts????  Thanks!

**Comment by clobber** [comment]
Hrm I don’t think this can happen with the keyboard, but this is a bug with analog axis directions getting stuck.

https://github.com/OpenEmu/OpenEmu-SDK/pull/22

Already fixed for next release.

**Comment by clobber** [comment]
Can you note the exact 8bitdo model you are using? I want to doublecheck later with my own and make sure we are both using the same one.

**Comment by retrodave80** [comment]
Hi yes, I am using 8bitdo SNES30 Gamepad!

Thanks,
Dave

**Comment by clobber** [comment]
Okay, with the 8bitdo SNES30 on latest firmware v4.10 plugged in **via USB** I can replicate it using OpenEmu 2.0.7. I cannot replicate it with Bluetooth (powered on with START, **not** START+A - do not use that mode). I cannot replicate a problem with either USB or Bluetooth on a pre-2.0.8 version, so that means this bug is indeed fixed for next release.

For now I recommend that you update your SNES30 to the latest firmware and only use it connected to Bluetooth (powered on with START) to workaround the analog axis sticking. The reason that it doesn't work correctly with USB is because the device presents a different HID profile for the directional pad than the one used in Bluetooth mode.

**Comment by clobber** [comment]
> I cannot replicate a problem with either USB or Bluetooth on a pre-2.0.8 version, so that means this bug is indeed fixed for next release.

This is fixed in OpenEmu 2.0.8, now available.

Note: Continue to use 8bitdo devices powered on with START, **not** START+A. Their "macOS mode" is incorrect.
