### ISSUE TITLE
Someone is selling OpenEmu

### ISSUE THREAD

**Issue by vitor251093** [OpenEmu/OpenEmu#3803]
Hello! I know this is not the proper place to communicate that, but I couldn't find a contact form in your website and I don't have an active Twitter account.

I was looking at Mercado Livre (an online shop focused in resellers from Latin America), and I found that ad there: 
https://produto.mercadolivre.com.br/MLB-1115511875-emulador-playstation-sega-nes-20-consoles-p-mac-_JM?quantity=1

Translating, this person is selling OpenEmu and 1000 game images for R$89,99 (about US$23 as today). I'm not sure if there is any action that should (or can) be taken, but in any case, I though that the best thing to do would be informing you.

Considering that this is not an issue with the app, you can close/delete that issue after reading it.

**Comment by clobber** [comment]
Hi Vitor, thanks for letting us know. Hopefully people aren't stupid enough to pay for a free app + some ROMs, but you never know. Due to the language barrier, I'm not sure how well I'll be able to navigate that site and get it removed, but I'll take a look.

As an aside, thank you for your work on reviving Wineskin! I have dozens of wrappers I use for win32 games.

>I couldn't find a contact form in your website and I don't have an active Twitter account.

Just an FYI, we recently set up a Discord server if you want to hang out there: https://discord.gg/FdyBqz

**Comment by vitor251093** [comment]
> As an aside, thank you for your work on reviving Wineskin! I have dozens of wrappers I use for win32 games.
Hehe thanks :D 

> Just an FYI, we recently set up a Discord server if you want to hang out there
Ow, I didn't know. Just joined it :)

**Comment by irishmapping** [comment]
Just to let you know, that seller appears to sell other things like this, emulators with lots of ROMs preinstalled for a huge price. He also happens to sell many overpriced things. Just thought i’d let you know :)

**Comment by gustavosarmento** [comment]
Since I'm from Brazil and use that site frequently, I filed a complaint about it to them. I'll post here their answer, if one comes.
