### ISSUE TITLE
Problem with xbox 360 (Possibly One as well) joystick

### ISSUE THREAD

**Issue by irishmapping** [OpenEmu/OpenEmu#3807]
Okay, so...
There seems to be a slight problem with the xbox joystick on this. Specifically, when using it for the dpad.
Most of the time, instead of being one, held out down press for example, it counts as... multiple? It’s hard to explain...

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

Plug in your Xbox 360/One controller
Go to controller settings
Set the dpad to the joystick
(Note: This sometimes counts as multiple even when just barely touching it as well)
Go into any game. Games with free movement using the dpad (e.g. Mario And Luigi games) will suffice.
Move the joystick and don’t release it.

# Expected Behavior

It should count as either holding that direction on the dpad, or count as one press

# Observed Behavior

Counts as multiple inputs

# Debugging Information

- OpenEmu Version: 2.07
- macOS Version: 1.13.6

**Comment by clobber** [comment]
>It should count as either holding that direction on the dpad, or count as one press

No it shouldn't. What you're suggesting doesn't make any sense -- that's not how analog works. And stop mapping your analog gamepad controls to "digital" buttons. For a system with d-pad controls, use an actual d-pad. What are you even thinking.

**Comment by irishmapping** [comment]
first of all it’s easier than the dpad
second of all, jeez, i’m sorry, you’re a **VERY** nice person

**Comment by clobber** [comment]
>first of all it’s easier than the dpad

No it's not easier. There is more travel in an analog stick and less precision when it comes to using it on systems that aren't designed for one. A d-pad (directional pad, get it?) is either an **on** or **off** state and is for quick, twitchy gameplay. It's why platformers and retro games in general are suited for a directional pad. 

As an aside, I'm blocking you from posting here for now because you've become a nuisance.
