### ISSUE TITLE
Can't run arcade games on Openemu anymore on MAC

### ISSUE THREAD

**Issue by plume1234** [OpenEmu/OpenEmu#3821]
Arcade games no longer work on OpenEMu on my Mac anymore.
Everything else is fine.

I get the following messages:
"Couldn't communicate with a helper application"

I've deleted everything, re-installed, no luck.
I've spent several hours already online reading threads/looking for solutions, no luck.

I'm using OpenEMu 2.8 Experimental pack.
I'm running MAC 10.11.6 El Capitan.

If anyone knows how to fix this would be great!

Thanks

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](http://choccyhobnob.com/articles/demystifying-mame-roms/)."
