### ISSUE TITLE
Contribution for the wiki

### ISSUE THREAD

**Issue by binomialstew** [OpenEmu/OpenEmu#3823]
I have a contribution available for the wiki. I don't think it is currently possible to make a PR directly, so here are the changes:

https://github.com/binomialstew/OpenEmu-wiki/commit/2292f10ab2f5f05e89b99e6fbaea219309dc1cfb

If there is a better way to do this, let me know.

**Comment by clobber** [comment]
Thanks.

The wiki is locked so that only members of the org may make changes. I may add this later after making some changes. Just a quick note: the port of Nestopia you are referencing is the long-dead Bannister port, an unofficial port of Nestopia (so I'm not sure how useful it is to reference this in the wiki). The latest standalone Nestopia (also known as Nestopia UE) can be found here (https://github.com/0ldsk00l/nestopia) and installed on macOS via [Homebrew](https://brew.sh/): `brew install nestopia-ue`
