### ISSUE TITLE
I need help with my ps3 controller on OpenEmu without usb

### ISSUE THREAD

**Issue by Kitana2430** [OpenEmu/OpenEmu#3845]
I have my PS3 controller connected to my Mac with and without the USB cable with no issues. However, when I go into controllers in OpenEmu, it only shows, when I have USB in. I am puzzled why It doesn't show without the cable, despite the bluetooth is all good?

Does anyone know, how to get it to work without the USB cable in on OpenEmu? I don't want to have it wired up when I am playing especially if I have two controllers on.

Any tips or ideas would be gratefully appreciated.

**Comment by clobber** [comment]
Not much of a reason for it to not show up in Prefs unless there is a problem caused by something in this guide: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

If you have an official PS3 DualShock controller (not a generic or knockoff) and you followed this guide to pair it, there should be no problems: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-DualShock-Controller-Pairing

Can't help you beyond this. My own works fine.
