### ISSUE TITLE
Bios files showing up as games for selected systems

### ISSUE THREAD

**Issue by sohojohn84** [OpenEmu/OpenEmu#3846]
This is mostly for Arcade, Famicom and Pc Engine (that I know of).

Whenever I drop the required Bios files on Openemu, they "show up" on my game list (see screenshot attached). In the case of Mame, several Bios files are required for games to play. If I move manually the Bios files from the Rom folder into the Openemu's Bios folder, the games won't work, meaning, the files have to stay where they are for games to function.

<img width="1466" alt="screen shot 2019-01-15 at 4 37 13 pm" src="https://user-images.githubusercontent.com/8723951/51211587-fcd57080-18e3-11e9-97e2-1ca63d6fe522.png">

Anyone experiencing the same? Was there any solve previously found? I looked into past issues but didn't see anything similar.

Thanks in advance!

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](http://choccyhobnob.com/articles/demystifying-mame-roms/)."

Next time read the guides so we waste less of each other's time. Files are showing up in your Arcade Library as they are supposed to, regardless of if they are BIOS/firmware zips or not from a MAME ROM set -- that's how it works for Arcade/MAME. Furthermore, more than half of those systems you appear to want to get working are definitely not going to run.

As for the *supported* console systems (non-Arcade/MAME), if BIOS/system files don't correctly import then you simply have the wrong files. https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files
