### ISSUE TITLE
Arcade problems with the needed bios

### ISSUE THREAD

**Issue by colson97** [OpenEmu/OpenEmu#3868]
I have installed the experimental pack of OpenEmu then, I install the MAME core, then i selected an arcade game to play, and then all of a sudden, it needed a MAME bios badly. Can you add a MAME bios on the bios section in the preferences?

# Debugging Information

- OpenEmu Version: 2.0.8
- macOS Version: 10.14.3

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](https://web.archive.org/web/20180101211010/https://choccyhobnob.com/mame/demystifying-mame-roms/)."
