### ISSUE TITLE
How do I assign ColecoVision keypad buttons using WiiMote controller settings? Without them unable to begin a game.

### ISSUE THREAD

**Issue by dhsteeler** [OpenEmu/OpenEmu#3873]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: ???

**Comment by clobber** [comment]
Well the problem is pretty easy to understand: The Wiimote has a limited number of buttons so you cannot possibly assign all of the buttons on a real ColecoVision controller to it... not sure what you are asking for here.

The solution:
You either use another gamepad or you simply use the keyboard to press the numerical button that you want. OpenEmu responds to both keyboard and gamepad inputs at the same time, so just press the button on your keyboard man.

**Comment by dhsteeler** [comment]
I did just press the keyboard buttons “man”. Sorry to bother you.
