### ISSUE TITLE
Refreshing game list after deleting roms

### ISSUE THREAD

**Issue by halpz** [OpenEmu/OpenEmu#3876]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Delete roms from applicationsupport folder (the app hangs when I try to delete too many of them at once them in there)
2. Open the app
3. Rom names are still there,

# Expected Behavior

1. Would like a refresh option to remove 'dead links' to roms

is there a way to regenerate the DB file somehow?

# Debugging Information

- OpenEmu Version: 2.0.8
- macOS Version: mojave

**Comment by halpz** [comment]
I've solved my problem by deleting my roms in smaller batches

there must be a memory issue somewhere?

it would be nice to have some sort of progress bar when deleting, (if it was just taking a a long time and not crashing)

**Comment by clobber** [comment]
>Delete roms from applicationsupport folder (the app hangs when I try to delete too many of them at once them in there)

You're not supposed to delete files from the ROMs folder since those files are managed by OpenEmu, so import and delete ROMs through the UI. Manipulating the contents of the Game Library folder outside the application **will** cause problems. Other cleanup operations are taking place when you properly delete files through the UI. Furthermore, on macOS, the User Library is not intended to be user-accessible for a reason, so stay out of it, at least when it comes to our application.
