### ISSUE TITLE
can't delete more than 100 or so roms

### ISSUE THREAD

**Issue by halpz** [OpenEmu/OpenEmu#3877]
Summary of issue

previous issue was closed because I dared to access the application support folder, you didn't address this part of my issue:

# Steps to reproduce

    1. cmd+a select all roms (in app)
    2. delete
    3. spinning beachball, app hangs, roms are not deleted

# Expected Behavior

    1. select all roms ,then delete, show progress bar until finished, roms are deleted

# workaround

    1. delete roms in small batches so the app doesn't break

# Debugging Information

    * OpenEmu Version: 2.0.8

    * macOS Version: mojave

**Comment by clobber** [comment]
>previous issue was closed because I dared to access the application support folder, you didn't address this part of my issue:

Your previous issue was closed because it was invalid (you manually deleting ROMs) -- you had not made it clear you had a problem using the application. This issue will also be closed because you opened with a snide remark, provided no useful information to troubleshoot with and I also cannot replicate the problem.
