### ISSUE TITLE
Light UI as an option

### ISSUE THREAD

**Issue by ScherisMarie** [OpenEmu/OpenEmu#3885]
https://jessicaotis.com/academia/never-use-white-text-on-a-black-background-astygmatism-and-conference-slides/

While the current UI in OpenEmu isn't exactly like this (as it uses a subdued gray-like color for most of the text), I do experience some of the effect mentioned in the link above.

If a "light" UI option could be added as an optional option, it would help out my eyes a lot when I'm needing to use the app itself outside of playing games via it.

**Comment by clobber** [comment]
In the last release, we made the decision to force "Dark Mode" on macOS 10.14+ so that our custom UI would look better (https://github.com/OpenEmu/OpenEmu/commit/87d340c3479732bf6174303b397bd5d9256ba71f), as it doesn't look good with light UI elements. As we continue to replace our custom UI with native controls, we will eventually remove that change but we are not there yet.
