### ISSUE TITLE
Midway/Atari Seattle hardware emulates slow in an ancient MAME port

### ISSUE THREAD

**Issue by Akumaku7** [OpenEmu/OpenEmu#3915]
Hello. I'm having issues with only Arcade in OpenEmu. All the other emulator runs smoothly. I was playing few of NFL Blitz Series where the only the gameplay tends to be slow and the sound choppy. The movies/main menu/attract mode runs well. 

I tried playing/testing on two laptop just to see which is different yet, they're both are affected from it . I would say its the game's graphics but I want to be sure.

**OpenEmu v2.0.8**
Display: Pixelate and Nearest Neighbor

**Model Name:	MacBook Pro**
Model Identifier:	MacBookPro9,1
Processor Name:	Intel Core i7
Processor Speed:	2.6 GHz
Chipset Model:	Intel HD Graphics 4000
Type:	GPU
Bus:	Built-In
VRAM (Dynamic, Max):	1536 MB

  **Model Name:      MacBook Pro**
  Model Identifier:    MacBookPro14,1
  Processor Name:   Intel Core i5
  Processor Speed:  2.3 GHz
  Chipset Model:      Intel Iris Plus Graphics 640
  Type:                      GPU
  Bus:                        Built-In
  VRAM (Dynamic, Max):   1536 MB

Thank You

**Comment by digamejh** [comment]
I'm thinking it's more a MAME issue than an OpenEmu issue.  Polygonal games from that era need a lot of computation power in order to be remotely playable (I'm not familiar with NFL Blitz, but Cruis'n USA, which I think runs on similar hardware, is that way).

You'd probably have better luck with standalone MAME in this case.

**Comment by MaddTheSane** [comment]
That and MAME aims to be as accurate as possible, compromising on speed if needed.

**Comment by clobber** [comment]
@Akumaku7 Good job, you ignored the guide!

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](https://web.archive.org/web/20180101211010/https://choccyhobnob.com/mame/demystifying-mame-roms/)."

The OpenEmu core plugin version of MAME is also incredibly old. Use MAME standalone.
