### ISSUE TITLE
"Drag & Drop Games Here" text is overlaid on itself?

### ISSUE THREAD

**Issue by axfelix** [OpenEmu/OpenEmu#3920]
Seems like a weird visual glitch for such an otherwise attractive app, not sure if it's a known issue or what

<img width="483" alt="Screen Shot 2019-05-25 at 10 01 07 PM" src="https://user-images.githubusercontent.com/252047/58377571-b26e9b00-7f38-11e9-908b-60edfd516308.png">

**Comment by robotoad** [comment]
Need more info. What version of OpenEmu are you using, and in what circumstances does this glitch occur?

**Comment by axfelix** [comment]
Newest (installed yesterday), it's a 2018 MBP, running Mojave, happens ... no matter what?

**Comment by clobber** [comment]
Cannot replicate with OpenEmu 2.1 on macOS 10.14.6

<img width="942" alt="Screen Shot 2019-10-24 at 9 58 40 AM" src="https://user-images.githubusercontent.com/1303132/67612495-b2cdc500-f768-11e9-9308-3708e40e37d9.png">

**Comment by axfelix** [comment]
![image](https://user-images.githubusercontent.com/252047/67648736-cbb6b180-f8f3-11e9-81a1-6105f36b0f51.png)

Just went to 2.1, still occurring. 10.14.6, 2018 MBP 13".

**Comment by livid** [comment]
Still occur on OpenEmu 2.2 running on macOS 10.14.6.

In addition to screenshots, which files would be helpful for diagnosis? I can upload them here. Thank you.

**Comment by orion1vi** [comment]
Caused by subpixel antialiasing.
![Screenshot 2020-03-21 at 14 22 09](https://user-images.githubusercontent.com/16036254/77226267-b763a180-6b7f-11ea-9993-9593aa4b3a7b.png)
![Screenshot 2020-03-21 at 14 22 18](https://user-images.githubusercontent.com/16036254/77226270-b9c5fb80-6b7f-11ea-854e-132a4af4a0d4.png)
Can reproduce with:
defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

**Comment by axfelix** [comment]
This is fixed in 2.3
