### ISSUE TITLE
PLEASE HELP! Openemu is causing random screen flickering around the border of my macbook pro - even when openemu is closed!?

### ISSUE THREAD

**Issue by glitchHiker** [OpenEmu/OpenEmu#3922]
Hello. I've been using openemu for a long time, but today I played some N64 roms - MK4 and killer Instinct Gold. After quitting KI I noticed some screen flickering around the edge of my macbook pro screen - about an inch from the vertical border, and only like a milimeter or 2 from the horizontal edges.. THIS WON'T GO AWAY!? I've restarted, tried changing resolution... It won't stop!? Has this emulator ruined my macbook permanently!? the only thing that stops it temporarily is moving the mouse pad, but it comes back within a few seconds and won't stop until i move the mouse pad again... HOW DO I FIX THIS!? Tried googling and cannot find this problem listed anywhere. PLEASE HELP!!! ANY help is appreciated. Thank you.

Macbook specs:

Macbook pro 13 inch 2017
mojave 10.14.4
8gb 2133 mhz lpddr3
intel iris plus graphics 640 1536 mb

**Comment by clobber** [comment]
>I've restarted, tried changing resolution... It won't stop!? Has this emulator ruined my macbook permanently!?

Sorry, this doesn't sound like an OpenEmu bug or something cause by our software at all. Take it into the Apple store.

**Comment by EnriqueL88** [comment]
Hello, I have had the same problem and wish to know if more findings on this topic exist. The screen is still undergoing this flickering. Can we have some information? I am looking over to run some additional diagnostics to check what is happening and will provide updates.

**Comment by EnriqueL88** [comment]
Hey, got some solutions I think can work. It can be that something at OpenEmu or Mupen64 created a problem with the PRAM (or NVRAM) and I am going to try the solutions described at: 

https://macreports.com/mac-how-to-troubleshoot-screen-flickering/
Implies resetting the PRAM/VRAM and/or the SMC.

Will report results.

**Comment by EnriqueL88** [comment]
Gotta mention some additional details:
Mi mac is exactly the same:

Macbook pro 13 inch 2017
mojave 10.14.4
8gb 2133 mhz lpddr3
intel iris plus graphics 640 1536 mb

And the flickering disappeared without even having to reset the PRM or VRAM.
Just continuous usage for an hour and a half while searching solutions.
I restarted the Mac twice too. 
And, I uninstalled openEmu, but I do not think that oPenemu is the issue as it continued flickering after uninstall.
The ROM that created this problem is Mortal Kombat 4 (USA), the flickering began with it.

Team at OpenRom, hope this is of some help for this or future cases.
