### ISSUE TITLE
Game Scanner Import doesn't have Colecovision

### ISSUE THREAD

**Issue by colson97** [OpenEmu/OpenEmu#3946]
After i downloaded Mountain King for the Colecovision, I began to add it to the library then there's an resolve issues then, all of a sudden no Colecovision on the import! Can you help this import problem?

- OpenEmu Version: v2.0.9.1
- macOS Version: v10.14.5

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Importing

In order to import, OpenEmu expects ColecoVision ROMs to have the file extension of either **.col or .rom** and for the "ColecoVision" Library to be "enabled" (if it is visible in the list of consoles in your sidebar then that means it is "enabled"). If you satisfy those requirements then the game will import fine. The fact you say whatever ROM you imported ends up in the "Issue Resolver" means you have it wrong.

![Screen Shot 2019-06-26 at 9 15 07 AM](https://user-images.githubusercontent.com/1303132/60187303-f9c7a000-97f2-11e9-85d7-dae568af8af2.png)
