### ISSUE TITLE
N64 controller not working only in Goldeneye

### ISSUE THREAD

**Issue by dsparshott** [OpenEmu/OpenEmu#3955]
N64 controller attached with USB adapter, calibrated, and selected in Open Emu.

As of today the controller is unresponsive when playing Goldeneye, it works fine with other games and is visible and selectable in the preferences>edit game controls panel within Goldeneye.

Yesterday the controller worked fine. Nothing updated with OS, ROM, or Emu since.

Mac OS 10.11.6
Emu 2.0.9.1
Goldeneye (USA)

**Comment by clobber** [comment]
I can assure you there's nothing random about the way OpenEmu works. If your input device isn't working it's either due to something listed in the [Troubleshooting: Input problems](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) wiki (especially if you may be using a multi-port adapter/hub) or you are experiencing a Mupen64Plus core bug. Try launching the game without restoring the autosave at launch:

* In the app, go to OpenEmu > Preferences > Library, click "Reset warnings"
* Open your game and click "No" when prompted to "Continue where you left off"

**Comment by dsparshott** [comment]
Doesn't help i'm afraid. No other apps are running. Warnings are present and followed as suggested.

How is a core bug resolved? OpenEmu and games have had a new clean install yet the problem persists-  now applies to Mariocart and Goldeneye.

**Comment by clobber** [comment]
It is impossible for a device to have per-game issues for a system. It either works for all the N64 games or it works for none. Describe your issue thoroughly, in detail. What does “unresponsive” mean? Which games does it verifiably work for? What USB adapter?
