### ISSUE TITLE
Problem with LOZ:ALTTP possibly with layers?

### ISSUE THREAD

**Issue by posdit** [OpenEmu/OpenEmu#3963]
This is a pretty basic but frustrating problem I am having with Zelda3.  When I go the guy sleeping under the bridge I can not talk to him ie pressing the A button does nothing.  I can talk to anyone else in the game so far.  The A button works as expected in every other situation.  I can not walk straight through him so the sprite is there but I just can't talk to it.  I am using the Snes9x core with the pixelate filter.

OSX version 10.11.6
Open emu version 2.0.9.1

**Comment by clobber** [comment]
Not going to be an OpenEmu or even Snes9x core bug here. I recently played this game and had no problem collecting that bottle. Perhaps you already collected it and forgot, because once you've already talked to him he won't talk again.

https://www.zeldadungeon.net/wiki/Under_the_Bridge#A_Link_to_the_Past
