### ISSUE TITLE
Cannot add new roms

### ISSUE THREAD

**Issue by gsadkins** [OpenEmu/OpenEmu#3978]
I cannot add new roms.  I've tried by using "Add to Library" as well as dragging and dropping.  Nothing happens.  Existing roms are working.  

Example frogger mame rom here:  https://wowroms.com/en/roms/mame/download-frogger/83275.html

MacOS 10.14.5
OpenEmu 2.0.9.1

**Comment by clobber** [comment]
That imports just fine here. If you cannot import it, then it already exists in your Library.

<img width="942" alt="Screen Shot 2019-09-08 at 3 11 44 PM" src="https://user-images.githubusercontent.com/1303132/64493845-12b8ec80-d24b-11e9-9179-f2463fecc90b.png">

Also:
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](https://web.archive.org/web/20180101211010/https://choccyhobnob.com/mame/demystifying-mame-roms/)."

Use MAME standalone.
