### ISSUE TITLE
Not recognizing keyboard input MacOS Catalina

### ISSUE THREAD

**Issue by chartle** [OpenEmu/OpenEmu#3988]
Summary of issue

Since updating to Catalina, keyboard input is not recognized.  Have granted permissions for input monitoring. 

# Steps to reproduce

1. Launch any game, any system.
2. Modify controls for Keyboard, no input is recognized.

# Expected Behavior

1. Keyboard input is recognized. 

# Observed Behavior

1. Input is not recognized. 

# Debugging Information

- OpenEmu Version: 2.0.9.1
- macOS Version: Catalina 10.15

**Comment by clobber** [comment]
Not an OpenEmu bug. This is due to new security rules in macOS Catalina 10.15, so in order for keyboard input to work you MUST grant OpenEmu "Input Monitoring" access in the [Privacy pane](https://support.apple.com/guide/mac-help/change-privacy-preferences-on-mac-mh32356/mac) of Security & Privacy preferences.

To open this pane on your Mac, choose Apple menu  > System Preferences, click Security & Privacy, then click Privacy.

Scroll down on the left to Input Monitoring. If needed, click on the lock icon in the bottom left corner, and enter your password. **Check the box** next to OpenEmu.app, if asked select quit now, and close out of System Preferences.

**Note:** You may also see [this alert](https://i.imgur.com/uDCAVig.png) the first time running OpenEmu on macOS Catalina 10.15, in which case you should click "Open System Preferences" and grant "OpenEmu" access by making sure the box is checked.

**🚨 Extra Important Note:** Toggling the permission may also resolve keyboard input issues. If keyboard input is *still* not working after granting access, toggle it off and then on again to see if that resolves the problem.

A future OpenEmu update will improve the UX for this process but it will still be necessary.

**Comment by chartle** [comment]
ty sir.  toggling the option corrected.  appreciate your work.

**Comment by nghtstr** [comment]
I have tried toggling the button as suggested; and it still does not recognize the keyboard input. Any further advice would be greatly appreciated.

**Comment by nghtstr** [comment]
I just thought of something regarding my comment. It was working before I paired my PS4 controller to my Mac; since then keyboard does not work. I even went to the extreme of forgetting my PS4 controller from my Mac, and making sure that Keyboard was selected from the Input dropdown menu.

**Comment by clobber** [comment]
> making sure that Keyboard was selected from the Input dropdown menu.

OpenEmu responds to both keyboard and gamepad input at the same time. So you are able to press a keyboard button (and use that) even while a gamepad is plugged in. The "Input:" drop down menu in Controls Preferences is only for mapping controls, not selecting which device is "in use" during gameplay.

@nghtstr Sorry, I don't believe yours is an OpenEmu issue. Toggle the setting again, restart your machine and make sure you don't have a situation noted in the [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) guide that could cause a problem.

**Comment by LucasMaliszewski** [comment]
> Not an OpenEmu bug. This is due to new security rules in macOS Catalina 10.15, so in order for keyboard input to work you MUST grant OpenEmu "Input Monitoring" access in the [Privacy pane](https://support.apple.com/guide/mac-help/change-privacy-preferences-on-mac-mh32356/mac) of Security & Privacy preferences.
> 
> To open this pane on your Mac, choose Apple menu  > System Preferences, click Security & Privacy, then click Privacy.
> 
> Scroll down on the left to Input Monitoring. If needed, click on the lock icon in the bottom left corner, and enter your password. **Check the box** next to OpenEmu.app, if asked select quit now, and close out of System Preferences.
> 
> **Note:** You may also see [this alert](https://i.imgur.com/uDCAVig.png) the first time running OpenEmu on macOS Catalina 10.15, in which case you should click "Open System Preferences" and grant "OpenEmu" access by making sure the box is checked.
> 
> **🚨 Extra Important Note:** Toggling the permission may also resolve keyboard input issues. If keyboard input is _still_ not working after granting access, toggle it off and then on again to see if that resolves the problem.
> 
> A future OpenEmu update will improve the UX for this process but it will still be necessary.

Toggling it off and on for me was a fix!

**Comment by MagnusBrzenk** [comment]
On my Mac it says that this permission will "Allow [openEmu] to monitor input from your keyboard even while using other apps". Why does openEmu need such liberal access to my inputs? Why can't it just be content to monitor the keyboard iff I'm using it (like just about every other app on my computer)?

**Comment by ifonefox** [comment]
@MagnusBrzenk If I understand it correctly, since OpenEmu is using the keyboard in an unconventional way (ie not to write text), the app needs more direct access to the keyboard than macOS normally provides. The Catalina-compatible version of OpenEmu isn't doing anything new, Catalina is just making it an opt-in process.
