### ISSUE TITLE
Openemu folders

### ISSUE THREAD

**Issue by theblackpig75** [OpenEmu/OpenEmu#4010]
I have downloaded openemu and placed all my roms in the downloads folder. I recently decided to have a clear up and moved openemu into my desktop. When I open it up and attempt to play the games it says the roms are either missing or corrupt. I reinstalled and downloaded the most recent version (2.1) and it asks me permission to access the desktop which I grant and the games load no problem. But when I restart it resets and I get the cannot find Roms message. Any ideas?

**Comment by Akylzhan** [comment]
Cannot reproduce this issue, macOS 10.15, my roms are in Application Support folder

**Comment by theblackpig75** [comment]
I have managed to set my destination folder in my desktop however I have lost all my roms. I have had to transfer them all over to the destination folder and that’s resulted in loads of roms going into the wrong folders. Is there a way of resetting and getting the old folders back? Also having problems finding the rom set 0.149 for mame. The file is massive 20Gb+ and is taking an age to download. I don’t remember doing this before. Is there an alternative?

**Comment by theblackpig75** [comment]
I have downloaded the mame rom set, some are working some are coming up with 
Pole Position (Atari version 1) (polepos1.zip) requires:

namco51.zip  	- NOT FOUND
namco52.zip  	- NOT FOUND
namco53.zip  	- NOT FOUND
namco54.zip  	- NOT FOUND

These ROMs must be from a MAME 0.149 ROM set. Some of these files can be parent/device/BIOS ROMs, which are not part of the game, but are still required. Delete files already imported and reimport with correct files. 

and

Cadillacs and Dinosaurs (USA 930201) (dinou.zip) requires:

dino.zip  	- NOT FOUND
qsound.zip  	- NOT FOUND

These ROMs must be from a MAME 0.149 ROM set. Some of these files can be parent/device/BIOS ROMs, which are not part of the game, but are still required. Delete files already imported and reimport with correct files.

Any ideas?

**Comment by clobber** [comment]
>Any ideas?

@theblackpig75 I'm not sure how to make that message more self-explanatory. Actually read it and get the correct files. Arcade use with OpenEmu is unsupported.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](https://web.archive.org/web/20180101211010/https://choccyhobnob.com/mame/demystifying-mame-roms/)."

The OpenEmu core plugin version of MAME is also incredibly old. Use MAME standalone.
