### ISSUE TITLE
Poor Framerate

### ISSUE THREAD

**Issue by wagenet** [OpenEmu/OpenEmu#4017]
Summary of issue

Framerate is poor. It is noticeably worse than prior versions.

# Steps to reproduce

Play a game.

# Expected Behavior

Better framerate.

# Observed Behavior

Framerate is poor.

# Debugging Information

- OpenEmu Version: v2.1 265-g9379477-Release
- macOS Version: 10.15 (19A602)

**Comment by clobber** [comment]
>Framerate is poor. It is noticeably worse than prior versions.

Need to be WAY more detailed than that.

**Comment by wagenet** [comment]
@clobber running multiple projects myself I understand the annoyance of vague issues. However, it would have been nice if you could have given me some pointers here on what sort of information is useful to you as a developer. My understanding is that 2.1 includes a rewrite of the graphical system and as such, it seems that you would be interested in hearing about potential regressions.

In hindsight, I realize that I should have mentioned that this specifically applies to some of the filters. Specifically, there was a smoothing filter that I used without any performance penalty. I believe the exact filters may have changed in 2.1, but when I tried to find a similar one, I got significant framerate drops where previously everything had run smoothly. I realize that 2.1 is supposed to make things better but I'm actually considering downgrading both due to this and #4016.

**Comment by clobber** [comment]
> pointers here on what sort of information is useful to you as a developer

Tips on what to include is all in the Troubleshooting/Contributing Guide - the link you saw as you opened the issue. Let's not pretend you didn't know what sort of useful information to include.

You seem to understand there was a rewrite of the graphics system and new shaders. Including that you were having trouble with shader(s) beyond the default Pixellate would have been the obvious choice. I'm not going to try and beat the information out of you when you knowingly open a vague issue. That's just a waste of my time, much like now.

> Specifically, there was a smoothing filter that I used without any performance penalty.

Really cannot help you there. If your GPU cannot handle your selected shader, nothing can be done besides using a different shader that is less taxing. Some are much more taxing than others, such as CRT Royale. The old shaders and new are nothing alike, so making a comparison there as a possible "regression" case will not be useful. As an aside, if you have a dual-GPU machine, OpenEmu automatically switches to the more-powerful "discrete" one. Many of the new shaders are also configurable in order to achieve a desired look.

Don't like any of the current ones? You're in luck! A guide and improved UI/UX will be available in the future on how to add more from the `slang-shaders` repo.
