### ISSUE TITLE
Azumanga Daioh Puzzle Bobble unable to run even with required files

### ISSUE THREAD

**Issue by raindew120** [OpenEmu/OpenEmu#4021]
Summary of issue

The game, Azumanga Daioh Puzzle Bobble is unable to run even with the files 'gdl-0018.chd' and 'naomigd.zip' placed in the game library. 

<img width="449" alt="Screen Shot 2019-11-02 at 12 07 09 AM" src="https://user-images.githubusercontent.com/56622825/68038866-d57e5180-fd05-11e9-8b3f-73147cd11dd2.png">

# Steps to reproduce

1. Download OpenEmu 2.0.9.1 (experimental) and enable Arcade.
2. Download the files azumanga.zip, gdl-0018.chd and naomigd.zip.
3. Drop them in the Arcade library section of OpenEmu.
4. Click on 'Azumanga Daioh Puzzle Bobble (GDL-0018)' and it will bring up the following error message.

# Expected Behavior

1. Download OpenEmu 2.0.9.1 (experimental) and enable Arcade.
2. Download the files azumanga.zip, gdl-0018.chd and naomigd.zip.
3. Drop them in the Arcade library section of OpenEmu.
4. Click on 'Azumanga Daioh Puzzle Bobble (GDL-0018)' and it will launch.

# Observed Behavior

I got the message informing me that certain files are required but there is nothing on the list.

# Debugging Information

- OpenEmu Version: 2.0.9.1 (experimental)
- macOS Version: 10.12.6

**Comment by clobber** [comment]
1. You don't have all the files.
2. That is a Naomi system and MAME will not run it, despite there being a copy available for you to download.
3. Old versions of OpenEmu are unsupported.
4. Arcade is unsupported

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](https://web.archive.org/web/20180101211010/https://choccyhobnob.com/mame/demystifying-mame-roms/)."

The OpenEmu core plugin version of MAME is also incredibly old. Use MAME standalone.
