### ISSUE TITLE
Screenshots not working for some in v2.1.1

### ISSUE THREAD

**Issue by Kerry-Maxwell** [OpenEmu/OpenEmu#4023]
Summary of issue

Attempts at screenshots yield 32 x 32 pixel image of black screen.

# Steps to reproduce

Press key assigned to screenshot.

# Expected Behavior

Expect screenshot @ either 4320 × 5760, or 7680 × 5760

# Observed Behavior

Black 32x32 image

# Debugging Information

OpenEmu v 2.1.1
Mojave 10.14.6

**Comment by clobber** [comment]
I cannot replicate this with NES games using OpenEmu 2.1.1 with default settings on macOS 10.14.6. This might be happening for you under very specific conditions. Any additional information you can share, such as preferences, only happening on certain systems, etc?

**Comment by Kerry-Maxwell** [comment]
I have only tried Arcade games, as I use manual screenshots of title screens for each game. The only change in variables I'm aware of was updating to 2.1.1. I can try other systems later this evening and report back. I also noted that the camera icon that appears when taking a screenshot had moved to the far left of the screen, and was not within the game window as it used to be. I tried several arcade games, both horizontal and vertical.

**Comment by clobber** [comment]
> Arcade

This is our official stance on Arcade/MAME support at the moment:

> Contributing guidelines - "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official standalone version and to read this helpful MAME ROMs tutorial."
>
> The OpenEmu core plugin version of MAME is also incredibly old. Use MAME standalone.

That said, I cannot replicate this problem with any OpenGL-backed cores either (Arcade/MAME, Mupen64Plus or PPSSPP). Our current Arcade/MAME core is due for an update soon and will no longer use OpenGL to render, but it will still be part of the "experimental cores" bundle and officially unsupported.

Reply back here if you can replicate this problem with other systems testing NES, N64 and PSP.

**Comment by Kerry-Maxwell** [comment]
I get the issue with all systems, but only in fullscreen mode. I can get correct screenshots when windowed, but going to fullscreen yields a 32x32 black patch for all systems. The video card for my iMac 27" retina 5K (late-2015) is AMD Radeon R9 M390 2 GB.

**Comment by Kerry-Maxwell** [comment]
I notice that even when I get a non-black screenshot, they include the black bars on the sides of the screen, and the resolution is much smaller than the previous version's screenshots. The previous version would create a 7508 × 5760 screenshot for an SNES game, without any black bars on the sides. v2.1.1 creates a 3578 × 1966 shot with black bars on the sides. I have about 225 screenshots taken with the previous version, dating from as far back as 2016, and as recently as Nov. 2nd before I updated, from most of the systems supported by Openemu., and they are are all consistent in their resolution and lack of black bars.

**Comment by clobber** [comment]
> I get the issue with all systems, but only in fullscreen mode.

Thank you for the test case. I've tried in fullscreen, both library and popout window, and am still unable to replicate.

**Comment by Kerry-Maxwell** [comment]
What size screenshots do you get? Files typically used to be between 1.6 MB and 9 MB, and I'm now getting files between 250-585 KB.

**Comment by pagooedtv** [comment]
I have a similar issue with the screenshot functions: different version of OpenEmu, and macOS, and different failure of output file. 

# Steps to reproduce
- Start i.e. game on Game Boy or SNES
- Press CMD + T or the menu entry for creating screenshot without using shortcut 

# Expected Behavior
- Expect a screenshot
- Last time when it worked was on December 27, 2019 on the same device

# Observed Behavior
- screenshot size is 25KB and 1660 x 1066
- you can still play the games (keyboard works very well)
- screenshot is black on OpenEmu screenshot gallery and when you open the "real file" with the help of finder

# Attached files
- two screenshots, same game, different dates of creation
![Super Mario Land 2019-12-27 16 04 10](https://user-images.githubusercontent.com/59545618/71817742-2ce2ca00-3087-11ea-8c44-080c78889b57.png)
![Super Mario Land 2020-01-06 13 08 16](https://user-images.githubusercontent.com/59545618/71817743-2ce2ca00-3087-11ea-9c0e-eb448e7cfbac.png)

# Debugging Information
- OpenEmu Version: 2.2 (also on 2.1.1)
- macOS Version: 10.15.2

**Comment by Lhivorde** [comment]
I am having a similar issue.  Playing a Gameboy Color game with the Pixelate shader.  The scale does not seem to change the result.

OpenEmu Version: 2.2.1
MacOS: 10.15
MacBook Pro (15-inch, 2016)

**Comment by clobber** [comment]
Fixed in https://github.com/OpenEmu/OpenEmu/commit/dd797fd25faf7f8d36b25d0a95a15b9312628996
