### ISSUE TITLE
New NDS display modes do not work initially after upgrading to 2.2

### ISSUE THREAD

**Issue by gingerbeardman** [OpenEmu/OpenEmu#4068]
New NDS display modes do not work initially after upgrading to 2.2 

# Steps to reproduce

1. Launch NDS game
1. Select new NDS display mode (single screen, rotation) using cog menu and mouse

# Expected Behavior

1. New display modes should effect the video output

# Observed Behavior

1. New display modes do _not_ effect video output

# Debugging Information

- OpenEmu Version: 2.2 (6096.40-g3b560b8c-Release)
- macOS Version: 10.14.6 (18G2022)
- Previous issue #1775

ps: thanks for adding this feature!

**Comment by shysaur** [comment]
I cannot reproduce your issue.

Please make sure that you are not switching display modes using the "Next/Previous Display Mode" system key bindings. Since there are 56 possible combinations of display modes, some of the newly added ones are intentionally inaccessible from those system keys. 

Additionally, the code which handles emulation and save states in the DeSmuMe core is completely independent from the new code which handles display modes. Thus, save states should not be able to interfere with display modes.

(By the way, the save state you attached was saved with DeSmuMe core version 0.9.11.3)

**Comment by gingerbeardman** [comment]
Interesting. 

The first time I launched 2.2 the cog menu display options did not have any effect (I didn't use any keys to trigger them). Perhaps it was an incorrect assumption that it was due or save state that I deleted between launches. Maybe it was just the first launch itself. I'll try to reproduce.

**Comment by gingerbeardman** [comment]
Here's a screen recording of me reproducing:

https://imgur.com/a/PpdyLXQ

I trust that gives the issue some weight.

**Comment by shysaur** [comment]
It would be useful if you specified how you were able to make this bug happen again. 

Also, please post here the output of the following Terminal command when you manage to reproduce the bug:
`defaults read org.openemu.OpenEmu displayMode.org.openemu.desmume`

**Comment by gingerbeardman** [comment]
I trashed my app and preferences (keeping my ROMs) and started again. It reproduced immediately. 

I’ll grab the values for you soon.

**Comment by shysaur** [comment]
> I’ll grab the values for you soon.

No need for that, I can reproduce now. Thanks!

**Comment by shysaur** [comment]
The fix will be available in the next version of OpenEmu, which I think is going to be released fairly soon. Thanks again for the help!

**Comment by gingerbeardman** [comment]
Thanks for sticking with it, seeing the issue closed so quickly after filing it was very disheartening.

**Comment by clobber** [comment]
> seeing the issue closed so quickly after filing it was very disheartening.

Ay, so dramatic. :P 

Without steps to replicate it or if we cannot replicate it, that is the standard procedure. Especially if you say it’s related to save states which was totally nonsensical.
