### ISSUE TITLE
RetroLink USB N64 Controller Issues in v2.2 (macOS Mojave)

### ISSUE THREAD

**Issue by jacobsladder99** [OpenEmu/OpenEmu#4076]
Gamepad input glitches everywhere with v2.2. Reverted back to 2.1, and everything works fine. The gamepad I'm using is a RetroLink USB N64 Controller.

3 Steps to reproduce

1. Select gamepad as input in the controller menu
2. Assign buttons (*** Sometimes will not allow you to assign buttons, sometimes will ***)
3. Select a game, and open it.

# Expected Behavior

1. Game should function normally, buttons on gamepad should correspond with actions in game when pressed

# Observed Behavior

1. Some buttons do not function, in some games there is a hard drift to the left with analog stick, or several directions of analog stick not registering at all.

2. When assigning gamepad buttons, sometimes OpenEmu will allow buttons to be assigned, sometimes not. Quitting and restarting OpenEmu may allow you to assign buttons, but the issues with buttons and analog play as stated above still exist.

Examples: In Mario Kart 64, the analog stick does not register left or right. In Tony Hawk's Pro Skater 2, there is a hard drift to the left.

# Debugging Information

- OpenEmu Version: 2.2 (No issues in previous builds with this gamepad and OS)
- macOS Version: Mojave 10.14.6

**Comment by clobber** [comment]
> When assigning gamepad buttons, sometimes OpenEmu will allow buttons to be assigned, sometimes not. Quitting and restarting OpenEmu may allow you to assign buttons, but the issues with buttons and analog play as stated above still exist.

Please be very specific. *Which* buttons cannot be assigned? I might assume you mean the analog sticks as the new analog axis auto-calibration system is causing sensitivity issues, affecting the dead zone of the analog axes. I'm unsure of the analog "drift" issues you say you experience. Possibly because the analog stick isn't assigned correctly in the mappings? Does the issue persist if you move the analog stick in full circles, several times, making sure to hit the full range of the stick while in-game?

We also require a HID profile of your device. Download this app: [HIDBrowser.app.zip](https://github.com/OpenEmu/OpenEmu/files/3746691/HIDBrowser.app.zip). Connect the controller, open HIDBrowser.app (via right-clicking if necessary), and then select your "RetroLink" gamepad from the "Device" list. Finally, select "Export Device Properties..." from the File menu, and post the .plist files you have exported.

**Comment by jacobsladder99** [comment]
I don’t care enough to continue with this ridiculously convoluted but
reporting setup, sorry. Feel free to delete my entry

**Comment by clobber** [comment]
Test this build: https://send.firefox.com/download/4f2509ab0285bff0/#pPaiwLm2QpGQpd-LcKoKWg

**Comment by lwaldo** [comment]
that seems to fix the issue. I was also have trouble with mapping my buttons (all of them). However I had to unplug my controller twice as this update seem to be auto selecting buttons before I started.

**Comment by chadlavi** [comment]
I'm experiencing (what I think is) a similar issue to the original poster; I'm using v2.2 on macOS Catalina (10.15.3 beta).

I'm trying to use a retrolink n64 controller, but it seems that only the D-pad and stick can be mapped in the controls settings. Start, A, B, C-pad, L, R, and Z cannot be mapped at all, and pressing them has no effect.

(the test build linked above in this thread has expired)

**Comment by clobber** [comment]
@chadlavi Try the test build:

https://send.firefox.com/download/4ea6f60a7d3cdba9/#aXAiYA7S1m_pSrUW0t8U9A

**Comment by chadlavi** [comment]
@clobber sorry about the delay -- that test build does fix this issue! I was able to map the controls on the retrolink perfectly, and the controls worked correctly in a test run of MarioKart 64.

**Comment by clobber** [comment]
Officially fixed in OpenEmu 2.2.1, available now.
