### ISSUE TITLE
Twilight Princess GC iso L and R issues

### ISSUE THREAD

**Issue by kmgooey** [OpenEmu/OpenEmu#4100]
Summary of issue
I have successfully uploaded "Legend of Zelda, The - Twilight Princess (USA).7z" into OpenEmu and started the game. The L and R buttons are not working no matter which buttons I remap them to on the keyboard. I plugged in a PS4 controllers and again, the L and R buttons don't work no matter which buttons I remap them to. All of the other buttons work fine. It is not my keyboard or controller because when I play a GBA game the L and R work fine.
Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

I have successfully uploaded "Legend of Zelda, The - Twilight Princess (USA).7z" into OpenEmu and started the game. The L and R buttons are not working no matter which buttons I remap them to on the keyboard. I plugged in a PS4 controllers and again, the L and R buttons don't work no matter which buttons I remap them to. All of the other buttons work fine. It is not my keyboard or controller because when I play a GBA game the L and R work fine.

# Expected Behavior

L and R are used for centering the camera and locking on (a must have to progress in the game)

# Observed Behavior

Game shows no sign of button input. Gamecube remapping settings registers the buttons pressed on the keyboard or controller but does not change the input in the game.

# Debugging Information

- OpenEmu Version: 2.2
- macOS Version: 10.14.6

**Comment by clobber** [comment]
> uploaded ... .7z

Do not *import* compressed .ISOs for GameCube games. Your game will load incredibly slow as it needs to decompress each time you try to load it. Only import the .ISO file itself, which results after you decompress the .7z archive.

> The L and R buttons are not working

This is due to a dolphin core plugin update that was just released in preparation for the next OpenEmu version, which adds support for hybrid analog/digital triggers on the GameCube. You will have to wait for this next version for your issue to be resolved.

**Comment by yitzritz** [comment]
could you send me that ISO?
