### ISSUE TITLE
Gamecube emulation

### ISSUE THREAD

**Issue by bennettlewin** [OpenEmu/OpenEmu#4119]
I am attempting to play Super Mario Sunshine and am dismayed to find that I cannot e-save and am hoping this problem would soon be fixed.

**Comment by clobber** [comment]
>e-save

Did you just make that up? I'm going to assume you mean "save state"

From the [release notes](https://openemu.org/rnotes/2.2.1.html) regarding GameCube emulation:

>Saves states are currently NOT enabled due to future updates breaking compatibility. 

They will not be available any time soon, if ever.

**Comment by bennettlewin** [comment]
What does future updates breaking compatibility mean?

**Comment by clobber** [comment]
Exactly how it sounds: Dolphin updates routinely break save state compatibility, where old saves are not compatible with the new version and won't load. This is due to the volatile nature of active emulator development, and should be expected. Instead, rely on in-game memory card saves whenever possible.
