### ISSUE TITLE
Controls not working on one particular N64 Game

### ISSUE THREAD

**Issue by lenchoj** [OpenEmu/OpenEmu#4164]
The controlls stopped responding only on one particular game (banjo tooie). Had been playing the game for a while with no issues, when suddenly they stopped responding. I tried closing all other apps, restarting the computer, retarting the game, and still won't respond. When I opened another game, the same issue happened, but after restarting I was able to play for a little while. I have tried opening the other games in the system and the games runs perfecly, except controls wont respond. I have tried turning off and on the privacy settings for input on the Catalina system, and still nothing seems to work

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.15.3

**Comment by lenchoj** [comment]
<img width="1282" alt="Screenshot 2020-04-01 11 45 48" src="https://user-images.githubusercontent.com/63002919/78169511-bc8ddf80-740e-11ea-8642-682d325bcd06.png">
<img width="930" alt="Screenshot 2020-04-01 11 46 49" src="https://user-images.githubusercontent.com/63002919/78169531-c1eb2a00-740e-11ea-890c-a98492f146e2.png">

**Comment by lenchoj** [comment]
Message for input monitoring appears even though it is turned on. Any ideas? I have also updated the system to the Catalina 10.15.4 and the issue persists.

**Comment by clobber** [comment]
You must toggle it off and then on again.

**Comment by lenchoj** [comment]
Thank you for your response clobber. I have done so several times and the issue still persists. Is there anything else I could try?

**Comment by lenchoj** [comment]
@clobber Thank you for your response. I have tried that already and the issue persists. I have even tried to toggle it off, restart the computer, toggle it back on, and the same appears to happen. Is there additional information you might need to see where the issue might be?

**Comment by clobber** [comment]
The solution depends on what the actual problem is. Per-game input bugs are not a thing unless there is an emulator bug (the Mupen64Plus core plugin), so if that is the case then I cannot help you. I'm skeptical that is the problem but N64 emulation in general does have issues.

If input is not working at all, for any games/systems:

OpenEmu **MUST** be granted input access otherwise it simply will not work. That message on launch comes from reading Apple API, so it's not an OpenEmu bug if macOS reports that it still does not have permission. Many have reported that when this problem occurs, toggling the setting off and then on again resolves the issue.

If OpenEmu is not asking you for input permission on launch but input still does not work, try the [Input troubleshooting guide](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems). Sorry, I don't think I cannot help you beyond that.

**Comment by lenchoj** [comment]
@clobber Oh ok, I understand. I had a later version of OpenEmu and updated it today to see if maybe that was the issue. If, by any chance, there was a problem with the N64 emulator, how would I go about uninstalling it, and downloading it again? Would I lose game progress if I did? I will try to see there might be an issue with the API or something. I havent deleted any files, but, just to make sure, besides the input setting, is there a driver or file needed in the system for it to properly work? Thanks for the input guide. Will verify all that info.
