### ISSUE TITLE
Support Folders in Game Library (Feature Request)

### ISSUE THREAD

**Issue by GryphonClaw** [OpenEmu/OpenEmu#4203]
Would it be possible to add Folders for the Games Library? for example in when SNES Library is selected, have the ability to add a Folder called: "Zelda Randos" and I could put all my Zelda Randomized Roms in said Folder

**Comment by clobber** [comment]
Sorry, no. You shouldn't need direct access to the ROMs folder since those files are managed by OpenEmu. Manipulating the contents of the Game Library folder outside the application will cause problems.

Instead, consider using the "Collections" feature to organize your ROMs within the app.

<img width="942" alt="Screen Shot 2020-05-01 at 9 51 21 AM" src="https://user-images.githubusercontent.com/1303132/80818974-5c1acb00-8b91-11ea-98a4-f5c0b63346e9.png">
