### ISSUE TITLE
Include a reference to generate .cue sheets on the wiki

### ISSUE THREAD

**Issue by git2samus** [OpenEmu/OpenEmu#4233]
I've found this site: http://nielsbuus.dk/pg/psx_cue_maker/ and this guide: https://www.youtube.com/watch?v=q23PGP8Iurk to generate missing .cue files from .bin or .iso dumps (which are the majority of roms out there).

The wiki currently suggests "to get a proper dump" but that's not really an option unless you find it somewhere else, with this tool you can generate the missing files for OpenEmu to work and use all the roms.

**Comment by clobber** [comment]
>which are the majority of roms out there

Not true.

Also, not a good tip. A disc dump without its cue sheet is considered a bad dump. The mode and sector size is unknown, as well as if CDDA tracks with their lengths and gaps are contained. Instead of downloading shitty warez from Uncle Jimbob's Elite Romz Jamboree with malware installers and popups, learn to download known **good dumps from "Redump" on Archive.org**.
