### ISSUE TITLE
Sega Saturn Emulation Problems

### ISSUE THREAD

**Issue by pyrolusite-d** [OpenEmu/OpenEmu#4245]
I tried to play Castlevania - Symphony of the Night's saturn version Akumajou Dracula X - Gekka no Yasoukyoku. Got the bin/cue files and the proper bios, but when I booted it up it was staggeringly slow. the picture quality wasn't affected, it was just running way too slow to be playable. No other console emulation had a problem like this. What can I do to make it run normally?
Thank you.

**Comment by clobber** [comment]
Your Mac is too slow to run Mednafen’s Sega Saturn emulation at full speed.  Nothing you can do about besides getting a new machine.

**Comment by SamKoi1224** [comment]
I have a similar problem with my recently modified iMac:

- iMac Late 2009 27" (iMac11,1)
- 2.93GHz Intel Core i7
- 32GB 1067MHz DDR3
- ATI Radeon HD 4850, 512MB
- 1TB SSD
- macOS High Sierra (10.13.6)

I tried to play Hideo Nomo World Series Baseball (Sega Saturn) on OpenEmu v2.0.9, but it was staggeringly slow and unplayable (as attached). The problem is, it worked just fine without any glitches on that iMac before I modified it.

- iMac Late 2009 27" (iMac10.1)
- 3.06GHz Intel Core 2 Duo (iMac10,1)
- 16GHz 1067MHz DDR3
- ATI Radeon HD 4850, 512MB 
- 1TB SSD
- macOS High Sierra (10.13.6)

The modified iMac looks faster and indeed any other apps (except SS on OpenEmu) do work much faster than before. Don't know why. Can anyone advise how to solve the problem?
 



[ss_hideo_nomo_wsb_slow.zip](https://github.com/OpenEmu/OpenEmu/files/4935825/ss_hideo_nomo_wsb_slow.zip)
