### ISSUE TITLE
No sound in macOS Big Sur Dev Beta 1

### ISSUE THREAD

**Issue by shokuninstudio** [OpenEmu/OpenEmu#4249]
Title is self explanatory. Everything else appears to work normally, just no sound at the moment.

**Comment by SuccySucc** [comment]
it's a developer beta, support for it will most likely not be a thing until Big Sur releases in fall

**Comment by NobodyNada** [comment]
@shokuninstudio What's your hardware configuration and what sort of audio output are you using? I can reproduce this issue under Big Sur, but only when using AirPods -- outputting through my MacBook's internal speakers works just fine.

I don't think this issue should be closed -- after all betas are not listed as unsupported on the [issue reporting guidelines](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems). If I was a maintainer, I sure would like to know about issues in the beta, since the issue will still have to be addressed when Big Sur is publicly released in a few months. I'm not a maintainer though, so take whatever I say with a grain of salt :)

**Comment by shokuninstudio** [comment]
> @shokuninstudio What's your hardware configuration and what sort of audio output are you using? I can reproduce this issue on my 2014 MBP running Big Sur, but only when using AirPods Pro -- outputting through the laptop's internal speakers works just fine.
> 
> I don't think this issue should be closed -- after all betas are not listed as unsupported on the [issue reporting guidelines](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems). If I was a maintainer, I sure would like to know about issues in the beta, since the issue will still have to be addressed when Big Sur is publicly released in a few months. I'm not a maintainer though, so take whatever I say with a grain of salt :)

Hi, I read the fix for the problem on a Mac forum. I deleted the app, redownloaded it and reapplied permissions in Security & Privacy preferences > Input Monitoring + Files and Folders.

That fixed the sound but after a day passed I have another issue that I have now reported.

Bluetooth is a bit shaky in this build of Big Sur. Can you repair your AirPods and check it is selected as the Output device.

**Comment by NobodyNada** [comment]
None of those workarounds fixed the sound for me. However, I dug into the code a bit and learned a little more about what's going on here. It appears to be a Big Sur bug, so I have filed a feedback with Apple.

In the meantime I have found a reliable workaround: open sound preferences and change your default *microphone* to something besides AirPods, for example your computer's internal microphone.

--- 

Under Big Sur, accessing [`-[AVAudioEngine outputNode]`](https://developer.apple.com/documentation/avfoundation/avaudioengine/1389103-outputnode) activates the *microphone* on AirPods. This appears to be a macOS bug, and I've filed a feedback for it. Of course, activating the microphone causes AirPods to switch into that awful 8kHz-mono audio mode. (This sometimes causes the helper application to crash, because it does not expect the audio configuration to change while it is being initialized).

Now for whatever reason, macOS starts asking OpenEmu's `OEAudioUnit` for absurdly large audio buffers (~3 seconds). I'm not sure why this is; it's probably another macOS bug but I'm not really inclined to investigate further. [`OEAudioUnit` tries to request a maximum buffer size](https://github.com/OpenEmu/OpenEmu/blob/5c4232e01c422bc35a8948c780a69c7fde585bc4/OpenEmu/OEAudioUnit.mm#L106) of 512 samples by setting the `maximumFramesToRender` property, but `AVAudioEngine` [does not appear to honor that property](https://developer.apple.com/forums/thread/111968?answerId=343425022#343425022) and sets its own value instead.

In any case, 3 seconds is an outrageous buffer size. OpenEmu only allocates an audio buffer [0.05 seconds long](https://github.com/OpenEmu/OpenEmu-SDK/blob/46e14221fa1137b6e676f879fd4f0cdd08737af8/OpenEmuBase/OEGameCore.m#L660), so the `OERingBuffer` implementation [kinda gives up](https://github.com/OpenEmu/OpenEmu-SDK/blob/46e14221fa1137b6e676f879fd4f0cdd08737af8/OpenEmuBase/OERingBuffer.m#L126) and no audio data is returned to the system (resulting in silence).

---

As you can see, there are a few bugs working together here, but the main one is that accessing the `AVAudioEngine`'s output device should not be activating the input device too. By changing the input device to something besides AirPods, `AVAudioEngine` does not activate the AirPods microphone, does not switch audio codecs, and does not request absurdly large buffers.
