### ISSUE TITLE
Unable to Open Save States in Zelda Ocarina of Time

### ISSUE THREAD

**Issue by timshutes** [OpenEmu/OpenEmu#4274]
Summary of issue

Zelda Ocarina of Time does not load autosaves on latest version of OpenEmu (on Mac OS Catalina). This is identical to the issue that was closed by the moderator due to the report happening on an older version of OpenEmu. Happy for this issue to be closed and that one to be re-opened. Not sure what protocol is there.

See https://github.com/OpenEmu/OpenEmu/issues/4087

# Steps to reproduce

1. Launch OpenEmu
2. Open Zelda Ocarina of Time

# Expected Behavior

1. Launch OpenEmu
2. Open Zelda Ocarina of Time
3. Auto loads the previous save state.

# Observed Behavior

1. Launch OpenEmu
2. Open Zelda Ocarina of Time
3. "The operation could not be completed. No further information is available at this time" message appears.
4. Title Screen appears.

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.15.6

**Comment by clobber** [comment]
There are no per-game core bugs specific to save states or macOS updates. The issue you referenced is a coincidence and not related to your own. The problem is you should not be using save states with N64 games at this time for reasons outlined here: https://github.com/OpenEmu/OpenEmu/issues/4090#issuecomment-578464779
