### ISSUE TITLE
Game library grid view empty on Big Sur Public Beta

### ISSUE THREAD

**Issue by joseph950521** [OpenEmu/OpenEmu#4276]
Hello, I'm using a 2014 MacBook Pro running the Big Sur Public Beta. The game library is empty when viewing with grid view, but lists all games with no problem on list view.

**Comment by freecodecampster** [comment]
Just to confirm same happens with dev beta 4.

**Comment by thiagosmartins** [comment]
Same for me here with Beta 4. Emulation is working fine, just the library is empty in grid view as well as saved states library.

**Comment by shysaur** [comment]
We are aware of this issue. However, since the grid view worked fine in previous betas, it's probably an OS bug that will be fixed in time for the final release of Big Sur (like many others before this one).

For the time being, this issue will be locked to avoid unnecessary traffic. It will be unlocked and fixed if the release version of Big Sur still has the bug.

Remember that beta macOS versions are unsupported. If you are using the Big Sur betas as your daily driver, it's at your own risk and peril.
