### ISSUE TITLE
How to get Gamecube Controllers working on OpenEmu?

### ISSUE THREAD

**Issue by Testleadz** [OpenEmu/OpenEmu#4281]
Im using a 3rd party adapter however it works perfectly on Dolphin, wondering if there was some sort of support for it and if so, how to do it? Thanks!

**Comment by tiramisu222** [comment]
I'm 98.7% sure adapters are discouraged with OpenEmu. Your best bet is to try it out. The GC core is based on Dolphin but with many changes so no guarantees. If it doesn't work, use another controller type. I recommend Xbox controllers because of its similar button layout. Be sure to map the triggers to L and R and the right shoulder button to Z. The A, B, X, and Y buttons work best mapped to the buttons of the same name. If you want to, try one of the many **(HID)** controllers that are replicas of the original but don't expect the plastic and buttons to feel the same.

**Comment by shysaur** [comment]
See https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems.

At the moment, OpenEmu only supports HID-compliant controllers and select very popular non-HID controllers. GameCube adapters tend to not work.

Our port of Dolphin does not use Dolphin's controller management code, thus even though Dolphin may support a controller, that doesn't imply OpenEmu's Dolphin port supports it as well.
