### ISSUE TITLE
How to reset an emulator after controller issue ?

### ISSUE THREAD

**Issue by Varhaan** [OpenEmu/OpenEmu#4316]
Hello, I wanted to change my controls in the N64 emulator, but after that the L button no longer worked (i wanted to switch L2 and R2 on my PS3 controller). So I would like to reset my controls or reinstall the emulator, can someone tells me how to do (if you think that could work) ?

**Comment by shysaur** [comment]
It is not clear exactly what your problem is.

You can't bind the same button to two different controls, therefore to switch the L and R controls you have to set them both again. In other words, if you re-map the L2 button to R, if the L button was also mapped to L2 it is un-mapped automatically, and you need to re-map L as well.

To clear a single controller binding in the Preferences you click on its box just like when you set it, and then you press "esc" on your Mac's keyboard.

To delete all bindings close OpenEmu, open Terminal, copy-paste the following command, and then type Enter (ALL your controller bindings will be deleted, not just N64 ones!):
`rm ~/Library/Application\ Support/OpenEmu/Bindings/Default.oebindings`
