### ISSUE TITLE
Can Someone Make An OpenEmu for Windows Please?

### ISSUE THREAD

**Issue by KloecknerStudios** [OpenEmu/OpenEmu#4348]
I have used a Mac before when I used to go to summer camp, and since I was in a film class I had to use iMovie to make the films. And I have always wanted to get an accurate Mac emulator for Windows, so I can use iMovie. But I looked on the reddit:

Question: https://www.reddit.com/r/OpenEmu/comments/jy59g2/can_i_run_openemu_on_windows/

and it said how OpenEmu was for Mac only, I wanted to know if someone can make OpenEmu available for Windows.

**Comment by MaddTheSane** [comment]
I don't know what you're asking: Are you asking for an emulator that can emulate a Macintosh, or are you asking for us to port OpenEmu to Windows?

1. OpenEmu support for microcomputers is in its infancy.
2. OpenEmu does not emulate a Mac at all.
1. OpenEmu uses a lot of libraries specific to macOS. In order to port OpenEmu to Windows, you'd need a _lot_ of work.

If you want a general-purpose emulator like OpenEmu, Use RetroArch.
If you want a Mac emulator, use Qemu.

**Comment by KloecknerStudios** [comment]
I am asking for both

**Comment by KloecknerStudios** [comment]
It is just that this website said I could use OpenEmu for getting iMovie:

https://www.3dize.com/imovie-for-pc/

**Comment by MaddTheSane** [comment]
OpenEmu isn't a Mac emulator. The site is wrong.

**Comment by KloecknerStudios** [comment]
Oh

**Comment by KloecknerStudios** [comment]
I am stupid
