### ISSUE TITLE
OpenEMU keeps changing the Arcade/MAME requirements, PLEASE HELP!

### ISSUE THREAD

**Issue by glitchHiker** [OpenEmu/OpenEmu#4353]
Every time I go to play a game that worked fine before it says that it now requires a game from mame 0.219 then another 0.2___ - currently its 0.225 - I've gone through this a handful of times now and have had to get new roms and some new chd files and the neogeo.zip bios file and whatever else. WHY does it keep doing this? IT'S EXTREMELY ANNOYING to say the least!! Is there some way to stop this? To somehow stop openemu from automatically updating the mame portion of the app or something? Why is it even doing it anyways? It seems every other month I gotta look up some new version of a few (OR MORE!!) games and/or chd files. I've actually found the full 0.225 chd files but can only find the 0.226 rom files - and downloaded them and then loaded them into openemu, but they won't work now! it still says I require the chd file from the 0.225 set - even though that's what I've just loaded into the app!! Is it possible it's because the roms are 0.226? But if that were the case then wouldn't it demand the 226 chd's??? I got the roms/chd's from the usual site I always use, (I'm not sure about the rules here so I won't mention it unless someone says its ok to!!!) idk if this is causing the problem now or what it is.. IDK what to do.. 

Just to be clear, I'm only having trouble with roms that require chd files - cps3 mainly.

I'm not exactly fully knowledged when it comes to all this stuff so if there's some reason for the constant updates and some way to perhaps update the chd and roms that I already have or something, or just some way(s) to deal with this constant and seemingly random change, I could really use some help!!  If it's possible to just convert/update the roms/chd files I already have into the new version required, that would be VERY ideal! Mac version would be prefered (obviously!) ANY help would be greatly appreciated! Thank you.

**Comment by tiramisu222** [comment]
I think this is a MAME problem, not an OpenEmu problem. MAME is [constantly updating,](https://github.com/mamedev/mame/releases) and the Arcade core implements the updates. I can't tell you why the updates cause breaking changes, I'm not experienced enough with the MAME development, but unless there's some odd changes to the MAME core upon implementation, this sounds like a MAME problem. Also, Arcade is in beta. There is no guarantees that anything will stay the same version to version. If you have to emulate steadily, use MAME.

_A little diversion here. You mentioned you download roms. Big no-no. That's piracy and heavily frowned upon here, at MAME, and at almost all retrogaming communities. Not to mention illegal. Buy the game off eBay for 2 dollars and dump it._

**Comment by clobber** [comment]
The latest versions of MAME require .CHD files to be in subfolders applicable to the name of the parent ROM set. For example:

`cap-33s-2.chd` would go in
`~/Library/Application Support/OpenEmu/Game Library/roms/Arcade/sfiii3`

`kinst.chd` would go in
`~/Library/Application Support/OpenEmu/Game Library/roms/Arcade/kinst`

@glitchHiker, few things:

* The application name is "Open**Emu**" - *Emu* as in *Emulator*. Not OpenEMU, not Open E.M.U.
* Use [MAME standalone](https://sdlmame.lngn.net/) and never update it, instead of OpenEmu, if you do not want to deal with learning about [how MAME works](https://web.archive.org/web/20180101211010/https://choccyhobnob.com/mame/demystifying-mame-roms/) and updating your MAME ROM sets.
* The next time you open a "OMG PLZ HALP!!!1" type non-issue on our bug tracker is a ban.
