### ISSUE TITLE
SteelSeries Nimbus – can map buttons for Quick Save and Quick Load, but no go when in a game

### ISSUE THREAD

**Issue by star-affinity** [OpenEmu/OpenEmu#4394]
Using a SteelSeries Nimbus I can map two buttons to Quick Save and Quick Load respectively, but when in a game (Sega Mega Drive) nothing happens when I press those buttons.

# Steps to reproduce

1. Map buttons for Quick Save and Quick Load in the preferences using a SteelSeries Nimbus controller.
2. Try to use those buttons when running a game.

# Expected Behavior

1. Pressing the buttons should execute the Quick Save and Quick Load menu items (⌘S and ⌘L).

# Observed Behavior

1. Nothing happens when pressing the on the controller mapped buttons for those functions.

# Debugging Information

- OpenEmu Version: 2.3
- macOS Version: 11.1

**Comment by clobber** [comment]
I cannot replicate any problem with those hot keys, global or per-system.

Some things to note and try:

* OpenEmu MUST be granted input access otherwise it simply will not work. That message on launch comes from reading Apple API, so it's not an OpenEmu bug if macOS reports that it still does not have permission. Many have reported that when this problem occurs, toggling the setting off and then on again resolves the issue.

* If OpenEmu is not asking you for input permission on launch but input still does not work, try the [Input troubleshooting guide](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems).

* Completely remove your Nimbus device from macOS Bluetooth Preferences and then add/pair it again.

Sorry, I don't think I cannot help you more beyond that.
