### ISSUE TITLE
Falsely reports ROM being in library

### ISSUE THREAD

**Issue by El-Has** [OpenEmu/OpenEmu#4396]
After updating to version 2.3 I tried to add a Mega Drive ROM to my library. I have been repeatedly getting the message "Already in library, but manually deleted or unreachable" when the ROM was not already in the library or manually deleted. The ROM came as a .md file which I've never seen before, and it doesn't go into the library.

# Steps to reproduce

1. Download ROM (In this case it's the Sonic the Hedgehog prototype that was recently dumped)
2. Unzip ROM if necessary
2. Drag and drop ROM into library, or import through the menu bar

# Expected Behavior

1. ROM imports
2. ROM is added to library
3. ROM becomes playable

# Observed Behavior

1. Add ROM to library
2. Message saying "Already in library, but manually deleted or unreachable" immediately appears

# Debugging Information

- OpenEmu Version: 2.3
- macOS Version: 10.15.7

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Importing#already-in-library-but-manually-deleted-or-unreachable

It *has* to be in your game library database because there is an entry for it in there, otherwise you wouldn't get that message. It may not be named something you expect, but it is there. Find the offending entry and delete it in the UI.
