### ISSUE TITLE
New N64 Core request.

### ISSUE THREAD

**Issue by ikea48** [OpenEmu/OpenEmu#4399]
This Is just a quick feature request, the request is semi-simple maybe I dont know, basically since MupenPlus has not been updated since two years ago you might consider using a new N64 core, if you do plan on doing this I recommend 1. Sixty force 2. Project64, yeah I know there's not many as a lot of these emus are pretty bad so yeah, if you dont want to change thats fine I just want to make this EMU one of the best. (You might also want to change you NDS core to MelonDS)

**Comment by clobber** [comment]
>semi-simple maybe

"This shouldn't be too hard" 🤣

> 1. Sixty force

Uh, that is not open source.

> 2. Project64

No, that is a Windows-only codebase.

Our Mupen64Plus core plugin [has been updated](https://github.com/OpenEmu/Mupen64Plus-Core/commits/master), quite recently in fact. It's not yet ready for release due to several issues. Please, in the future, do not open issues like these on our bug tracker.
