### ISSUE TITLE
Problems trying to import Final Fantasy VIII

### ISSUE THREAD

**Issue by GrapeZero** [OpenEmu/OpenEmu#4415]
Lately I have completed Final Fantasy VII, and wanting more, I have downloaded the sequel, Final Fantasy VIII. However, it will not import. I have tried to download the discs BINs without their respective cues and created the cues myself on a text editor, I have also tried to download a complete dump which has the BINs and cues included in a .zip file.

I know how to import a multi-disc game into emu, just create a .m3u file containing the names of the cues of their respective discs and put them on order. Here's some proof; Final Fantasy VII and Metal Gear Solid are two multi-discs, FF7 having three discs and MGS having two.
![Screen Shot 2021-01-08 at 6 37 30 PM](https://user-images.githubusercontent.com/77179935/104079961-c8e76a00-51e2-11eb-9343-53457e21ae78.png)

Does this problem have to do in the fact that FF8 has 4 discs and the actual limit is 3 or am I missing something important?

Any feedback would be of great help.

**Comment by clobber** [comment]
> I have tried to download the discs BINs without their respective cues and created the cues myself on a text editor

Instead, download known good dumps from "Redump" on Archive.org. OpenEmu 2.3+ will tell you the reason your games do not import. Cannot help you beyond this.

**Comment by GrapeZero** [comment]
> Instead, download known good dumps from "Redump" on Archive.org. OpenEmu 2.3+ will tell you the reason your games do not import. Cannot help you beyond this.

I'll try that since the most recent dump I tried to import was uploaded by Square, maybe that has to do something with the issue.

**Comment by lorenzo-pagliari** [comment]
I had a similar problem. I have downloaded the .bin files, made the .cue files and downloaded the .sbi files for all the four disks of FFVIII and also the .m3u file. However, when I import the game in OpenEmu the game shows up but OpenEmu still does not execute it. It says that it needs the .sbi files, even I have already drag and drop them into the emu.

I have already done this procedure for FFIX and it works fine, so I do not understand why is it not working for FFVIII

**Comment by clobber** [comment]
@lorenzo-pagliari 

> I have downloaded the .bin files, made the .cue files

Instead, download known good dumps of the games from a "Redump" set on Archive.org

> It says that it needs the .sbi files, even I have already drag and drop them into the emu.

Launch OpenEmu > Go to your imported game > Right click > Show in Finder ... that's where your `.sbi` files need to go.

**Comment by lorenzo-pagliari** [comment]
> @lorenzo-pagliari
> 
> > I have downloaded the .bin files, made the .cue files
> 
> Instead, download known good dumps of the games from a "Redump" set on Archive.org
> 
> > It says that it needs the .sbi files, even I have already drag and drop them into the emu.
> 
> Launch OpenEmu > Go to your imported game > Right click > Show in Finder ... that's where your `.sbi` files need to go.

Thank you very much. I did it correctly overall, but thanks to your suggestion I found out what was wrong.
I'll explain it even if it stupid, but it can help also others with the same trouble.
To me happened that trying to import the same game over and over due to an error, OpenEmu created in HIS library (not in my folder) an additional folder for that import. Therefore, I had like 6 folders called FF VIII, and every time I have imported the `.sbi` files OpenEmu put them in the first folder of the six.
So, in the end, I was trying to lunch the game from the last folder OpenEmu created but the `.sbi` files were always in the first one. That's the reason why for me it was not working.
Following the suggestion of @clobber, "`Launch OpenEmu > Go to your imported game > Right click > Show in Finder`" I found the multiple folders, deleted all of them, and import them again one last time correctly. Now the game is working properly.
If your game is not working, follow the aforementioned path to see if, from the OpenEmu perspective, everything is ok.
Thank you @clobber for the help.
