### ISSUE TITLE
Cannot add custom PSX rom

### ISSUE THREAD

**Issue by okla** [OpenEmu/OpenEmu#4438]
I have custom PSX rom (bin + cue) of Xenogears (with fan translation). When trying to add it to OpenEmu it returns error "No valid system detected". RetroArch and Duckstation import and play the rom just fine. Does OpenEmu support only "original" roms (that match with redump.org) or there is something else?

# Steps to reproduce

1. Import custom Xenogears rom

# Expected Behavior

1. Rom is added to library

# Observed Behavior

1. Import fails with error  "No valid system detected"

# Debugging Information

- OpenEmu Version: 2.3.3 (6866.4-g70ac442b-Release)
- macOS Version: 11.1 (20C69)

**Comment by clobber** [comment]
> or there is something else?

Presumably whoever did your translation altered the 16-byte "`  Licensed  by  `" disc header at offset `0x24E0` so now the ROM cannot be identified as PlayStation. Change it back with a [hex editor ](https://ridiculousfish.com/hexfiend/).

**Comment by okla** [comment]
Thanks, now it can be added, but loads like this

<img width="529" alt="Screen Shot 2021-01-24 at 11 43 42" src="https://user-images.githubusercontent.com/8558017/105625379-eac72a80-5e39-11eb-9816-31c8850f07c0.png">

**Comment by yoiang** [comment]
Is there somewhere that documents all the ways OpenEmu identifies which system to import to? I love that it automagically works but when it doesn't there isn't any insight and it'd be great to have a few things to try before bothering folks in Github (saw similarly an issue where someone didn't realized archives with multiple ambiguous files would get categorized under Arcade vs the system they expected)

**Comment by clobber** [comment]
@yoiang Information import requirements and failure is in the wiki guide:
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Importing

If a disc doesn't import, it's a bad dump. Instead, download known good dumps of the games from a "Redump" set on Archive.org. That's the best information one could possibly give regarding discs and is already in the guide. Likewise, ROM dumps should come from "No-Intro" sets (and headered depending on the system... NES, FDS, Lynx).

> saw similarly an issue where someone didn't realized archives with multiple ambiguous files would get categorized under Arcade vs the system they expected

From the guide:

> Single ROM files per zip may be imported -- but not for CD/Disc-based systems. Multiple files per zip cannot be imported.

...and since v2.3, OpenEmu has done a great job at catching import failure cases.

**Comment by yoiang** [comment]
Awesome, thank you!!
