### ISSUE TITLE
How to add shaders

### ISSUE THREAD

**Issue by deroa163026** [OpenEmu/OpenEmu#4529]
Found shaders but as lines of code not files. I read I can somehow get shader cg files and move them to shader folder in application support for openemu. Might be dumb question but what do I do to add these shaders to my openemu?

**Comment by clobber** [comment]
As of writing, the documentation hasn't been updated yet, but the old Cg files are not compatible with the new shader system.

Since version 2.1 there is a new configurable, multi-pass post processing shader system using **Slang**. To use slang files, they must go in a folder named after the shader that includes all the required files, and then run through our Go script that will package it into a `.oeshaderplugin` bundle which you can then drag and drop into the OE window to import. More information here: https://github.com/OpenEmu/slang-shaders

**Comment by MEPoss** [comment]
So what if someone would like to use one of the slang shaders on OpenEmu?
