### ISSUE TITLE
OpenEmu Keeps 'Forgetting' Wired Retro-Bit Genesis Bluetooth Controller Despite Allowing Button Mapping

### ISSUE THREAD

**Issue by happinesstan** [OpenEmu/OpenEmu#4549]
Hi guys

A lot riding on this one - I have a disappointed six year old nephew who can't play two-player 'old school' games with his uncle until this one is resolved so no pressure...!

(Using Catalina 10.15.7) I have two Retro-Bit Genesis Bluetooth Controllers, one of which pairs and maps fine over bluetooth. However, I understand that I cannot map the second controller over bluetooth as the Mac won't allow multiple bluetooth controller connections at once (unless I purchse a USB bluetooth dongle I assume).

So I plug in the second controller over USB. Initially it works fine and allows me to map/config buttons (bizzarely it comes up as a 'Nintendo Switch' controller) but once configured, when I go into (any) game, only the BT controller is recognised and going back into mapping shows that the wired controller is no longer in the drop-down as recognised. Pulling the USB out and back in again recognises it again but the cycle then quickly repeats itself.

Any help greatly appreciated and will make a six year old's day all the better!

Thnks in advance

**Comment by clobber** [comment]
> the Mac won't allow multiple bluetooth controller connections at once

That's not right. You can connect as many Bluetooth devices as you want.

I have these gamepads (both USB and Bluetooth, but NOT a 2.4 GHz dongle-requiring one) and don't recall any issues. It sounds as though one of your gamepads is ending up in a "mode" where it tries to present itself with a Nintendo Switch HID profile and is confusing our automap system. Try putting your gamepad in a different "mode" instead of the one for Macs listed in their manuals: http://retro-bit.com/controllers-support
