### ISSUE TITLE
N64 Save Games For Paper Mario ROM Hacks Overriding Each Other

### ISSUE THREAD

**Issue by SiriusDarkblaze** [OpenEmu/OpenEmu#4560]
So I know this is really specific but I have been playing some Paper Mario ROM Hacks, Black Pit, and Master Quest, and when I loaded up Black Pit it showed the save games for Master Quest (MQ for short), and when I went into the battery save path ~/Library/Application Support/OpenEmu/Mupen64Plus/Battery Saves, I found a single Paper Mario save game titled "PAPER MARIO (unknown rom).fla" and I was wondering if there was a way to reconfigure OpenEmu to designate which save game to use with which ROM because as it stands, even with the secret preferences menu open there isn't anything I have found that could allow me to do anything with it.

I did already find a workaround for it by compressing the current Save and renaming the compressed ZIP so I know which is which and can just unzip when necessary but that is a lot of extra steps to do. I also know I could make the steps faster by using Automator or scripting but still hoping there will be a better answer besides just use the workaround I have.

**Comment by bkimmett** [comment]
This is due to Mupen64's internal save naming scheme, as I understand (the internal ID of the rom, as with all PM64 romhacks, is 'PAPER MARIO', but the rom is not recognized as a retail game by Mupen). I'm in favor of keeping it because it's easy to swap between versions of the same romhack - just replace the rom and your save files carry over.

**Comment by clobber** [comment]
> I was wondering if there was a way to reconfigure OpenEmu to designate which save game to use with which ROM

Sorry, no there is not.
