### ISSUE TITLE
GB / GBA / GC Link cable support

### ISSUE THREAD

**Issue by edwardloveall** [OpenEmu/OpenEmu#458]
This is definitely a someday/maybe/wish list item, but it would be great to have some kind of emulation of two systems linking together. For example, all the Pokémon games require you to link two separate Game Boys together to trade Pokémon to complete the game (read: Catch 'em all).

As far as I know, current emulators don't support this.

References:
http://en.wikipedia.org/wiki/Game_Link_Cable
https://en.wikipedia.org/wiki/Nintendo_GameCube–Game_Boy_Advance_link_cable

**Comment by buchanancate** [comment]
I hope somebody does this soon, because I can't wait to play The Legend of Zelda: Oracle Series Linked Games!

**Comment by flmmartins** [comment]
+1 for this feature!!

**Comment by clobber** [comment]
To those that stumble upon this issue because of Pokemon trading:

Use cheats instead https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Cheat-codes
* For example, an 'encounter in the wild' cheat and master ball to get whatever you want
* Or try a ROM hack such as http://www.romhacking.net/hacks/2840/

We're already cheating by using an emulator (features such as save states, fast forwarding, rewind, etc) so let's not pretend the antiquated use of a system link cable is still necessary to "catch 'em all"
