### ISSUE TITLE
Nintendo RVL-CNT-01-UC not pairing with MacBook 15" (2017) through OpenEmu after upgrade from Big Sur to Monterey. OpenEmu crashing.

### ISSUE THREAD

**Issue by rmstxrx** [OpenEmu/OpenEmu#4612]
Hi there!

I have a pair of Nintendo Wii U Pro controllers (Nintendo RVL-CNT-01-UC), and I have been using them pretty much ok with my MacBook Pro 15"(2017, 512GB SSD, 16GB 2.133Mhz LPDDR3, Radeon Pro 560) with Big Sur. I have never used them together, just alternating between them every now and then.

However, after upgrading Monterey, the controllers started to behave oddly (slow inputs, stuttering), so I thought re-pairing could do trick. After unpairing, however, I could never pair it again.

I read OpenEmu's official page on the matter (https://github.com/OpenEmu/OpenEmu/wiki/User-guide%3A-Wiimote-and-Wii-U-Pro-pairing) and followed all the instructions, to no help. I think it is also useful to say I have never used any other software or driver to pair my controllers - I have always used OpenEmu's pairing feature.

Both controllers appear on the "Bluetooth Preferences" menu when I press the pairing button on them (red button behind the controller), but OpenEmu doesn't do anything after I click its scanning option. If I keep trying to pair the controllers through OpenEmu (say, three times, for example), the software locks for a few seconds (up to one or two minutes, sometimes) eventually crashing (although this doesn't happen constantly - sometimes OpenEmu comes back to proper functioning, but the controllers still don't pair).

I'm using OpenEmu 2.3.3, and macOS Monterey (12.0.1).

I've also attached Apple's crash report. Somewhere in the largest target stack there is a mention about connecting to IO bluetooth devices, so I think maybe something useful is in the report.

Thanks in advance!

[CRASH_LOG.docx](https://github.com/OpenEmu/OpenEmu/files/7442976/CRASH_LOG.docx)

**Comment by rmstxrx** [comment]
Downgraded from Monterey to Big Sur and everything started working again. Closing thread.

**Comment by rmstxrx** [comment]
For the sake of testing, after closing the issue I've decided to try pairing my controllers through OpenEmu (2.3.3) with my MacBook Air (retina, 13", 2019), macOS Monterey (12.0.1). The error was entirely reproducible - trying to pair the controller results in no action from OpenEmu or the controller.

I'm guessing downgrading to Big Sur could solve the problem (as it indeed did for the MacBook Pro), but I'm not gonna do it - it takes too long, and this machine wasn't really made for playing.

Everything said, the fact that the error was reproducible and that there was an instance where it was solved by downgrading to an older makes one legitimately think there might be something with OpenEmu that doesn't work quite right with macOS Monterey.

This is clearly an issue and, therefore, I've decided to reopen it.

**Comment by isaacclausen** [comment]
This is the case with all Wii remotes that I've tested.  Will not connect under Monterey.  Would love support for Wii remotes back...

**Comment by shysaur** [comment]
It works here with my own RVL-CNT-01-UC (AKA Wii U Pro Controller), but first you have to give Bluetooth access permissions to OpenEmu in System Preferences -> Security & Privacy.

This is a new setting in Monterey, which explains why it worked in Big Sur and earlier macOS versions.

**Comment by shysaur** [comment]
To clarify, Wii/WiiU controllers work when they have already been paired, but specifically pairing is broken because of a bug in macOS introduced in Monterey.

It's not possible to my knowledge to work around this bug, so downgrading or booting from an external hard disk are the only ways to be able to reliably pair Wii/WiiU controllers after you have updated to Monterey.

**Comment by preland** [comment]
Hello,

I've been looking around the internet to see if there is any way to fix this issue besides waiting for Apple to fix it, and I want to make one thing straight



> To clarify, Wii/WiiU controllers work when they have already been paired, but specifically pairing is broken because of a bug in macOS introduced in Monterey.
> 
> It's not possible to my knowledge to work around this bug, so downgrading or booting from an external hard disk are the only ways to be able to reliably pair Wii/WiiU controllers after you have updated to Monterey.

Does this mean that, hypothetically, if you were to have Monterey (or now Ventura) as your OS, and *somehow* figure out to downgrade back to Big Sur, could you then pair a Wii remote with the system, *upgrade back up to Monterey*, and have everything work fine?

If I am misinterpreting this, please correct me. However, if I'm not, I wonder if it would be possible to..... repurpose? Apple's Bluetooth module from Big Sur and before to connect older devices for newer Os's?

P.S: *(Note: all of this is just my own personal speculation; I don't really know that much about Bluetooth connections)*

I have done some debug testing myself with Xcode's Packet Logger, and it seems like the system and the remote initiate and even complete a connection, but the system (*not the remote, the system*) requests to disconnect, which succeeds, thus ending the connection. This, in effect, makes it impossible to connect a Wii remote, even if you were able to type in a correct PIN, at least as far as I can see it.

**Comment by preland** [comment]
Extra Extra P.S: The only reason I am writing any of this in the OpenEmu issues is because this is probably the only place where a solution could ever arise from. Dolphin doesn't know what to do with it, and they don't have that much drive to fix it, considering that MacOS isn't a major focus of their emulator. Furthermore, I have extremely large doubts about Apple fixing this. Apple is definitely aware of its bluetooth issues, and has made fixes to it in the latest major OS release (Ventura). Most notably, they added native support for JoyCon controllers. While this sounds good on paper, when you consider that Wii remotes **used** to work on Mac, while JoyCon controller support is an (almost entirely) new thing, the hopes of any real work being done is quite bleak.

Now, there are ways around this issue, the most straightforward of which being an external bluetooth dongle, but it still feels dumb for this to even be a problem.
