### ISSUE TITLE
Recent changes to OpenEmuKit crashes Mednafen.

### ISSUE THREAD

**Issue by dvessel** [OpenEmu/OpenEmu#4748]
Summary of issue

[Recent OpenEmuKit changes](https://github.com/OpenEmu/OpenEmuKit/commit/382ebf7562452842318ac3215d3960191dcb299f) crashing Mednafen core. Revert the commit _(along with the [corresponding OpenEmuShader commit](https://github.com/OpenEmu/OpenEmu-Shaders/commit/c5b980b031f9003f3b5030bffdcf8f6605e78b23))_ launches Mednafen without issue.

# Steps to reproduce

1. Clone repo.
1. Open in Xcode 13.4.1 and select `OpenEmu + Cores (Experimental, Alpha)` scheme.
1. Build for profiling.
1. Launch OpenEmu then any game handled by Mednafen. >> __CRASH__

# Observed Behavior

1. OpenEmuHelper.app crashes in the background.
1. Nothing can be launched again until OpenEmu is restarted.

# Debugging Information

- OpenEmu Version: Latest, built from source. 2.3.3
- macOS Version: 12.5 (21G72)
- [OpenEmuHelperApp-2022-08-06-100906.ips.txt](https://github.com/OpenEmu/OpenEmu/files/9275191/OpenEmuHelperApp-2022-08-06-100906.ips.txt)

**Comment by Gabe21001** [comment]
Hi.
Im commenting on this post because I have some problems with the app. The problems are that on Game Cube and Nintendo 64 there is a dashboard that say  core has compatibility issues and some games may contain glitches or not play at all.Please do not report problems as we are not responsible for the development of emulation app. when I'm playing Mario party 1 and the audio cuts almost at the end of the game, and there are lines on some of the mini games. What should I do?

**Comment by stuartcarnie** [comment]
https://github.com/OpenEmu/OpenEmuKit/commit/5240a37ce355c09c8136a0d9d5b7ed219ec5ba8b resolves the issue with Mednafen

**Comment by clobber** [comment]
Thanks for reporting. This is resolved. https://github.com/OpenEmu/OpenEmuKit/commit/5240a37ce355c09c8136a0d9d5b7ed219ec5ba8b
