### ISSUE TITLE
Virtua Fighter with Arcade/MAME core port

### ISSUE THREAD

**Issue by flashboss** [OpenEmu/OpenEmu#4758]
I explain with an example:

I have virtua fighter working on mame throgh two zip rom files: vf.zip and model1io.zip 

When I import the two files in the OpenEmu library and I start vf rom, it doesn't work because it doesn't find the other links inside model1io.zip 
What I have to do to make it working?

**Comment by digamejh** [comment]
Normally, I just import the rom I want to open (in this case, vf.zip) and the version of MAME handles all dependencies.  It even works with US sets.

But for Virtua Fighter, it gives me:
> Unable to load ROM.  
> This machine does not work and the emulation is not yet complete.  There is nothing we can do to fix this problem except wait for the MAME developers to improve the emulation.

(even though Virtua Fighter works in stand-alone MAME--after displaying a warning)

**Comment by clobber** [comment]
Our latest MAME core port is 0.235. You need to use ROMs from a MAME 0.235 ROM set.

The game, Virtua Fighter, does not load with the OpenEmu core port because it is marked as ["NOT WORKING" as of MAME 0.235](https://github.com/mamedev/mame/blob/ec9ba6fa76c3941272786e20232a1fcfc68594f3/src/mame/drivers/model1.cpp#L1899
). The game's broken status is even [noted in the source code](https://github.com/mamedev/mame/blob/ec9ba6fa76c3941272786e20232a1fcfc68594f3/src/mame/drivers/model1.cpp#L10-L13). The fact that you can "load" it with MAME standalone is irrelevant - it will let you load anything despite the status of the driver. OpenEmu core ports of MAME will never load "NOT WORKING" status drivers/games.
