### ISSUE TITLE
Imported roms assigned wrong console; no ability to move manualy

### ISSUE THREAD

**Issue by barnabyc** [OpenEmu/OpenEmu#679]
I imported a bunch of Sega Genesis roms, however they were mostly assigned to the Arcade group. I can't find a way to manually move them, and they don't have the correct Core association when in the wrong group.

Any suggestions? Thanks!

**Comment by beporter** [comment]
Is there a listing of which filename extensions are mapped to which cores anywhere? Or what internal logic is used to assign a drag-and-dropped file to a core? I'm mostly using ancient (OS 9 era) ROM files so I'm sure they're not "up to date" but OpenEmu is being "too helpful" and too opaque in its helpfulness. I know which console a particular file is _supposed_ to belong to, but OpenEmu still just does its own thing. If there was a guide to tell me how to correct my ROM files so that OpenEmu would smile favorably on them, it would help a lot.

**Comment by clobber** [comment]
@beporter Can you clarify the issue you're having (which system, the file(s) you are importing, etc) so we can clear it up?

**Comment by beporter** [comment]
@clobber Let me see if I can clarify by posing a question:

If I drag a file named `MyRom` (no extension) into OpenEmu, how does OpenEmu determine which core the file belongs to? What I'm asking for is documentation that makes it clear how the matching is done between a given ROM dropped into the app and the core it will be assigned to based on that matching. Is it _just_ by the extension on the filename? Is OpenEmu reading headers from file's contents? I can't find anywhere that explains how that process works so that I can make sure my ROMs are in a format that OpenEmu knows how to recognize.

As a specific example: I can drop a valid ROM file named `MyRom.bin` into Snes9x.app and it will load and play correctly. If I drop that exact same file into OpenEmu.app, it's mis-detected as an Atari 2600 ROM and fails to run (which is not surprising). If I rename the file to `MyRom.smc`, OpenEmu correctly assigns it to the SNES core, but still fails to run it. So it seems clear that OpenEmu is using some different logic to pair a ROM to a core and that whatever that logic is, it's much more restrictive than the cores themselves are capable of handling.

**Comment by eightball298** [comment]
> @clobber Let me see if I can clarify by posing a question:
> 
> If I drag a file named `MyRom` (no extension) into OpenEmu, how does OpenEmu determine which core the file belongs to? What I'm asking for is documentation that makes it clear how the matching is done between a given ROM dropped into the app and the core it will be assigned to based on that matching. Is it _just_ by the extension on the filename? Is OpenEmu reading headers from file's contents? I can't find anywhere that explains how that process works so that I can make sure my ROMs are in a format that OpenEmu knows how to recognize.
> 
@clobber, I know this thread is pretty ancient by now, but I'm having the same problem. Did you ever get this figured out mate?

> As a specific example: I can drop a valid ROM file named `MyRom.bin` into Snes9x.app and it will load and play correctly. If I drop that exact same file into OpenEmu.app, it's mis-detected as an Atari 2600 ROM and fails to run (which is not surprising). If I rename the file to `MyRom.smc`, OpenEmu correctly assigns it to the SNES core, but still fails to run it. So it seems clear that OpenEmu is using some different logic to pair a ROM to a core and that whatever that logic is, it's much more restrictive than the cores themselves are capable of handling.
