### ISSUE TITLE
(10.7) N64 doesn't render video

### ISSUE THREAD

**Issue by Swick34** [OpenEmu/OpenEmu#686]
When opening N64 games, I get a glitched looking screen, however audio plays so it seems the game is still running in the background. My card is a Radeon x1600 running on 10.7.5.
![screen shot 2013-07-09 at 7 27 58 pm](https://f.cloud.github.com/assets/4595602/771846/7ddef334-e8ef-11e2-936b-a0533e5ca847.png)

**Comment by clobber** [comment]
10.7 unsupported

**Comment by clobber** [comment]
Hi, I see you're upset and emoting on Twitter: https://twitter.com/swick34/status/642894332572381184

Sorry, but everyone has to upgrade eventually and we can no longer reasonably support older OS X. That isn't much of a reason to pout and you should understand the burden of maintaining a native application as featured as ours across several different versions of OS X. We held on for as long as we could, but now it's time to move on. Since 10.9, OS X updates are now yearly and free without dropping old hardware so we are taking advantage of this.

Regarding 10.7, it's dangerous to even be running such an old release - you're lacking critical security fixes and improvements. If your machine is locked into 10.7 due to 32-bit EFI, there are still ways to get later OS X installed which you can google.

**Comment by Swick34** [comment]
I'm not pouting. I did my part and brought the issue to your attention, waiting two years for some sort of fix or workaround. You chose to ignore it and then drop support for a large range of hardware. There are certainly valid reasons to do so, and you're free to do as you see fit, but you can see why I'm not particularly *thrilled*, and why I chose to plug a better-supported product that focuses on functionality over form.

Thanks for the security tip.
