### ISSUE TITLE
Dropbox sync for Saved States and Game Library

### ISSUE THREAD

**Issue by vinkla** [OpenEmu/OpenEmu#831]
Dropbox sync would be a really neat feature.

**Comment by ddbehsnilian** [comment]
I have managed to get this to work even if it is unsupported at the moment. Now let me clarify that I am I no way affiliated with the OpenEmu team, I’m just a thankful dude tryinng to give back a little. Having said that, I am trying this at my own risk and if anyone tries to do the same I will not be responsible for any consequences. This should only be attempted by people who know what they are doing. Even so I would advice to have a recent backup before embarking on this adventure.

Alright, now to the fun part.

I have found that it is possible to sync the entire OpenEmu Library, including all the stuff from ~/Library/Application Support/OpenEmu over Dropbox. I find this useful since I have a Mac Mini at home and a MacBook Pro for the road.

First of all I made sure to have the exact same version of the Experimental release of OpenEmu on both computers. Also important, whenever I update one I immediately update the other to the same version, before I even open the app. This is to avoid any problems that may stem from version differences.

If you already have your OpenEmu Library folder on Dropbox then skip this, otherwise create a new library inside Dropbox, close OpenEmu, overwrite the new empty library with the one with all your data. Relaunch OpenEmu.

Now for the OpenEmu folder inside ~/Application Support we’ll do the old symlink “switcheroo" trick.

	1. Copy the OpenEmu folder from ~/Application Support to somewhere on your Dropbox

		If you want things nice and tidy you can do as I did and create a Emulation folder on your Dropbox containing your game library folder and your application support/openemu folder

	2. Delete the OpenEmu folder form ~/Application Support and create a symlink to the folder’s new location inside Dropbox. This will “fool” OpenEmu into thinking all the support files are where they are supposed to be when they are in fact in your Dropbox. If you need to freshen up your symlink creating skills you might want to give Path Finder a try. It really does give Finder a run for it’s money. Otherwise you can use this command in the Terminal ln -s /path/to/original /path/to/symlink replacing the values as needed.

Anyway, whis is what you should end up with:

![7fcecc08-3da9-11e5-9f98-4d044063624f](https://cloud.githubusercontent.com/assets/13107306/9152162/f67dda48-3df3-11e5-8a46-e1e436b14282.png)

![914278b8-3da9-11e5-84fa-9a07f011a51b](https://cloud.githubusercontent.com/assets/13107306/9152167/08e6a840-3df4-11e5-9b7f-115dd10696e9.png)
